### ISSUE TITLE
Helium API returns country_id null for the hotspots in Northern Cyprus

### ISSUE THREAD

**Issue by ccavusoglu0** [helium/miner#1031]
Hotpots in Northern Cyprus have a major issue that their country id returns null from the Helium API.
https://api.helium.io/v1/hotspots/112CA7UxpkFPUM5QEbeAT5MqrH6Z7AEqDjKptV3H2LzBv29SCofF

Because country id is null, miners cannot take frequency and they currently can't provide local Proof of Coverage at all. 

**Potential reason** 
There are some political problems that have been going on for years in Cyprus. Unfortunately for this reason, it is currently governed by 2 separate states.
- Republic of Cyprus which is recognized and also in European Union (Southern part of the island)
- Turkish Republic of Northern Cyprus (TRNC) which is only recognized by Turkey as a result of the decision of United Nations Security Council (Code S/RES/541) since 8 November 1983

Internet in TRNC is also provided through Turkey. So the IP addresses appearing in the applications generally seem like we are connecting through Turkey. However geolocation shows Cyprus. This situation often causes problems on web applications because of the inconsistency.  

It seems like the geocoder used by the Helium API is also confused about this situation and it couldn't get country_id as Cyprus. 

**Comparison between hotspot in Republic of Cyprus & TRNC** 

Hotspot in South Nicosia (Republic of Cyprus) - 882da450bbfffff
![güney](https://user-images.githubusercontent.com/13016484/132093268-d2f747cc-d527-4b38-80d3-3524cc13442c.png)

Hotspot in North Nicosia (TRNC) -882da45569fffff
![kuzey](https://user-images.githubusercontent.com/13016484/132093287-cf48dc12-9bf5-4e98-ac49-1e1639cdd9c6.PNG)

It's the same city Lefkoşa is the Turkish meaning of Nicosia. Half of the city is under the control of the Republic of Cyprus and the other half is under the control of TRNC. It shows different names because of the IP differences.  

**Other example hotspots which country id is null** 
https://explorer.helium.com/hotspots/hex/882da4572dfffff
https://explorer.helium.com/hotspots/hex/882da45563fffff
https://explorer.helium.com/hotspots/hex/882da4475bfffff
https://explorer.helium.com/hotspots/hex/882da46b2bfffff
https://explorer.helium.com/hotspots/hex/882da46b0dfffff

As a Cyprus Helium community, we are expecting more than 250 hotspots to North of Cyprus this month and it has been already a month that people struggle with this problem. That's why we hope this situation gets fixed soon.

**Miner warnings because of this situation**
Sensecap:
![20210904_160217](https://user-images.githubusercontent.com/13016484/132095450-80bd2a2e-7a66-4918-9b84-a2459dd1107e.jpg)

Nebra: 
![h](https://user-images.githubusercontent.com/13016484/132094211-a323c3fa-58e4-4864-8a22-0e7ce482c485.jpg)

**Some suggestions**
-I'm not sure about which parameters do you use to validate country but apparently IP blocks would be problem
-In the fix you do, you can take the country as Cyprus regardless of looking if it is north or south
-I have seen some examples that some hotpots in the South but close to the border are also getting null value for country_id. 
https://explorer.helium.com/hotspots/hex/882da6a663fffff

**Comment by 3mRaH** [comment]
![Uploading 5F17D5F7-3867-4109-84EC-65578C22AA60.jpeg…]()

**Comment by 3mRaH** [comment]
![BA6B9371-03CD-4CA9-A007-7BF31BB2A882](https://user-images.githubusercontent.com/90114378/132108249-64124e49-0186-45eb-9605-fdab6f7f37cf.jpeg)

**Comment by 3mRaH** [comment]
![C578DE6A-166F-4E96-8E91-B18183F4B5C6](https://user-images.githubusercontent.com/90114378/132122375-592c377d-5002-424e-81cb-c4f5fd4334b9.jpeg)

**Comment by 3mRaH** [comment]
Hi my device is sensecap location is North cyprus.  I haven't found even 1 witnesses with 8 dbi for 1 month, it says null in the location. Can you help with null?

**Comment by cingscy** [comment]
Hi, I have the same problem. My device has been working for 12 days, there is no relayed situation, the device is synced, no internet problem etc. My antenna’s position is also good, 15m-5.8 dbi. There are no buildings around to restrict the signal. There are 4 more devices in North, and none of them has seen any witness for almost 1 month.  
•	I recently checked the region in my Sensecap dashboard, it is shown as Region: Unkown. As mentioned above, Country id returns null from the Helium API too.
•	I have used Hotspotrf simulation and It shows 55 witnesses in the simulation according to my information.
•	I ran discovery mode several times but 0 withness was shown.

We are concerned that because of this political situation, we are out of the witness circle. 

Thank you for your time and consideration. I hope to hear from you soon.
![hotspotrf](https://user-images.githubusercontent.com/90174847/132170666-3317e273-0d57-4dcc-bf26-b9396e9ab783.png)
![meanshadowsheep_explorer](https://user-images.githubusercontent.com/90174847/132170679-03d32438-7eac-43f1-a783-9a3937e5dacb.png)
![meanshadowsheep_explorer2](https://user-images.githubusercontent.com/90174847/132170684-fdde9ca8-b3a1-4d54-8324-5b56a6dd8607.png)

**Comment by caferelgin** [comment]
I'm anxiously following this issue as my miner is going to arrive soon. It would be frustrating to see the devices struggle to have witnesses after waiting so long.

**Comment by cingscy** [comment]
I also contacted my device manufacturer Sensecap tech support, I provide my device’s serial number. The tech support changed the region manually. So far it is working well. They wrote to me that it's a bug in the API of helium. When positioning, the machine will not get the code of my country region, resulting in an unsuccessful API call.

**Comment by ccavusoglu0** [comment]
> I also contacted my device manufacturer Sensecap tech support, I provide my device’s serial number. The tech support changed the region manually. So far it is working well. They wrote to me that it's a bug in the API of helium. When positioning, the machine will not get the code of my country region, resulting in an unsuccessful API call.

Hope someone will also help us soon

**Comment by ke6jjj** [comment]
This probably needs to be filed against the API repo, not the miner (which is where it's filed right now).

**Comment by shawaj** [comment]
> > I also contacted my device manufacturer Sensecap tech support, I provide my device’s serial number. The tech support changed the region manually. So far it is working well. They wrote to me that it's a bug in the API of helium. When positioning, the machine will not get the code of my country region, resulting in an unsuccessful API call.
> 
> Hope someone will also help us soon. As you see above I mentioned this issue to Nebra long before but couldnt make them believe as you see and now they locked the topic as off topic :) This company is like joke.

There's nothing we can do. The region is set by the miner and if that provides "unknown" then it will not work correctly.

Both Turkey and Cyprus are using EU868 as you can see here https://github.com/helium/miner/blob/master/priv/countries_reg_domains.csv

You probably need to raise an issue on this repo to have it fixed https://github.com/helium/lorawan-h3

**Comment by ccavusoglu0** [comment]
> > > I also contacted my device manufacturer Sensecap tech support, I provide my device’s serial number. The tech support changed the region manually. So far it is working well. They wrote to me that it's a bug in the API of helium. When positioning, the machine will not get the code of my country region, resulting in an unsuccessful API call.
> > 
> > 
> > Hope someone will also help us soon. As you see above I mentioned this issue to Nebra long before but couldnt make them believe as you see and now they locked the topic as off topic :) This company is like joke.
> 
> There's nothing we can do. The region is set by the miner and if that provides "unknown" then it will not work correctly.
> 
> Both Turkey and Cyprus are using EU868 as you can see here https://github.com/helium/miner/blob/master/priv/countries_reg_domains.csv
> 
> You probably need to raise an issue on this repo to have it fixed https://github.com/helium/lorawan-h3
I'm gonna move the issue there. Until it gets fixed, is there any temporary solution for Nebra customers? Is it possible to set region inside miner config files etc..?

**Comment by caferelgin** [comment]
gradoj/hplans repo eu868 map shows the whole island is in the region (except for the military bases), so according to this, there shouldn’t be a problem. You can see the map image below:

![0D74B139-62C2-44D6-8856-6CB105C8E8AB](https://user-images.githubusercontent.com/3657950/132596563-726c68c3-edba-44df-a6ae-48078c3095cd.jpeg)

so why does it show unknown?

**Comment by abhay** [comment]
Closing this issue since it's really a Geocoding problem. we can try to figure it out in https://github.com/helium/blockchain-etl/issues/235
