### ISSUE TITLE
Peerbook not updating IP address after a validator is moved (I think)

### ISSUE THREAD

**Issue by densone** [helium/miner#1035]
## System Details
Free BSD 13
Miner 1.2.2

## Problem Statement 
I've been running into issues where a new machine where all validators were migrated to it are being greatly affected with performance penalties. This machine cannot also maintain a peerbook connection to more than a couple peers.  

This machine also is very slow to receive new blocks and receiving disjoint errors. 

## Hypothesis 
If you check the helium api for an affected validator it shows the previous address of the validator. I was thinking this might just be an issue with API, but I am literally unable to connect to any address of a recently migrated validator. 

### API Record
`https://api.helium.io/v1/validators/112eNrLyRxSGmR32E4WKYUfwAgPCdCJT6yJaqttfQqNHWWtEPVZF`

```
root@cool_stinkbug:~ # /usr/local/miner/bin/miner peer connect /p2p/112eNrLyRxSGmR32E4WKYUfwAgPCdCJT6yJaqttfQqNHWWtEPVZF
Failed to connect to "/p2p/112eNrLyRxSGmR32E4WKYUfwAgPCdCJT6yJaqttfQqNHWWtEPVZF": not_found
```

The actual IP address of the validator is below and accurate to the machine. 

![image](https://user-images.githubusercontent.com/49484/132287822-6d5cf870-7645-4a00-ae44-3b3547357a31.png)

**Comment by abhay** [comment]
Something worth investigating. Here's an interesting progression. 

```sh
$ miner peer connect /p2p/112eNrLyRxSGmR32E4WKYUfwAgPCdCJT6yJaqttfQqNHWWtEPVZF
Failed to connect to "/p2p/112eNrLyRxSGmR32E4WKYUfwAgPCdCJT6yJaqttfQqNHWWtEPVZF": not_found
```

```sh
$ miner peer connect /ip4/51.79.36.113/tcp/2154
Failed to connect to "/ip4/51.79.36.113/tcp/2154": timeout
```

```sh
$ miner peer connect /ip4/45.57.233.190/tcp/2154
Connected to "/ip4/45.57.233.190/tcp/2154" successfully
```

```sh
$ miner peer connect /p2p/112eNrLyRxSGmR32E4WKYUfwAgPCdCJT6yJaqttfQqNHWWtEPVZF
Connected to "/p2p/112eNrLyRxSGmR32E4WKYUfwAgPCdCJT6yJaqttfQqNHWWtEPVZF" successfully
```

**Comment by abhay** [comment]
@densone do you have any interesting logs to share on the IP change?

**Comment by densone** [comment]
ahhhh ok.. any way to xfer. No interesting logs at all. I can however give professor or whoever a login to the machine or a live walk through if they'd like to look at it directly.

**Comment by Vagabond** [comment]
You need to look at the current view that node has of the peer book, it may have a stale version. If it fails to dial, it will request any newer versions of that peerbook entry from its peers and so it will likely work next time.

Secondly, connecting via IP will allow you to obtain a peerbook entry directly from the other peer, which also will fix this issue.

If the peerbook entries seem to be regressing then you either have 1: clock skew (probably on the remote peer) causing the older (but chronologically newer) peerbook entry to supersede the newer but chronologically older peerbook entry. Or 2: you have two nodes running with the same swarm key.

**Comment by densone** [comment]
<img width="248" alt="image" src="https://user-images.githubusercontent.com/49484/132399615-58f46dcf-7c5d-4188-a090-ea0c7b0e7766.png">


ok so something went horribly wrong with my clock.

**Comment by densone** [comment]
going to close this one. Looks like we need to do some more babysitting on chrony.
