### ISSUE TITLE
Can I change the official docker image with self-building image?

### ISSUE THREAD

**Issue by zxgangandy** [helium/miner#1043]
Hi, guys, I found that when I replace the official image with my docker building image, my peer info has changed, the address and peer name also changed. How can i to fix the issue? By the way , Can I  use the official source code to build a new docker image to replace the docker image in the hotspot? Are there any differences? What should I do ?

**Comment by zxgangandy** [comment]
just close

**Comment by Domain4dmin** [comment]
@zxgangandy: have you found a solution?
