### ISSUE TITLE
RAKv2 fell out of sync and cannot catch up to block

### ISSUE THREAD

**Issue by keys120** [helium/miner#1047]
RAKv2 fell out of sync on Sept. 8 and 48 hours later still cannot catch up to the block. It is connected to internet and downloading 3GB a day. Last reported block is 1,002,780.

Interesting Lemonade Barbel

**Comment by onehelium** [comment]
Same issue - been 24 hrs now - I have rebooted a couple of times, reset the internet - any ideas

**Comment by onehelium** [comment]
Raspy Magenta Huskie

**Comment by abhay** [comment]
> RAKv2 fell out of sync on Sept. 8 and 48 hours later still cannot catch up to the block. It is connected to internet and downloading 3GB a day. Last reported block is 1,002,780.
> 
> Interesting Lemonade Barbel

Please contact hardware support. This sounds like it may be a hardware issue.

**Comment by keys120** [comment]
I have had 3 RAKv2s go down today. All the same issue. Doubt it’s hardware:

Interesting lemonade barbel
Mean leather parrot
Scruffy Crepe Elephant

**Comment by onehelium** [comment]
Yes, I doubt it is hardware - Raspy Magenta Huskie has been active since
March - connected via ethernet.

Does anyone know what the yellow/orange symbol means next to the 100% on
Blockchain sync?  1:43pm CDT yesterday was the last activity.

Thanks
Brian

**Comment by abhay** [comment]
It certainly isn't an issue that is relevant to the miner repo. 40k+ RAK hotspots seem to be keeping the chain and creating challenges. 

Closing for now to allow for conversation in Discord and/or hardware support channels.
