### ISSUE TITLE
Expose asserted antenna gain via cli (and RPC)

### ISSUE THREAD

**Issue by timcooijmans** [helium/miner#1048]
To be able to adjust transmitting power on the hotspot, it would be great if the asserted antenna gain is exposed via CLI, just like the asserted region is.

Because CLI has some issues with zombie-processes, it would be great if this information is also exposed over RPC.

**Comment by abhay** [comment]
Could be useful, @jadeallenx @Vagabond makes sense?

**Comment by madninja** [comment]
yes it does

**Comment by timcooijmans** [comment]
@madninja technically yes but I’m afraid `info_summary` does too much “on the side” to make it feasible for polling every 5 minutes or so. I was hoping for a RPC like `info_region`: https://github.com/helium/miner/blob/2e12527d2d49a91b146bdde15d854876fe9cfa67/src/jsonrpc/miner_jsonrpc_info.erl#L46
