### ISSUE TITLE
Miner loses witnesses and stops earning HNT

### ISSUE THREAD

**Issue by glu-04** [helium/miner#1051]
As of 5 days ago my miner, Lone Taupe Baboon, shows I have zero witnesses and no earnings. The miner has been up and running with no issues for 2 months now. It's been in the same location the entire time and I haven't cycled the power either. I ran a discovery test and it shows I can connect to other hotspots. I've also noticed that a couple of the other miners around me also have zero witnesses with a complete drop off in earnings as of a few days ago as well. The issue seems to coincide with a recent 9/3/21 miner update.

[helium discovery results.txt](https://github.com/helium/miner/files/7148429/helium.discovery.results.txt)

![Screenshot_20210911-123421](https://user-images.githubusercontent.com/86620463/132960252-989062b1-2886-4bcd-b1a5-76d05d8c86d2.png)
![Screenshot_20210911-123355](https://user-images.githubusercontent.com/86620463/132960255-09e11560-664f-475f-8a22-b020bdd2f1c1.png)
![Screenshot_20210911-123229](https://user-images.githubusercontent.com/86620463/132960256-aaf33273-211d-4401-be58-800df9339cca.png)
![Screenshot_20210911-123038](https://user-images.githubusercontent.com/86620463/132960257-d7e745eb-97ca-4b43-8ace-b1ff94a67d0a.png)
![image](https://user-images.githubusercontent.com/86620463/133003197-39996610-27b6-48a1-aa12-c2f4c3ba35d8.png)

**Comment by simonthepieman70** [comment]
I am having the exact same issue

**Comment by glu-04** [comment]
It looks like it's working again after I powered off and then powered on the miner, though now it's in a Relayed state. Perhaps a recent update required a restart? I'll keep this issue open for a little longer in case the miner loses witnesses again or someone else runs into the same issue.

**Comment by abhay** [comment]
Bobcat firmware updates should be discussed on Bobcat support channels. This repository is specifically for the miner code base that is a subset of that firmware.
