### ISSUE TITLE
To go no DIY when there’s a supply shortage

### ISSUE THREAD

**Issue by midtur** [helium/miner#1060]
It's a small antenna anyone could buy off of Amazon or eBay and a cheap raspberry pi. 

Helium Inc collects premium from every transaction. The data is not open source either. The LowRan service is propriety so the Internet has a bottleneck by design.

Top of pyramid is Helium.
Hotspot manufacturers must pay a hefty fee to Helium inc to be an "authorized vendor" Hotspot purchasers $40 to be placed on the network (costs nothing for Helium inc.  ![image](https://user-images.githubusercontent.com/74473427/133386467-59c9ef13-9884-41ba-81b8-b6a0a4502623.jpeg)

**Comment by abhay** [comment]
Helium Inc does not take any fees from hotspot manufacturers. Feel free to read up on the HIP 19 process here rather than spreading a false narrative.
