### ISSUE TITLE
"Error constructing the add hotspot transaction.”

### ISSUE THREAD

**Issue by HelloCyle** [helium/miner#1069]
After port forwarding appropriately 44158 and even following it up with connecting directly to the Nebra hotspot with Ethernet, when finally submitting registration, the following error message appears: “There was an error constructing the Add Hotspot transaction. Please try again.” I’ve repeated over 30 times - no success.

**Comment by evanmcc** [comment]
Please contact Nebra support, this is not the correct venue.
