### ISSUE TITLE
Error: No onboarding info found for this miner's onboarding key.

### ISSUE THREAD

**Issue by fredsco** [helium/miner#1077]
After setting up the miner both the hotspot app and the docker command: docker exec miner miner info onboarding results in that there is no onboarding key (or info) found..

docker exec provision gateway_mfr ecc onboarding  gives me an onboarding key! 

And docker exec miner miner print_keys print a pubkey and onboarding key (which are both identical)

**Comment by evanmcc** [comment]
I'm not sure what you're trying to do here?  We're not allowing any more DIY miners, iirc.
