### ISSUE TITLE
Weird innvalid witnesses with "witness_on_incorrect_channel"

### ISSUE THREAD

**Issue by leo-karelics** [helium/miner#1080]
There are 2 miners 810m from each other. Antennas are on the roofs.
https://explorer.helium.com/hotspots/11wKPumKmp6mBnqPQ3fgprFpyQeFPuoUz8gxNJmPoZXceFiD8FG
https://explorer.helium.com/hotspots/112tx7amVxWJN7YPQpb7MeBXmpZrcL4ofKz5aUrZT4RzUZna1c4z
No relayed status. 

There are many invalid witnesses. But some witnesses are correct. Could not find any answer in discord and could not understand it from the code. What might be the reason? Can it be that the validation code is wrong? Should documentation be updated?
![image](https://user-images.githubusercontent.com/67486992/134582731-59ec8ef9-b208-4517-b08e-047b23bb6120.png)

**Comment by DmitryX1** [comment]
I also wonder if this is due to the inconsistency with the Russian frequencies

**Comment by shawaj** [comment]
> I also wonder if this is due to the inconsistency with the Russian frequencies

Are some people not running with ru864 then?

**Comment by leo-karelics** [comment]
This can be because of eu868-miner running there. But still interesting is that 1) it uses usually the correct frequency (864) and 2) sometimes witnesses are valid ....

**Comment by DmitryX1** [comment]
как решился вопрос?

**Comment by leo-karelics** [comment]
It was a bug related to preparation to PoCv11 and fixed couple releases ago in blockchain core repo. Now I don't have this issue any more, but I saw there that the code was just moved and probably after activation of PoCv11 it will come again, let's see
