### ISSUE TITLE
Bobcat miner issue after halving and firmware update in the end of August

### ISSUE THREAD

**Issue by steve338866** [helium/miner#1090]
My bobcat miner was not mining during and after firmware update in August. It was syncing for a week and then the low earning begins. Before the firmware update, my bobcat miner was earning 2 HNT per day with 4 dbi antenna. After the update, it was earning 0-0.25 HNT per day. I tried to swap out the antenna from 4 dbi to 5.8 dbi but still not improving. The scale also dropped from 0.67 to 0.25 after the update. Please help!

**Comment by shawaj** [comment]
The scale is determined by hotspots in your hexes and has nothing to do with any updates.

The halving, as well as more hotspots being on the network, will have reduced your earnings
