### ISSUE TITLE
Not Witnessing Beacons! Beaconing though to 10 Hotspots.

### ISSUE THREAD

**Issue by astritm** [helium/miner#1092]
My Sensecap hotspot is not Witnessing Beacons. Although it is sending beacons to 10 hotspots.
Antenna gain of 3dBi is put on the roof and discovery mode shows 48 hotspots responding.

https://my.heliums.online/hotspot/11K26xEjtSAVMqrbCqFTjB3MknaBbnJFpzTRpULVL5rNWwrMsSa

**Comment by mamartins** [comment]
Same here, 47 witnesses and like 2/3 witnessings per day!!!

11SS6jPX9SRw3DjqPEiZR4WX5byLKJCoTGfHhDuAvV7M8Jjg35f

**Comment by wolasss** [comment]
Same here, in the last few days I am constantly getting 0 witnesses on all my hotspots (since 20-21 Sept). Seems that something was broken along the updates. I think it is not the first time regression is introduced.

**Comment by Lusitanea** [comment]
Same here!
I have read about this kind of situation in the Discord forums. Many people saying that their miners went from a lot of HNT to almost nothing, in the last week

**Comment by abhay** [comment]
As always. The docs have the best information on why a beacon may not have witnesses: https://docs.helium.com/troubleshooting/understanding-witnesses/

**Comment by astritm** [comment]
@abhay the link explains the witness list. Im not saying I have 0 Witnesses in my list, my Beacon is heard from 10 HotSpots all the time. The issue is why I am not hearing other HotSpots Beacons for days. Something’s wrong here, and my issue is not solved, did you check the link I provided. Please open the issue…

![309E061F-E148-49E5-B4E8-5AC065682824](https://user-images.githubusercontent.com/45420135/134850029-6bf9927a-6597-49a3-aa84-1c47d02ed899.jpeg)

**Comment by mamartins** [comment]
Same problem as @astritm.  I'm sending beacons and they're listened by 10 HS but I'm receiving few beacons to witness on one particular device.

**Comment by astritm** [comment]
and the btw, discovery mode finds 58 HSs responding…

**Comment by mamartins** [comment]
@abhay pls re-open the issue as this is clearly a problem

**Comment by aliibra1** [comment]
I have the same Issue, what antenna are you using, cable , height ?

**Comment by Masakrx** [comment]
> @abhay the link you sent explains the witness list. Im not saying I have 0 Witnesses in my list, my Beacon is heard from 10 HotSpots all the time. The issue is why I am not hearing other HotSpots Beacons for days. Something’s wrong here, and my issue is not solved, did you check the link I provided. Please open the issue…
> 
> ![309E061F-E148-49E5-B4E8-5AC065682824](https://user-images.githubusercontent.com/45420135/134850029-6bf9927a-6597-49a3-aa84-1c47d02ed899.jpeg)

Same thing here. I have Bobcat 25m (rooftop) with 6.5dbi with 1m cable and beacons are 18 and witnesses are almost non existent. Was planing switching back to stock antenna coz this is not working for some reason.

**Comment by mikeBreaksShit** [comment]
I  am having this exact same issue. Any ideas on what the issue is. My miner is future mercurial penguin

**Comment by mdepaepe2** [comment]
I see some of you guys got your hotspots to get more active, how did you solve the issue?

**Comment by wolasss** [comment]
I personally didn't do anything, it seems the recent libp2p fixes that were released finally fixed those issues in my case

**Comment by magoespa** [comment]
> > @abhay the link you sent explains the witness list. Im not saying I have 0 Witnesses in my list, my Beacon is heard from 10 HotSpots all the time. The issue is why I am not hearing other HotSpots Beacons for days. Something’s wrong here, and my issue is not solved, did you check the link I provided. Please open the issue…
> > ![309E061F-E148-49E5-B4E8-5AC065682824](https://user-images.githubusercontent.com/45420135/134850029-6bf9927a-6597-49a3-aa84-1c47d02ed899.jpeg)
> 
> Same thing here. I have Bobcat 25m (rooftop) with 6.5dbi with 1m cable and beacons are 18 and witnessing is almost non existent. Was planing switching back to stock antenna coz this is not working for some reason.

Same issue here, with exactly the same setup. Did you manage to solve it? Thanks

**Comment by derryxs** [comment]
I have same exact problem, any solution?
I can send beacons and they can well heard by other hotspots signal levels are good, but cannot witness from them,

**Comment by maximdepaepe** [comment]
> I have same exact problem, any solution? I can send beacons and they can well heard by other hotspots signal levels are good, but cannot witness from them,

Since i have an Older Heltec Model I had to buy a filter on aliexpress.
Seems to be working fine now for me.

**Comment by florian-asche** [comment]
> > I have same exact problem, any solution? I can send beacons and they can well heard by other hotspots signal levels are good, but cannot witness from them,
> 
> Since i have an Older Heltec Model I had to buy a filter on aliexpress. Seems to be working fine now for me.

what filter did you buy?

**Comment by ObiTwo2** [comment]
This was the problem I had as well. The problem was that I was quite close to a 4g cell tower and it was saturating my reception signal. I could send a beacon out and others could witness me, but I was witnessing only the occasional very nearby hotspots. As broadcast and reception signal are the same shape and power, it made sense that something was stopping reception. Bought a 915 MHz Bandpass Filter and hey presto, problem solved. It effectively blocks everything outside of the band I am looking at, reducing the noise, such as from the nearby 4g mobile cell tower.

**Comment by Aviatorxxx** [comment]
Just installed a 915 MHz Bandpass Filter to see if it cures the problem. Running a Sensecap with a 5.8dBi @ 8m using LMR400. fair amount of beacons and no witnesses.
