### ISSUE TITLE
AS934-4 not handled in miner_lora_throttle.erl

### ISSUE THREAD

**Issue by t0mmyz7** [helium/miner#1094]
Hi

we notice that as923-4 region is not listed in miner lora throttle and it probably should be right ?

https://github.com/helium/miner/blob/8793f7417fcceb8007f2082edb9293698478faf3/src/miner_lora_throttle.erl

**Comment by tzacha** [comment]
Hi @vihu 
can you help with adding support for region_as923_4 
it looks like need to be added in 2 lines... at miner/src/miner_lora_throttle.erl

thanks in advance

**Comment by tzacha** [comment]
Thanks Vihu
