### ISSUE TITLE
Problem with city names in Kosovo

### ISSUE THREAD

**Issue by betimi91** [helium/miner#1096]
Until two or three days name of Country Kosovo was working in Search in Helium Map Coverage/Explorer and all cities within their names but I see that now if you search for a city like Prishtina before it was showing total number of devices and the correct flag now shows less devices and it has Serbian flag.

More information for Kosovo as a country can be find in https://en.wikipedia.org/wiki/Kosovo so please keep this project away of politics because there are a lot of young people who bought the devices for creating Hotspot and waited 4-5 months to receive and spent money on them.

We are in same frequency as Albania, Germany and other EU countries there is also no restriction by regulator here for it.

If you need anything more regarding this issue please let us know.

**Comment by abhay** [comment]
This report is somewhat old so I'm going to close it for now. This particular issue seems more relevant for the [helium/explorer](https://github.com/helium/explorer) repo as well.
