### ISSUE TITLE
Invalid witness  on incorrect  channel 

### ISSUE THREAD

**Issue by yaswanth-source** [helium/miner#1127]
![Screenshot_20211013-154141_Chrome](https://user-images.githubusercontent.com/85169964/137156678-507dc232-ed8d-43b1-b8bd-0992ac8f0aa0.jpg)
![Screenshot_20211013-154119_Chrome](https://user-images.githubusercontent.com/85169964/137156699-c64c0f42-1620-4696-ae59-c664ccb7f286.jpg)
![Screenshot_20211013-154059_Chrome](https://user-images.githubusercontent.com/85169964/137156716-7aed2ce1-eb1e-4e2d-87a0-3ebd53131358.jpg)
Is there any update in regards to witness invalid wrong frequency channel . All Indian hotspots are having the same issue since 3-4 weeks now and there was no help from the developers wer as Australian hotspots has same issue which is been fixed and nothing is  done to fix the issue .

**Comment by abhay** [comment]
We may have found an issue that should have been guarded behind a check on whether or not PoCv11 was active. Some work is required here to roll this out and manufacturers will need to update when we issue the miner changes in a release.

**Comment by 4hourwork** [comment]
Also I had a  same invalid "witness on incorrect channel"  issues until Sep.16 on Sensecap HS. 

<img width="370" alt="Screen Shot 2021-10-20 at 9 10 08 PM" src="https://user-images.githubusercontent.com/84188541/138090147-1da70bb6-7af6-4cce-9b45-78113e55a666.png">
<img width="373" alt="Screen Shot 2021-10-20 at 9 08 33 PM" src="https://user-images.githubusercontent.com/84188541/138090160-b4349ef0-0631-493d-8373-ba61d23c318a.png">
<img width="408" alt="Screen Shot 2021-10-20 at 9 08 02 PM" src="https://user-images.githubusercontent.com/84188541/138090161-667eac11-24f4-45d4-85d0-f6060d9ad0ce.png">

**Comment by abhay** [comment]
This report is somewhat old so I'm going to close it for now. Hopefully you've seen some improvement since the more recent releases. Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
