### ISSUE TITLE
Bobcat hotspots set in AU915 region not witnessing other beacons.

### ISSUE THREAD

**Issue by gabriol23** [helium/miner#1143]
I have currently 2 Bobcat hotspots set in Medellin, Colombia. Namely: Big Vanilla Swan and Howling Felt Cormorant. There are another 15+ Bobcat hotspots set up in the same city and within range of these two (4dbi, 50 meter outside placement with complete LoS, synced and not relayed), yet all of them follow the same pattern:

1. Bobcat sends out beacon.
2. Beacon is only witnessed by other hotspot vendors (CalChip, SenseCap, Helium Miner v1, etc) of which there are only 6 in the city.
3. Bobcats DON'T witness each other's beacons nor beacons from other vendors' hotspots.

Same issue with discovery mode. The only hotspots listening and responding to the pings are the other vendors' hotspots.

This leads me to believe that Bobcats, although showing correct region assignment on the Diagnostics page, are not really listening on the correct channels. They can beacon on AU915 but are not listening. The same pattern applies to Bobcat hotspots in Bogota, Colombia. Unless there's another vendor's hotspot around, the Bobcats will get no witnesses whatsoever.

I examined each Bobcat hotspot in Colombia on the explorer and ALL of them are presenting the same issue.

**Comment by rvjaywaks** [comment]
This also happens in the Philippines, after the frequency changed from us915 to AS923.

**Comment by BautiDelp** [comment]
Did you find a solution to the problem @gabriol23 ? I'm having the same issue in Argentina

**Comment by rvjaywaks** [comment]
![image](https://user-images.githubusercontent.com/2319264/140695088-03ad90dc-5e70-4c68-8619-9040a682fa15.png)
seems bobcat don't want to help us.

**Comment by cdkeensd** [comment]
We are having the same issue in Trinidad & Tobago . We are in ITU-R Region 2 which uses US915 , however Lora Alliance which I believe Helium is getting their Frequency Allocation from has alot of places configured incorrectly to ITU-R Region 3 which is Australia/Oceana

Everything in Region 2 should be using US915
https://www.itu.int/en/ITU-R/terrestrial/broadcast/PublishingImages/bcd%20images/ITU%20regions.jpg

**Comment by shawaj** [comment]
@gabriol23 can you maybe message bobcat and see if they'll send you the AU915 config they are using?

**Comment by jpouza** [comment]
Somebody has a clue about a fix for this?
After October's PoCv11 update, Bobcat screw up US915 miners located at AU915 regions, all other brands are still 100% functional, except bobcat :(
Also, customer support won't help us at all, they really don't care about this and yet they said that US915 weren't tested/certified for AU915 operation, OMG, it wouldn't hurt if they could remotly fix this, the earnings are about 10x less than before the fw update.

**Comment by jfgmdp** [comment]
It is NOT clear to me wether if the BOBCAT (originally US915) will do autswitching. when installed in another area

**Comment by anakletus1988** [comment]
i hace the same issue, and Bobcat send me an email saying that you have to get one of the new ones that can work in those regions.... so Bobcat is not going to fix this.....

**Comment by abhay** [comment]
This appears to be a Bobcat specific issue. Please contact Bobcat support.

**Comment by PJEstrada** [comment]
Anybody had any luck fixing this issue? Same problem with bobcat miner US915 frequency but seems that my country (Guatemala) is AU915. Is there a way to change this on the miner?

**Comment by whoisjdp** [comment]
I try to contact bobcat, still waiting on how to solve it for US915, I found out the issue, here in the Dominican Republic, beacons are transmitted over 917-918 MHz, where in the US they are transmitted over 903-905 MHz. So bobcats out here are not witnessing beacons, only sending them out. Sensecap, Nebra, and RAK V2 all witness beacons at 903-905 MHz and 917-918 MHz, have another guy with same issue...

Check frequency from others around you to see if this is the issue... If someone has any clue, most appreciated.
