### ISSUE TITLE
Ticket 281663

### ISSUE THREAD

**Issue by adam2585** [helium/miner#1161]
Hi Kevin, I sent you my hotspot over a month ago as it would not update the firmware and would not connect to the block chain, the ticket number is (#281663), I was told it would take 5 days for the engineer to sort out, this was over a month ago now! Please can you update me on this issue.  
I have tried every avenue possible to get a reply from Nebra, I find it absolutely disgusting that you have confirmed you have received my hotspot, told me it will take around 5 days and then I haven't heard anything for a month!!!! That is a whole month of lost earnings! Please can you update me with where my hotspot is!!!!

**Comment by abhay** [comment]
Although this sounds incredibly frustrating, the helium core team cannot help with a Nebra hotspot and this codebase is meant for software that that runs on all hotspots. Please contact Nebra support directly.
