### ISSUE TITLE
Sent Beacon 0

### ISSUE THREAD

**Issue by yogeshnichal** [helium/miner#1173]
From last 4-5 days my hotspot sent beacon but nearby hotspot not witnessed.
I thought every miner earn minimum 3-4 HNT per month but now this problem is going on.

Please help me.
Why this problem is going on?

![Screenshot_2021-11-08-05-57-26-35.png](https://user-images.githubusercontent.com/56922233/140668857-b11e982f-65ed-4cf1-b8ff-75ece7374697.png)
![Screenshot_2021-11-08-05-58-07-04.png](https://user-images.githubusercontent.com/56922233/140668868-8c63b30e-b213-469c-925e-ef963bc1eafe.png)
![Screenshot_2021-11-08-05-59-06-11.png](https://user-images.githubusercontent.com/56922233/140668889-98b80a7e-3774-45a7-b639-0cdd40cf38b6.png)

**Comment by Chinik12** [comment]
Same problem. From 17days no election for send beacon
[Activity](https://explorer.helium.com/hotspots/1121u7LTwLwLKDwCHzkVmj4uv8CxDxcPLwxUJzSsT1PkDk26Gjrv/activity)
![image](https://user-images.githubusercontent.com/93588105/143044676-65018a8d-a7c0-462e-97fe-93df09e437cc.png)
![image](https://user-images.githubusercontent.com/93588105/143044708-c8152bf2-77b0-418d-bc9e-3f7bab81a272.png)

**Comment by efe92** [comment]
i have same problem and nobody respond. good luck!
