### ISSUE TITLE
Please upgrade to `2021.08.21.0`

### ISSUE THREAD

**Issue by Eyk73** [helium/miner#1176]
Please upgrade to `2021.08.21.0`

_Originally posted by @abhay in https://github.com/helium/miner/issues/996#issuecomment-903197558_

Many people are reporting that their gateways are not automatically updating after firmware update 2021.08.16.1.

Any guidance you can give will be greatly appreciated and shared in the relevant channels.

Thanks

**Comment by bitlite** [comment]
In your Miner's home page, select RESET MINER (if you have this option) to clear the firmware and blockchain then it will download the new firmware and blockchain.  After 20-30 minutes you can also perform a Fast Sync (if you have this option) to speed up the blockchain gap.

**Comment by abhay** [comment]
> Any guidance you can give will be greatly appreciated and shared in the relevant channels.

Your manufacturer can provide the most information here. `2021.08.21.0` is now fairly old and your manufacturer should have upgraded you to at least `2021.11.02.0` if not `2021.11.04.2`
