### ISSUE TITLE
Beacons are not sent for many days!

### ISSUE THREAD

**Issue by mpiru** [helium/miner#1177]
In https://app.heliumstatus.io/ the gateway is offline, but in https://status.sensecapmx.cloud/ it is online and sometimes even  has earnings by witnesses.

The problem is that it doesn't send beacons for many days. Restart temporarily help, but when you have many routers deployed it is a problem to check them every day and to ask someone to restart.

One example here https://explorer.helium.com/hotspots/112vWM6gMKBWC9xcmdeHjzgR6usFH8TRKmYcYgo4sqmvbhWoSA5y/activity

![image](https://user-images.githubusercontent.com/3424797/140963768-1463c3d5-8d42-4e69-a3e6-d1792090ca3e.png)

**Comment by mpiru** [comment]
Here is an example:
https://explorer.helium.com/hotspots/112hbg4zxwj4FLqPdcakuuzi5xH7yjCNFPEuzMUKBTzwfV3tLUVg/activity Device is not relayed
![image](https://user-images.githubusercontent.com/3424797/141115368-751c8a82-0484-4fc3-87d5-177b16a18d21.png)

**Comment by b-effect** [comment]
i have same issue since 4 days..

**Comment by gusosborne** [comment]
Same here, seems to be spreading.

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
