### ISSUE TITLE
Potential typo? - blockchain:config is missing the ? before `poc_version`?

### ISSUE THREAD

**Issue by anthonyra** [helium/miner#1179]
https://github.com/helium/miner/blob/672ef444eca11a18b7703ef6ddc973786dec9318/src/miner_lora.erl#L169

**Comment by vihu** [comment]
Ah, good catch. It will still work without the question mark as well because it's defined in core as:

`-define(poc_version, poc_version).`

But we should fix it regardless.

**Comment by anthonyra** [comment]
Just didn't look like the rest, good to know that it would have still worked! I didn't know. I was trying to figure out how to do `miner eval` on one of my validators that blockchain:config to get the` poc_version` out of curiosity when I stumbled upon that..
