### ISSUE TITLE
Doesn't send beacons...

### ISSUE THREAD

**Issue by b-effect** [helium/miner#1193]
My connection and ports ok but miner can't send beacon for last 5 days.

![image](https://user-images.githubusercontent.com/94075078/141175563-b882f6c8-c50f-4f1d-b2e6-0d5f241e1f92.png)
![image](https://user-images.githubusercontent.com/94075078/141175589-c4fbb2ba-df09-48b1-9902-65585c232e11.png)
![image](https://user-images.githubusercontent.com/94075078/141175633-ce0daceb-6408-4d63-a0d3-40eb32e01c2d.png)

**Comment by b-effect** [comment]
1 week without earnings.

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
