### ISSUE TITLE
Large Mint Mongoose and Pet Stone Orca

### ISSUE THREAD

**Issue by Friscoplayrsf** [helium/miner#1196]
Can someone please open a ticket in regards to my miner? I havent changed anything but the rewards flatlined after the POV11 rollback. The status shows synced and online for both. I send a beacon and get no witnesses. In the helistats shows broken IP but nothing has changed except the Pov11 roll out and roll back. Prior to the POV 11 issues i was mining and getting rewards on both miners. Pet Stone Orca also has the same issues. This appears to be a widespread issue cause in Helium official Discord hotspot issues channel, a lot are having the same issues.

**Comment by Friscoplayrsf** [comment]
{
  "status": "Synced",
  "gap": "2",
  "miner_height": "1093870",
  "blockchain_height": "1093872",
  "epoch": "28599"
}

{
  "ota_version": "1.0.2.41",
  "region": "US915",
  "animal": "large-mint-mongoose",
  "pubkey": "11NPMUkF7CXqnaGhJMRj4i7t9oTy1nHZzFWK3PUhjm4TBkPqCFo",
  "miner": {
    "State": "running",
    "Status": "Up 6 hours",
    "Names": [
      "/miner"
    ],
    "Image": "quay.io/team-helium/miner:miner-arm64_2021.11.04.2_GA",
    "Created": 1636594883
  },
  "miner_height": "1093871",
  "blockchain_height": "1093872",
  "epoch": "28599",
  "ports_description": "only need to port forward 44158. For 22, only when need remote support",
  "ports": {
    "22": "closed/timeout",
    "44158": "open"
  },
  "p2p_status": [
    "+---------+-------+",
    "|  name   |result |",
    "+---------+-------+",
    "|connected|  yes  |",
    "|dialable |  yes  |",
    "|nat_type | none  |",
    "| height  |1093871|",
    "+---------+-------+",
    "",
    ""
  ],
  "public_ip": "67.180.152.31",
  "onboarding": [
    "",
    "********************",
    "General Manufacturing Info",
    "********************",
    "",
    "+-------------+---------------------------------------------------+",
    "|    name     |                      result                       |",
    "+-------------+---------------------------------------------------+",
    "|    batch    |                    bobcat_831                     |",
    "|  createdAt  |             2021-08-31T20:23:40.976Z              |",
    "|heliumSerial |                       null                        |",
    "|     id      |                      251581                       |",
    "|   macEth0   |                 e8:78:29:54:08:4b                 |",
    "|  macWlan0   |                 90:e8:68:30:d2:f9                 |",
    "|   makerId   |                         6                         |",
    "|onboardingKey|11NPMUkF7CXqnaGhJMRj4i7t9oTy1nHZzFWK3PUhjm4TBkPqCFo|",
    "|publicAddress|11NPMUkF7CXqnaGhJMRj4i7t9oTy1nHZzFWK3PUhjm4TBkPqCFo|",
    "|  rpiSerial  |                 222db1e80cfafb61                  |",
    "|  updatedAt  |             2021-09-17T15:25:51.718Z              |",
    "+-------------+---------------------------------------------------+",
    "",
    "",
    "********************",
    "Manufacturer Info",
    "********************",
    "",
    "+------------------+---------------------------------------------------+",
    "|       name       |                      result                       |",
    "+------------------+---------------------------------------------------+",
    "|     address      |14sKWeeYWQWrBSnLGq79uRQqZyw3Ldi7oBdxbF6a54QboTNBXDL|",
    "|    createdAt     |             2021-02-24T22:16:39.379Z              |",
    "|        id        |                         6                         |",
    "|locationNonceLimit|                         1                         |",
    "|       name       |                      Bobcat                       |",
    "|    updatedAt     |             2021-02-24T22:16:39.379Z              |",
    "+------------------+---------------------------------------------------+",
    "",
    ""
  ],
  "height": [
    "28599    1093871",
    ""
  ],
  "temp0": "32 °C",
  "temp1": "30 °C",
  "timestamp": "2021-11-11 07:46:21 +0000 UTC",
  "errors": ""
}
{"data":{"speculative_nonce":11,"lng":-122.27716941852725,"lat":37.956279688477906,"timestamp_added":"2021-09-17T15:29:03.000000Z","status":{"timestamp":"2021-11-03T09:51:12.753000Z","online":"online","listen_addrs":[],"height":1081671},"reward_scale":0.478240966796875,"payer":"14sKWeeYWQWrBSnLGq79uRQqZyw3Ldi7oBdxbF6a54QboTNBXDL","owner":"14EdjiixPG5hByr9YKukbC4uzZYZiR9VnFgozsxr54Pw2okEat6","nonce":11,"name":"large-mint-mongoose","mode":"full","location_hex":"8828308d0dfffff","location":"8c28308d0d5c7ff","last_poc_challenge":1093635,"last_change_block":1093635,"geocode":{"short_street":"Oliver Ct","short_state":"CA","short_country":"US","short_city":"El Sobrante","long_street":"Oliver Court","long_state":"California","long_country":"United States","long_city":"El Sobrante","city_id":"ZWwgc29icmFudGVjYWxpZm9ybmlhdW5pdGVkIHN0YXRlcw"},"gain":88,"elevation":4,"block_added":1014900,"block":1093873,"address":"11NPMUkF7CXqnaGhJMRj4i7t9oTy1nHZzFWK3PUhjm4TBkPqCFo"}}

+----------------------------------------------+---------------+----------+---------+---+----------+
|                   address                    |     name      |listen_add|connectio|nat|last_updat|
+----------------------------------------------+---------------+----------+---------+---+----------+
|/p2p/11NPMUkF7CXqnaGhJMRj4i7t9oTy1nHZzFWK3PUhj|large-mint-mong|    1     |    9    |non| 213.757s |
+----------------------------------------------+---------------+----------+---------+---+----------+

+----------------------------+
| listen_addrs (prioritized) |
+----------------------------+
|/ip4/67.180.152.31/tcp/44158|
+----------------------------+

+------------------+---------------------+-----------------------------------------+----------------+
|      local       |       remote        |                   p2p                   |      name      |
+------------------+---------------------+-----------------------------------------+----------------+
|/ip4/172.17.0.2/tc|/ip4/146.115.168.95/t|/p2p/112TqfrrgNgtDkhW5cEbJUSojJK8KeE8pNYh|decent-daisy-osp|
|/ip4/172.17.0.2/tc|/ip4/77.103.69.216/tc|/p2p/112az1j18pf9pbAiSYHWhd8Mf8DX7yBJmS33|rich-fossilized-|
|/ip4/172.17.0.2/tc|/ip4/151.73.29.218/tc|/p2p/113UZY6zzCYTe2EDX7AxikgnNFc5PNzcHigs|calm-fuchsia-cap|
|/ip4/172.17.0.2/tc|/ip4/184.155.237.57/t|/p2p/117LGJoR3bQkEVBvjuCmgfnDtnQnXWJKGhnq|urban-hickory-oy|
|/ip4/172.17.0.2/tc|/ip4/13.237.200.108/t|/p2p/11REvag6vFX8WHRKcdNXpXtMTK1Q2UQeQCLF|rich-sky-seahors|
|/ip4/172.17.0.2/tc|/ip4/54.251.69.171/tc|/p2p/11UCbsgywnxzfXdjDxsHcUqwfPgjt9nSt9m3|ancient-beige-ha|
|/ip4/172.17.0.2/tc|/ip4/73.72.179.224/tc|/p2p/11bRNFM9uHxVNQFL2hbbEaDs1waPoPs8VTv7|scrawny-fleece-o|
|/ip4/172.17.0.2/tc|/ip4/208.73.204.116/t|/p2p/11hzvp67hrF8ya1VeDPSiuTPnBZPREFynvWT|jumpy-khaki-porp|
|/ip4/172.17.0.2/tc|/ip4/216.232.181.10/t|/p2p/11zXmwKtJMtXvcnHdxd1JyqBpaYMvrpHNTv7|bent-cyan-baboon|
+------------------+---------------------+-----------------------------------------+----------------+

**Comment by Friscoplayrsf** [comment]
Miner can’t witness failing during process

**Comment by Friscoplayrsf** [comment]
blob:https://explorer-v1.helium.com/5ff3ee7e-56c8-48b0-bd5c-493f711281d7

**Comment by bitlite** [comment]
log into your local IP for Bobcat and click on RESET miner.  Reset your miner and wait.  It should resolve your issue.  Wait until the Blockchain is back up though.   Currently offline.

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
