### ISSUE TITLE
why is timestamp stuck and cannot send beacon?

### ISSUE THREAD

**Issue by gitemre** [helium/miner#1198]
https://explorer.helium.com/hotspots/112ExKbJfDuchThrX9XyGNiWmfo1U7msYWpam126SVGMmSXMqwJE/activity

https://api.helium.io/v1/hotspots/name/innocent-mercurial-raccoon

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
