### ISSUE TITLE
Witness Crisis 

### ISSUE THREAD

**Issue by FiloFilo1984** [helium/miner#1207]
No more witness, impossible to continue with so little income, since 27.10.2021 with 16 witness seen no income...
It's been more than two weeks, please remedy the problem quickly 

![Witnesscrisis](https://user-images.githubusercontent.com/94350201/141739609-6e6750fc-16a7-44cb-b581-386cc4acea69.JPG)

SensCap M1

**Comment by bitlite** [comment]
Contact Sensecap for assistance... it is most probably hardware related.  check your antenna cables.

**Comment by ProTechEx** [comment]
> No more witness, impossible to continue with so little income, since 27.10.2021 with 16 witness seen no income... It's been more than two weeks, please remedy the problem quickly
> 
> ![Witnesscrisis](https://user-images.githubusercontent.com/94350201/141739609-6e6750fc-16a7-44cb-b581-386cc4acea69.JPG)
> 
> SensCap M1

None of this has anything to do with the helium software. It's always up to your hardware or antenna :)

Like THOUSANDS OF OTHERS, may  you have the problem that your hardware get a issue suddenly with no reason OR your antenna has been walking from it's place. You have to be carefull, the helium network is full of miracles, unusual things happen for many THOUSANDS HOTPOT OWNERS ALWAYS AT THE SAME TIME :)

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
