### ISSUE TITLE
DNS response size too large

### ISSUE THREAD

**Issue by radrob1** [helium/miner#1224]
The current response size of seed.helium.io is 555 bytes. This appears to be causing some DNS resolution issues with miners with varying DNS servers that do not support EDNS as the maximum response size is 512 bytes by default. 

One option to resolve this issue may be to enable the `usevc` option in the inet config to allow for a tcp DNS request instead, but it is unknown what side effects it may have. 

Another option may be to decrease the size of the DNS record for seed.helium.io to make sure it stays under the 512 byte limit.

**Comment by Vagabond** [comment]
Thank you, we will fix it.

**Comment by madninja** [comment]
This was resolved by limiting the returned DNS  list to under 512 bytes and adding the extra seeds to the sys.config list
