### ISSUE TITLE
How to start validator?

### ISSUE THREAD

**Issue by mlg1** [helium/miner#1240]
Maybe my question is stupid, but how do I run a validator? How do I make a stake of 10,000 HNT, given that this is about 450,000 dollars?

**Comment by shawaj** [comment]
Either use a service like https://stakejoy.com/or start your own validator using these instructions https://docs.helium.com/mine-hnt/validators/mainnet/deployment-guide/

You need to have 10k HNT available to stake though

**Comment by mlg1** [comment]
Dudes, you didn't understand me! I can install and configure a validator. The question is where to get 10,000 HNT? What normal person would own 10,000 HNT, just like that?
