### ISSUE TITLE
Bobcat No Beacon and lack of activity problem 

### ISSUE THREAD

**Issue by licentia88** [helium/miner#1247]
My miners have not sent a beacon since nov 6 and has only 1-2 witness or challenge a day.. 

looking for a fix from helium as son as possible and a compensation reward as this issue is not a client mess..

**Comment by Mikael1993** [comment]
I have a problem since October 29
Many have this problem #1245

**Comment by ElYoM** [comment]
Yes, we are many in the same boat but it's not just a problem with Bobcat. It's more deeper than that. See here for example : https://github.com/helium/miner/issues/1205

**Comment by Chinik12** [comment]
i'm SENSECAP and from 17days no election for send beacon, why? it's random, but in 17 days a lot of block and election.
[Activity](https://explorer.helium.com/hotspots/1121u7LTwLwLKDwCHzkVmj4uv8CxDxcPLwxUJzSsT1PkDk26Gjrv/activity)
![image](https://user-images.githubusercontent.com/93588105/143044676-65018a8d-a7c0-462e-97fe-93df09e437cc.png)
![image](https://user-images.githubusercontent.com/93588105/143044708-c8152bf2-77b0-418d-bc9e-3f7bab81a272.png)

**Comment by LinusFly74** [comment]
news?

**Comment by C4ngr3j0** [comment]
> My miners have not sent a beacon since nov 6 and has only 1-2 witness or challenge a day..
> 
> looking for a fix from helium as son as possible and a compensation reward as this issue is not a client mess..

Did you fix it? I'm having the same problem. Check out Expert Carmine Salamander

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
