### ISSUE TITLE
API Reported Listen Address

### ISSUE THREAD

**Issue by DrNopt** [helium/miner#1252]
My activity has dropped to zero. I've noticed something is wrong in my Bobcat like others i've seen in here. ( their threat is closed )

![image](https://user-images.githubusercontent.com/12167061/143031415-08d93261-de46-478f-a877-5c20891108b2.png)

My API Reported Listen Address is wrong and closed. This should match the Observed Listen Addresses.
I'm not witnessing anything like this.
Some feedback on this, please  ?

Thank you.

**Comment by bilalhp** [comment]
The address which API reports is not important and is not affecting your earnings. Eventually, it will be updated once your gossip data reaches to the API nodes. But I am really wondering what caused this weird port 1762 to show up here.

**Comment by DrNopt** [comment]
Can someone explain to me how is this possible ?
How can this guy with the same hotspot as me, 400 mts away,  with a lot less witnesses than i gets a lot more beacons than me ??
![image](https://user-images.githubusercontent.com/12167061/143854627-7dc7e0af-cedb-4802-8316-286753d9ff89.png)
![image](https://user-images.githubusercontent.com/12167061/143854928-7389ea60-7517-4bdc-8f08-dd502fb3381f.png)

This just bogles my mind. 
If a lot more people see me (witnesses) , than in my logic i should witness more than him, right ?

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
