### ISSUE TITLE
what happened? bobcat lost all.

### ISSUE THREAD

**Issue by LinusFly74** [helium/miner#1253]
serious problems with bobcat.  Loss of witness.  I have believed in this project since April 2021 and now I am completely disappointed.My bobcat has lost all witnesses for 10 days now and I am.  with zero rewards.  I have everything right: 44158 open, synced, 8dbi rak antenna, nat none, very stable connection.  I live in the hills but up to 3 weeks ago I had 3 witnesses. now it's all over.  It is a scandal that no one gives us concrete answers ... have we invested our money in vain?

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
