### ISSUE TITLE
No Chalanged Beaconer (transmiter) after Challenge created 

### ISSUE THREAD

**Issue by BorisMolch** [helium/miner#1257]
animal name: Fierce Wool Baboon (happens to other hotspots as well, as reported by community members)
 bobcat 300

an odd behaviour keep repeating itself (not consistent)
a challenge is created, but no chalangee (transmiter) is selected > no reward is being issued.
Not relayed, ports are open.
Is this normal ? if so how does this happen?
how can one monitor the process of transmiter selection?

**Comment by jack9418** [comment]
terrible

**Comment by BorisMolch** [comment]
> terrible

?

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
