### ISSUE TITLE
Nebra Indoor Stuck on 9/27 firmware + block 1046852

### ISSUE THREAD

**Issue by chrisdaid** [helium/miner#1258]
Okay, I bought this Nebra second hand from a reputable seller on eBay since he accidentally bought two. Upon setting up and syncing, he realized he could only have one at his place, so he listed it. Last time this was synced was October 5. I received the miner on November 17, so it's been about a week. For the seller to transfer ownership of the miner to me, the miner has to be synced, and it isn't syncing. For the first 2-3 days I didn't know what I was doing, and didn't know diagnostics existed, so I'm not sure if it even synced then. It has been connected with ethernet for the first 4 days, then I realized nothing was happening, so I checked if I portforwarded correctly, and I did. Everything was saying it was fine. HeliumStatus gave me the green message "you're a pro" and nebra dashboard said it was connected to the helium server and everything was fine. Helium app said inbound and outbound was green. I am still stuck on block 1046852, and the percent synced keeps decreasing. In last 2 days it went from 94.6% to 94.13% now. (I updated dashboard screen shot and it is now 94.11%). 

Weird things I noticed that might help: 
- Nebra dashboard stats are definitely not correct (the stats have not changed at all. Same usage across the board at all times, and someone told me 8% cpu utilization is very low, so I feel like it isn't doing anything or the stats are just wrong.)
<img width="953" alt="Screen Shot 2021-11-25 at 3 56 34 PM" src="https://user-images.githubusercontent.com/70724105/143499180-9cdc42bf-79a2-436d-a2ec-5be0ee03e2c6.png">
- The private dashboard (enter your ip as the url) worked for me but showed everything was ok. It clearly isn't if it isn't syncing. Here is a picture of what it says: 
- <img width="1033" alt="Screen Shot 2021-11-25 at 3 52 02 PM" src="https://user-images.githubusercontent.com/70724105/143498989-84b7c1ec-2127-4fe5-8128-effcff78325e.png">
- I am stuck on firmware version 9/27 when 11/21 is out and everyone has that. I have plugged it into ethernet and left it overnight and throughout the day without touching it, and no update.
- Helium Status Screenshot:
<img width="841" alt="Screen Shot 2021-11-25 at 11 43 34 AM" src="https://user-images.githubusercontent.com/70724105/143478395-f0ecd7ee-c6e6-4c54-bf5e-16a66433484c.png">
Transmit scale is 0.25 because I assume it's from the fact that the location is still registered at the seller's house.
What I have done already:
- portforward to TCP 44158
- tighten antenna because it's a common issue on Nebra batch 1
- Reseat compute module
- Try wireless 
- reboot software in nebra dashboard and reboot miner

**Comment by wolasss** [comment]
https://github.com/NebraLtd/helium-miner-software 

I think this is the right repository to open issue of this kind

**Comment by chrisdaid** [comment]
> https://github.com/NebraLtd/helium-miner-software
> 
> I think this is the right repository to open issue of this kind

Unfortunately that isn't. This is the only place that won't close the issue tickets. I already emailed Nebra support but they haven't responded in 4 days so far.

**Comment by shawaj** [comment]
Please email support@nebra.com for tech support

**Comment by chrisdaid** [comment]
> Please email [support@nebra.com](mailto:support@nebra.com) for tech support

Been almost 2 weeks.. Nothing from Nebra support. Gave me a ticket number and I'm stuck here waiting

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
