### ISSUE TITLE
Sudden Drop in Rewards

### ISSUE THREAD

**Issue by techygeekshome** [helium/miner#1261]
My miner was earning quite nicely at around 1HNT a day, but then since the doomed update came out it stopped working completely. I've got it going again, but for the last week its only getting 0.2HNT a day if I'm lucky, sometimes not even that much. Whats going on? Might as well sell it on ebay at this rate.

**Comment by amirhaleem** [comment]
please see: https://discord.com/channels/404106811252408320/739678096487088229/911050154558242846
