### ISSUE TITLE
2021.11.30.1 update fixed some broke others

### ISSUE THREAD

**Issue by Chris-S44** [helium/miner#1272]
After this update my 1 sensecap that was on LTE has started witnessing and beaconing but 2 of my others that are on fibre with static public ip addresses have totally stopped. All they are doing now is challenging beaconers.
These have been my 2 best hotspots. Nothing changed except the firmware update.

**Comment by jack9418** [comment]
me too

**Comment by Chris-S44** [comment]
Another one of mine has flatlined today. That is 3 out 4 that have stopped witnessing or beaconing.
Changing the Ip address helped once but not anymore.

**Comment by Chris-S44** [comment]
@amirhaleem let me know if I can provide you with any further information.
Is this still a seed node problem?

**Comment by Allstarsone** [comment]
Same here rarely sending a beacon did tried everything changed IP address reboot miner nothing changed 

Shambolic Fuchsia Bird

**Comment by gdanskgrom** [comment]
Goldspot miner (Tiny Opaque Mule) stuck on block 1,121,718  - rebooted numerous times, reimaged SD
Rak v2.0 (Steep Glass Okapi) was fully synced and dropped back

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
