### ISSUE TITLE
zero-witness :(

### ISSUE THREAD

**Issue by yogeshnichal** [helium/miner#1280]
Before yesterday in last 15 days only 1 sent beacon.
Now
Sent Beacon multiple but 0 witnessing.
Please help me what's the problem??
![Shot 0181](https://user-images.githubusercontent.com/56922233/145282608-e4285bce-e904-4d1f-856a-806d610db4ce.png)
![Shot 0182](https://user-images.githubusercontent.com/56922233/145282614-2caf87a5-077b-486a-85d7-f9b29b957b6b.png)
![Shot 0183](https://user-images.githubusercontent.com/56922233/145282620-051644a2-72ca-40b1-ac1c-a60390b97518.png)
![Shot 0184](https://user-images.githubusercontent.com/56922233/145282625-e0e19ef5-4495-43aa-9b74-cf58f652291d.png)

https://explorer.helium.com/accounts/13wvymwxsxw6nDbRa5uE5wm76cyDgM1KNKtJVmnXbzd1tmRbQuA

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
