### ISSUE TITLE
miner-arm64_2021.12.06.0_GA Nothing has changed

### ISSUE THREAD

**Issue by bgdn021** [helium/miner#1283]
Still not witnessing anyone just sending beacons and creating challenges. I've checked my neighbors, almost everyone are updated to the latest version. Talked to some people on discord, some say things are better others say nothing has changed so as for me.

https://explorer.helium.com/hotspots/112okzK1NiDyxpyLoBZadCCsEjjveRkXJavLCQcBjHsxwH8BatLk

https://app.heliumstatus.io/hotspots/112okzK1NiDyxpyLoBZadCCsEjjveRkXJavLCQcBjHsxwH8BatLk

Maybe someone is willing to take a look at these logs.

[error log.txt](https://github.com/helium/miner/files/7677597/error.log.txt)
[miner log.txt](https://github.com/helium/miner/files/7677598/miner.log.txt)
[witness log.txt](https://github.com/helium/miner/files/7677599/witness.log.txt)

**Comment by ykuntsevych** [comment]
same case

**Comment by bgdn021** [comment]
New logs. 
[error log.txt](https://github.com/helium/miner/files/7684746/error.log.txt)
[witness log.txt](https://github.com/helium/miner/files/7684747/witness.log.txt)

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
