### ISSUE TITLE
Hotspot not beaconing (only creating challenges)

### ISSUE THREAD

**Issue by MPWrbk** [helium/miner#1286]
Network is properly configured, NAT is none, port 44158 is open, it synchronizes normally but doesn't do anything other than creating challenges 2 days. I've just set this hotspot up a week ago but due to some cable interferences it was restarting all the time. So I turned it off and replaced cable with FTP (protected) so now it doesn't restart but it only create challenges.

https://explorer.helium.com/hotspots/11bdAzdSYKgHpg8HGmh8VnBEgGFF5749GvDQK7wNYsJc6cV1GVX/activity

Please help

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
