### ISSUE TITLE
MNTD Blackspot miner flatlined after 12/9 update. 

### ISSUE THREAD

**Issue by bkapps** [helium/miner#1291]
After the 12/9 update my MNTD blackspot miner went out of sync. After around 8 hours it fully synced. Since it was fully synced it has been flatlined with no beacons, witnessing events, challenges, data transfers, etc. This has been the case for 16 hours now.

**Comment by OWNhanaJ** [comment]
Also having same issue everything says my miner is working and synced but flatlined since the update nothing for 24 hours now. It dropped off the network a few times and the app says it needs attention but the miner itself says it has no issues rebooting changed nothing!

**Comment by jmarcelino** [comment]
For RAK/MNTD support please email support@helium.com or contact us on https://bit.ly/rakminerhelp
This repo is not miner support.

**Comment by bkapps** [comment]
Sorry was told in the Rak discord to post the issue here. I guess that was bad advice.
