### ISSUE TITLE
failed to dial proxy server 

### ISSUE THREAD

**Issue by ykuntsevych** [helium/miner#1293]
Getting @libp2p_transport_proxy:connect_to:69 failed to dial proxy server   (Relayed? No, name: Faint Denim Parrot ) 

Getting ERRORS: failed to dial proxy server  and failed to send witness
Updating to last Miner version every time.  
Dashboard Version: v0.2.8  Miner Version: miner-arm64_2021.12.09.0_GA

[miner_log.txt](https://github.com/helium/miner/files/7695836/miner_log.txt)
[witness_log.txt](https://github.com/helium/miner/files/7695838/witness_log.txt)
[error_log.txt](https://github.com/helium/miner/files/7695839/error_log.txt)

**Comment by bgdn021** [comment]
Pisces miner, as mine 🤔

**Comment by RaY3nPupaY3n** [comment]
I have the same Issue. Tryed to Install the brand new Miner, he is offline for 5 Days now. No Idea.

**Comment by ykuntsevych** [comment]
> I had the same Issue. You need to open the Port 44158 first and then disable the upnp. After all check with the Forwarding-Test ( https://www.yougetsignal.com/tools/open-ports/ ) if the port is open. Do this Test outside your Network ( with a Mobile-Phone )

Thanks!!
Already done
Ports forwarded, upnp - off. Errors keep appearing

name: Faint Denim Parrot

this drives me crazy. Two neighbors in same hex are getting 0.5-1 NHT / day while I am getting errors. 

My roof is higher )) 


![7F7945C3-DE85-4E8A-BEA6-796AAAA3435C](https://user-images.githubusercontent.com/35671654/145794065-f8bb169a-35ff-4a95-a456-e36deea8c846.png)
![8C75EBDD-9B56-48EB-83E6-41A821018D61](https://user-images.githubusercontent.com/35671654/145794076-10495198-5bfa-4d00-b130-13083f3d64cb.png)

**Comment by RaY3nPupaY3n** [comment]
Router for 30 sec OFF, Miner 30 sec off >> then "CLEAN BLOCKCHAIN DATA" - Are you connected through WLAN? often it´s the problem, need to connect directly to LAN. At Hotspotty you can do Status-Check. Helium-Explorer is quite slow. There you can see the Changes somethimes few Hours later. So always check through Hotspotty.

**Comment by ykuntsevych** [comment]
> Router for 30 sec OFF, Miner 30 sec off >> then "CLEAN BLOCKCHAIN DATA" - Are you connected through WLAN? often it´s the problem, need to connect directly to LAN. At Hotspotty you can do Status-Check. Helium-Explorer is quite slow. There you can see the Changes somethimes few Hours later. So always check through Hotspotty.



> Router for 30 sec OFF, Miner 30 sec off >> then "CLEAN BLOCKCHAIN DATA" - Are you connected through WLAN? often it´s the problem, need to connect directly to LAN. At Hotspotty you can do Status-Check. Helium-Explorer is quite slow. There you can see the Changes somethimes few Hours later. So always check through Hotspotty.

Thanks. Does clean blockchain data changes something, did it work? It took 4-5 days just to sync.
I am not using wifi, do you mean router?it’s mesh but through cable

**Comment by ykuntsevych** [comment]
Moved to 2021.12.14 Reports from Hotspot Owners #1300

**Comment by MarilynBlack** [comment]
Hello, Did you overcome the proxy error? I am facing the same problem. Please help me.

**Comment by RaY3nPupaY3n** [comment]
Yes it worked.
Maybe you should check the router-firewall.
