### ISSUE TITLE
Lte Issue

### ISSUE THREAD

**Issue by matissj** [helium/miner#1295]
Miner on lte network witnesses only 5-6 times a day

Two miners located on rooftops in perfectly populated area witnesses only 5-6 times a day, in the mean time other miners really close by witnesses twice an hour. 

Noisy Mauve Tortoise
Sunny Glass Crocodile

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
