### ISSUE TITLE
AS923-3 frequencies marked as incorrect_frequency after PoC_v11 upgrade.

### ISSUE THREAD

**Issue by rvjaywaks** [helium/miner#1298]
After the POCv11, hotspots in the Philippines (AS923-3) suddenly got ALL invalid beacons and witnesses. There was no change in the frequency when the upgrade to POCv11 happened. It was still the the same AS923-3 uplink frequencies but those are now incorrect_frequency. Did we missed something in the config file or something related to that?

https://explorer.helium.com/txns/HnsJUI1mtfFbs-A-wAAIxPoWK6slCuybLhXOUmuz93A

Here's the screenshot of the frequency and the invalid witnessing caused by incorrect_frequency.

I hope the helium team can have a look and make the fix soon.

**Comment by jdgemm** [comment]
Thanks for raising the issue, but it's the incorrect repository. Please raise your issue here: https://github.com/gradoj/hplans/issues
