### ISSUE TITLE
.

### ISSUE THREAD

**Issue by tareqaldaher** [helium/miner#1321]
.

**Comment by SAVAMforWIN** [comment]
same

**Comment by vanjulio** [comment]
Definitely something wrong again.

**Comment by carzygod** [comment]
![image](https://user-images.githubusercontent.com/32446081/148008027-9480c34a-4b27-494a-a6e1-0b5d0f2d6f9f.png)
seems like the last beacon it send is 2months  ago... and witnessed by other(which means the lora is sending the message with no problem...)
And it go slient for 2 months

**Comment by J0SHINAT0R** [comment]
perhaps the issue is similar to this: https://github.com/helium/miner/issues/1305#issue-1083975305
