### ISSUE TITLE
Witness invalid 

### ISSUE THREAD

**Issue by SAVAMforWIN** [helium/miner#1322]
hi guys, I have recently installed a piscies P100, in the app I have declared the correct antenna values, despite this I receive many invalid witnesses (RSSI to high), how can I solve? it's frustrating because i didn't cheat and i'm 100% in good standing, it seems pocv11 hurts even good people

**Comment by inigoflores** [comment]
This an issue that affects Pisces P100 miners. The error you get is `witness_rssi_too_high` when witnessing beacons.

You have to login via SSH into your miner and change the two `rssi_offset` parameters from -215.4 to -230.4. 

`sudo nano /home/pi/hnt/paket/paket/packet_forwarder/global_conf.json`

Then you have to restart the packet forwarder or just reboot.

**Comment by SAVAMforWIN** [comment]
thank you very much for the information, can you tell me exactly the commands to do? I'm not familiar with hotspots

**Comment by inigoflores** [comment]
You have to log in via SSH to your miner using a SSH client (OpenSSH, Putty, etc.) with user admin. Once in, you have to edit `global_conf.json`, change the mentioned values, save and reboot.

    sudo nano /home/pi/hnt/paket/paket/packet_forwarder/global_conf.json
    sudo reboot

Please understand that this is out of the scope of this repo. In the [Pisces Discord](https://discord.gg/cBwEUxHcn4) you should find more help.

**Comment by SAVAMforWIN** [comment]
I rebooted from the hotspot web page, and now it doesn't come back online, do I have to turn it off and on again?

**Comment by carzygod** [comment]
> 

Yes . i do think you will need to take it a repower

**Comment by meowshka** [comment]
@SAVAMforWIN I am sorry it took a while to get back to you. I assume this issue has been resolved. However if you're still experiencing any problems, please contact the manufacturer of your hotspot directly. Here's their discord: https://discord.gg/cBwEUxHcn4
