### ISSUE TITLE
Bobcat try access on port 22. 

### ISSUE THREAD

**Issue by yogi0988** [helium/miner#1336]
Hi, 

I have a bobcat... when i analyse the firewall log traffic network. I observe that he constantly try acces my routeur on the port 22 by my lan. You can see the zip for packet capture.   When i block the traffic, my miner do not fonctionning properly. When i pass the traffic my miner is ok, but i have a multiple other log on my system. (see [5 january - acces port 22.pnj)

I want to know the reason. It is possible that the problem is misconfiguration on the miner? It is malicious ? 

Am I in the right place for my question?

Lan IP: 192.168.1.101
Wan IP: see port22.zip

[port22.zip](https://github.com/helium/miner/files/7817487/port22.zip)
![5 january - acces port 22](https://user-images.githubusercontent.com/95514605/148282509-b05d5c01-3040-47b3-8112-62489d7ae4f4.png)

**Comment by Vagabond** [comment]
This is a bobcat issue, please report to them.

**Comment by yogi0988** [comment]
Thank you. I will writing to bobcat support.
