### ISSUE TITLE
When we can expect the new update which will resolve the regions issue?

### ISSUE THREAD

**Issue by tatulyan** [helium/miner#1342]
we don’t issue HNT, and there’s no way for the network to really compensate for these types of issues. 

next update will hopefully be that the regions are updated and working again. thanks for everyone’s feedback.

_Originally posted by @amirhaleem in https://github.com/helium/miner/issues/1305#issuecomment-1003053723_

**Comment by J0SHINAT0R** [comment]
I have been trying to look for an update on this aswell... last Estimation was Early January... we are slowly getting closer to late Janurary haha 

Does anyone have a more accurate estimation?  maybe it is scheduled by now?  or if more issues have surfaced, we would still appreciate an update on what the current situation is.  

Thanks in advance

**Comment by tatulyan** [comment]
@abhay could you please update us w.r.t.  this issue ? The original issue is  #1305 , After December 12th update some regions are not able to get rewards.

**Comment by prnhnt** [comment]
@here **Chain Variable: State Channel Grace Period Increase**

The core developers are preparing the following chain variable to allow State Channel closers a longer grace period to close their channels before Hotspots.

- sc_grace_blocks: 5

The State Channel Grace Period (number of blocks a state channel operator can be late in closing their state channels) was reduced to `1` to help mitigate the State Channel related outage in November.

When the closer is late (misses the grace period), Hotspots will try to close the State Channel and claim their rewards but they only have partial State Channel summary information. Increasing the Grace Period will address this issue and also reduce the inconsistency some are seeing with on-chain reporting of Data Transfer.

_Side note: For those who are also interested about LoRaWAN regions / PoCv11 related variables, we will be updating them next week now that Validators have mostly upgraded to 1.6.2 to include some crucial performance updates. This variable today should give us a good sense of how those performance updates are working. The core developers and community members will continue to monitor the chain and Validator / Hotspot performance after today's variable is released_

**Plan**

We plan on releasing this chain variable a little after 00:00 UTC / 4:00pm PT (after the next Consensus Group is elected and starts producing blocks) and will update this post with an Audit link when the Consensus Group accepts it.

Audit: https://github.com/helium/miner/blob/master/audit/var-110.md
