### ISSUE TITLE
Big reward drop. Seems miner_onion_handle related

### ISSUE THREAD

**Issue by marsxiang** [helium/miner#1350]
Earnings have fallen sharply recently.

![image](https://user-images.githubusercontent.com/6489149/148898511-7a9639ed-1353-4fdd-a4cd-f9adaf97828d.png)

To solve this problem, we analyzed the log.
It is found that when the challengee is connected with the challenger, no challenge information is sent.

The normal process is as follows：

**1,challenger log:**

![image](https://user-images.githubusercontent.com/6489149/148899519-4d09d97d-b116-422e-bb42-cf1546b0eb93.png)

**2,challengee log**

![image](https://user-images.githubusercontent.com/6489149/148899716-11cb2d13-76b7-4ef3-a430-708f9bf1d159.png)

**Log of hotspots without revenue ：**

![image](https://user-images.githubusercontent.com/6489149/148900454-96a7d457-4a03-43bb-9adb-21e9dc81cf6f.png)

Therefore, we read the source code and found some interesting things. there are some other findings.

Using open source miner_poc_handle code, only 1.7k after compilation, as follows：

![image](https://user-images.githubusercontent.com/6489149/148901531-717fea2e-9860-4495-aebf-ea3640911240.png)

But the official image, this file has 13.8M!as follows：

![image](https://user-images.githubusercontent.com/6489149/148901711-113dc63f-7755-42ab-9cfa-6b0da2d91421.png)

What operations have been done in this file, resulting in reduced hotspots revenue? We don't know.
Is this a centralized project?

@Vagabond ,@macpie .

**Comment by serbyxp** [comment]
I can confirm this.
there is also a block chain sync issue. I have been syncing for 5 days... yet for 5 days I have been at the latest block height.
logs attached below.
[error_log_4.txt](https://github.com/helium/miner/files/7848387/error_log_4.txt)
[error_log_3.txt](https://github.com/helium/miner/files/7848388/error_log_3.txt)
[error_log_2.txt](https://github.com/helium/miner/files/7848389/error_log_2.txt)
[error_log_1-11.txt](https://github.com/helium/miner/files/7848390/error_log_1-11.txt)
[error_log_1.txt](https://github.com/helium/miner/files/7848391/error_log_1.txt)
[error_log_0.txt](https://github.com/helium/miner/files/7848392/error_log_0.txt)
[crash_log_4.txt](https://github.com/helium/miner/files/7848394/crash_log_4.txt)
[crash_log_3.txt](https://github.com/helium/miner/files/7848395/crash_log_3.txt)
[crash_log_2.txt](https://github.com/helium/miner/files/7848396/crash_log_2.txt)
[crash_log_1-11.txt](https://github.com/helium/miner/files/7848397/crash_log_1-11.txt)
[crash_log_1.txt](https://github.com/helium/miner/files/7848398/crash_log_1.txt)
[crash_log_0.txt](https://github.com/helium/miner/files/7848399/crash_log_0.txt)
[console_log_4.txt](https://github.com/helium/miner/files/7848400/console_log_4.txt)
[console_log_3.txt](https://github.com/helium/miner/files/7848403/console_log_3.txt)
[console_log_2.txt](https://github.com/helium/miner/files/7848404/console_log_2.txt)
[console_log_1-11.txt](https://github.com/helium/miner/files/7848405/console_log_1-11.txt)
[console_log_1.txt](https://github.com/helium/miner/files/7848406/console_log_1.txt)
[console_log_0.txt](https://github.com/helium/miner/files/7848407/console_log_0.txt)

**Comment by amirhaleem** [comment]
https://discord.com/channels/404106811252408320/730418759298318346/930675333345206352
