### ISSUE TITLE
Forcing miners to use 2.4 GHz wifi only (raspberry pi models atleast)

### ISSUE THREAD

**Issue by bruvv** [helium/miner#1355]
I have been struggling with sensecap and MNTD miners (both raspberry pi v4 based) at my home. After A LOT of debugging (and that is hard when you cannot access the miner in anyway to know what is going on :( ) after moving it to a friends house I found out that it is switching between 5ghz and 2.4 ghz every few minutes:
![afbeelding](https://user-images.githubusercontent.com/3063928/149098596-69ae4139-a932-4141-83b2-db83a42cd625.png)

Yes I know what can be done to overcome this:
- Switch to 2 different SSID names. No option because it is locked by the ISP
- Disable the 5GHZ all together Not an option because I want to use the 5ghz
- Buy a new access point and hopefully have no double nat. No option because I do not like to have extra access points
- Using ETH, no option because I cannot drill in my house since it is a temporary rental house.

In my opinion 5GHz will not improve anything for the miner. Since the miners that I know do not have an external antenna having a very stable connection with internet is very important for the whole blockchain. So locking it to 2.4 GHz will be very smart thing to do.

**My solution:**
- Lock the miners to only use 2.4 GHz.
OR
- Add an option to have the user decided to add 5GHz but leave it default locked to 2.4GHz.

Using a raspberry pi doing this will do just that:
Modify `/mnt/boot/system-connections` to: `band=bg`

**Comment by vanjulio** [comment]
I think the better solution is to not include Wifi with the miners completely.  I wasted many hours doing a similar troubleshooting as you outlined and also had an accident that cost me a power cable and a chain of errors on my part.  The Wifi allegedly costs more CPU than the ETH connection.  Get rid of it.

**Comment by serbyxp** [comment]
you could get another device in the middle of them... how that will effect the NAT for p2p ... I dont know but... I have Nebra.. miner they just use those little thumb size usb dongles... you could just swap the dongle out for one that is only 2.4 ghz with no 5 ghz radio... that might work IF sense cap uses the same type of USB dongle...
![IMG_3326](https://user-images.githubusercontent.com/73319313/149191357-41c5e847-665a-4fd7-b368-bb33717cf512.jpg)

**Comment by bruvv** [comment]
Good option but again helium is for noobs and people that just buy these things and do not look back at it. So we should make it noob proof as much as possible. Explaining to everyone who want to use wifi to extra wifi stuff to it is not really a good solution in my eyes.

If you would do something like you suggest, how will the MNTD or sensecap (raspberry pi v4 based) know what hardware to use? Us the internal WIFI or the external dongle? no option to select the wifi card as far as I know.

**Comment by serbyxp** [comment]
well it seems like the ISP is your issue.. that you cant name the diffrent radios... not so much the hotspot itself..

**Comment by bruvv** [comment]
I am talking about the miner/hotspot (raspberry pi based) how is THAT going to know what radio to use? (wlan0 vs WLAN1)

**Comment by serbyxp** [comment]
well you could force it to do 2.4 ghz Id look that up somewhere online or youtube on one of them maker channels... there is tons of info on the subject... I have never looked into it myself but I would look to force the 2.4 ghz radio and shut down the 5ghz radio but that will open up a can of worms. Nebra uses an OS called balena... which is a one way street... they got access to your settings but you don't got access to those settings... as you can see I went down that road... I would try and middle man it some how if you cant get your ISP to give different names for the different radios... on your router modem

**Comment by serbyxp** [comment]
I had an issue with my concentrator and the replacement didnt work with the pinout or PCB design so I had to jumper wire some things around... that was my issue... but again, the USB dongle if its a specific driver that's embedded in the sense cap firmware... aka if you swap it out it wont " plug and play" or update the firmware to the new USB dongle... then it wont work either way.. you need to put something in the middle between the router and the device that you have control of the radios... Like you said... that will get fishy with the NAT but... if you have access to that bridge device... you can then open the ports that are necessary and it should work... SHOULD ... but this p2p thing is finicky

**Comment by serbyxp** [comment]
Like I have an OLD router like super old but I flashed it with the DD-wrt and I have my IOT devices that only have 2.4 ghz radios on them connected to it like this... I get no NAT issues... ( I have other issues ) with the miner pluged into main router over ethernet..But my isp routermodem is in my room and I when im testing debuging stuff I plug it to this.. but either way the nat says none when on my debug work station...
![img_](https://user-images.githubusercontent.com/73319313/149198424-3db7c88f-3ce7-4fdc-92a4-73b2b8f1989a.png)
![IMG_3327](https://user-images.githubusercontent.com/73319313/149198431-0297e735-ccb3-425e-9f56-6fedea1609d1.jpg)

**Comment by serbyxp** [comment]
you dont have to put it onto the channel 11 you can put it to whatever channel... or leave it auto ... just in the USA channell 11 and 12 is for long distance stuff... like if your broadcasting or chirping far away... I do alot of ESP32 IOT projects... and I have them similar to LoRa that they " Chirp"  on 2.4ghz... but legally Its on channel 11 but those esp32s radios ... they got issues beyond the scope of this that they need a specific channel set to them in station mode, which then affects the AP or esp-now modes... so you could probably just leave it on auto so it picks the less noisy channel

**Comment by serbyxp** [comment]
you could also just throw it into the bridges DMZ option which is what I do for the miner hotspot when I plug it into this thing to debug.. that way all the ports are open and the only thing thats restricting your NAT is the main modem/router..

**Comment by bruvv** [comment]
Like I mentioned in my firrst post this will not work on my ISP router and a lot of people will overlook this. This simple fix in the miner can help the network. We should not focus on how to fix it at the router end but at the miners end. please

**Comment by vanjulio** [comment]
My suggestion was to no longer include the Wifi on the miners .  Like you, I spent a long time troubleshooting and it always failed. Worse, I destroyed my power cable which led to a long string of rookie mishaps on my part, ballooning my costs on this project.  I ran for a while with ethernet connection to the TPLink extender with Eth port (https://www.tp-link.com/us/home-networking/range-extender/re105/) but this ultimately failed as well.   Conclusion - never use Wifi with helium hotspot.

**Comment by serbyxp** [comment]
Im still confused ... how you cant add a bridge.... if you clone  the MAC address in the bridge of your ISP router... and put the SSID and PW of your ISP router... into the bridge... its going to act like your ISP router... I dont have access to a sense cap so I cant tell you how it is inside of there... or what OS its running, and what access you have to the hotspot miner itself... my nebra uses balenaOS and it works over A   Bluetooth setup GUI which Scans the wifi networks and you can pick it like on your phone or whatever and type your password in  over the bluetooth connection. I personally took the wifi usb dongle out first thing I did... just cus I dont need anyone that has access to the miner ( bad actors) to have that available to them. everything worked fine without it plugged in, and with ethernet plugged into the main router. Now can a " bad actor" still do things well yes... but atleast I can blame it on Comcast and not nebra or helium... but as far as what sort of access sense cap gives you to your hotspot miner. is what youll be able to do. The balenaOS on nebra automaticlly cleans out all the config files everytime it loads and puts it back to " stock" so even if you make a change in the config.txt it resets it to " stock " there are other files which can be modified within the balenaOS which is a json,config file which doesnt change on every reload, but most probably does on every firmware upgrade... that being said you got to figure out what OS that thing is using..BalenaOS is just running the debian arm64 linux kernel.. So the config.txt is the same as the raspiOS config.txt... So you would probably need to change some sort of DTOVERLAY or DTPARAM for the WIFI... OR figure out the EBUS... but now your getting into some stuff that is beyond clicking a drop down menu and selecting 2.4 or 5ghz...and alot of this miners manufacturers arent going to implment a fleet wide change for 1 hotspot... like I say maybe if you talk to the people at sense cap themselves... maybe they can change that setting for you remotely... IF they have the time...

**Comment by serbyxp** [comment]
Like vanjulio said its just better to leave it alone and not mess with the miner what so ever. that way you have a unmodified miner, that will cause you a slew of headaches.. then when you go to ask sense cap for help on another issue.. they going to blame it on that modification and not warranty or help you. leave the miner alone, and figure out how to get a secondary bridge to work.. Like I said for my IOT projects not concerning Helum... I use an OLD router that you can probably find in your attic  somewhere or just buy one from where ever for less then 20 bucks... flash it with an openWRT or DD-WRT style firmware so that you can have full control of the bridge and its settings... That way you can do things that the " stock firmware" on the bridge router doesnt allow you to. the ISP unless your ISP is like one of those " Captive Portal" hotspot kind of things... then your going to need to " hack" that captive portal with some sort of scripting that puts your user name and password everytime it boots you off automatically

**Comment by serbyxp** [comment]
like if it is a captive portal kind of ISP that you have to log into the web browser everytime you connect to it with user name and password... the easiest route for that is to have something with a web browser on it like your Phone or a spare phone tablet .. that you can type your credientials in and then on the phone device etc... youd have to set up " network sharing " or set the phone tablet as a " hotspot"  but I read some other posts that say those captive portal style ISP like say in a DORM room or something like that... probably wont  have that port 44158 open anyways... so youll be in that "relayed " state

**Comment by bruvv** [comment]
Again I am not going to change anything on my side. it is a temporary house and nothing in this house is mine. I am not going to add anything to the network since it isn't mine. I want to change just a simple setting in the bare bones of the miner. And yes using a hotspot from my phone can be an option. But again a lot of people might not be awair that their miner is doing this. So it should be fixed. And this is the bug report for it. Stop asking about my situation and start thinking about all the miners out there in this situation where you will never be able to tell the owner what you are telling me here.

Of course you should not leave the miner alone, if there is room for improvement on the miner it should be improved. this is an improvement in my eyes. So I would say we should change it....

**Comment by serbyxp** [comment]
I don't think that's " sense cap" specific. Most wireless devices that have the dual radios will do that automatically. but that's because the device is in a " zone" of the house that the 5ghz barely reaches and the device is looking for the available signal based on its signal strength. my Laptop , my raspberry pis , even my TV does that automatically. There are settings for that ... I have had this issue on other devices. But besides the settings that you cant change from the ISP end like setting up the radios with different names.  Or on the miner that you cant " forget this network" type of option so it doesn't keep swapping out. I had a buddy with an android phone that would do that non stop and he couldn't figure it out . let me see if he figured that out, maybe hes got a " name" for the issue...

**Comment by serbyxp** [comment]
random, but maybe an option.. Does the ISP have 2 different MAC addresses for the different radios? cus that might be a way to set the miners wifi settings to that specific radio, if there is an " advanced network" setting in the miners wifi settings... you might be able to specify which MAC it connects to...

**Comment by bruvv** [comment]
Please stop posting double and use the edit button. Again it is a rental house I am not going to do anything to the wifi. All the miners that are helium approved and have wifi on board should use 2.4 ghz only. End of discussion.

**Comment by serbyxp** [comment]
well like the people at nebra told me... your on your own.

**Comment by bruvv** [comment]
You're and thanks for helping

**Comment by serbyxp** [comment]
https://pimylifeup.com/raspberry-pi-mac-address-spoofing/

**Comment by Vagabond** [comment]
This is a manufacturer specific issue, not an issue with Helium or Helium manufactured/supported hardware, please take it elsewhere.

**Comment by vanjulio** [comment]
So you're saying RAK miners are not "Helium manufactured/supported hardware" ??? I"m confused.   It is a HUGE FUCKING issue. We are writing all these problems and telling you we wasted HOURS and DAYS of our time troubleshooting black box failures.   We give you logs and you ignore it.  Thanks

**Comment by serbyxp** [comment]
Im just trying to help someone out I have no affiliation with anyone or anything, In hopes not to waste the DEVS TIME so they can actually focus on fixing there network issues.

**Comment by Vagabond** [comment]
If there's a problem with Helium supported hardware, sure we can look into that, the problem is when other manufacturers, with very different system images, get into the mix it confuses the issue and helps nobody.

**Comment by bruvv** [comment]
Indeed this whole ticket went south quickly. This is about the miner software provided by helium where it should lock all the wifi miners to 2.4 ghz. Is that doable?

**Comment by just-jase** [comment]
Turn off wifi steering on the router and it will stay on the 2.4GHz that you connected it to.

**Comment by bruvv** [comment]
@just-jase if you did not read the ticket then please do not comment something that's been said and answered already.
