### ISSUE TITLE
Some miners are having their names changed

### ISSUE THREAD

**Issue by inigoflores** [helium/miner#1371]
At least three users have reported that their miners have, all of a sudden, changed their names.

We have inspected one of them, formerly known as [Exotic Spruce Tapir](https://explorer.helium.com/hotspots/112JmF1yGFijQGbMPRKXKfsgoWbA4q8ntMdwPxYk7jF5Eou15iPd).

Running these two ssh commands, we confirm that the onboarding key is different one from the other.

    root@raspberrypi:~# docker exec provision gateway_mfr ecc onboarding
    112JmF1yGFijQGbMPRKXKfsgoWbA4q8ntMdwPxYk7jF5Eou15iPd

    root@raspberrypi:~# sudo docker exec miner miner print_keys
    {pubkey,"112NkY5FtSXgoWqVQHuiriU6PdQhe1dTyaPcdY5evMoKAfBkKZ2T"}.
    {onboarding_key,"112NkY5FtSXgoWqVQHuiriU6PdQhe1dTyaPcdY5evMoKAfBkKZ2T"}.
    {animal_name,"shambolic-dijon-fox"}.

The key the miner is showing belongs to an account:

https://explorer.helium.com/accounts/112NkY5FtSXgoWqVQHuiriU6PdQhe1dTyaPcdY5evMoKAfBkKZ2T

According to Helium Explorer

![image](https://user-images.githubusercontent.com/5518087/150208063-53b60e3a-d425-42b4-8d2e-1cf7baa669ae.png)

Can somebody explain what is going on here?

Miner is the Pisces P100, in case it's relevant.

**Comment by Vagabond** [comment]
Every possible 'account' exists, so that doesn't mean anything. I suspect somehow these ECC keys had their keys regenerated somehow? This is likely a maker issue as we don't control how the ECC is provisioned/managed.

**Comment by inigoflores** [comment]
I understand that every possible account exists. But I wouldn't expect a random account id to be indexed and return as a match. Or perhaps it's just the expected behaviour...

If you are confident this is a maker issue, I'm closing this for now.

Thanks
