### ISSUE TITLE
Miner container restarting all time.

### ISSUE THREAD

**Issue by nasked** [helium/miner#1373]
After check my router because port 44158 was  closed, I discovered  miner container is all time restarting and do not show any port (docker ps -a). Should I must create a new miner container? Can I lost my helium certificate if I create a new container? Before make this I wish to be sure there are any problem?
I suppose steps for this is at https://docs.helium.com/mine-hnt/full-hotspots/become-a-maker/basic-miner-operation
My hotspot is a Milesight UG65

**Comment by nasked** [comment]
Well..after restar container and so, seems container is running. Nevertheless install Portainer or some container to notify when miner container is fall down it could be a coold idea

**Comment by carzygod** [comment]
May be you can take a check of the sys.config . may be it is the issues of you have change the sys.config ?

**Comment by controllinohelium** [comment]
If you want to debug such issues in the future, stop the miner container...
`docker stop miner`
...and restart it with the -a parameter...
`docker start -a miner`

This will give you the output of the container and you will see why, where, etc. it crashed. Sometimes it was some Docker issue, sometimes it is a misconfigured sys.config, and so on. Can be several things, but you will move on faster if you run it like that.

When fixed, just stop and start it with...
`docker stop miner && docker start miner`

**Comment by meowshka** [comment]
@nasked I'm sorry it took a while to get back to you. If you're still experiencing this issue, please contact the manufacturer of your hotspot. Here's their discord: https://discord.gg/2wAbU4eyRy
