### ISSUE TITLE
Increased bandwidth usage since 2022.01.12.1

### ISSUE THREAD

**Issue by marvinmarnold** [helium/miner#1374]
I am a Nebra developer. We are currently investigating significantly increased bandwidth usage by our fleet since GA 2022.01.12.1. The increased usage began on Fri Jan 14, 2022 and coincides with when we [released the GA](https://github.com/NebraLtd/helium-miner-software/commit/6da74c4f6c31110744bfec4de8ac2e29f8d38e9f). The traffic appears to be due to snapshot loading, but we do not have any more details at the moment.

**Comment by abhay** [comment]
Do you have any logs to share during startup?

**Comment by marvinmarnold** [comment]
> Do you have any logs to share during startup?

At the moment, no. But will share when available.

**Comment by marvinmarnold** [comment]
Was never able to get more concrete details.
