### ISSUE TITLE
validator deb package doesn't include a genesis block

### ISSUE THREAD

**Issue by kellybyrd** [helium/miner#1385]
The deb package doesn't include a genesis block. To make the package more useful for average users, this package should include a genesis block that is auto-loaded, mainnet for main builds and testnet for test builds.

**Comment by meowshka** [comment]
Genesis block was added, closing. 
https://github.com/helium/miner/pull/1402/commits/03cb7bfc85e5cd5cfd9fc7b7633378dea397090c
