### ISSUE TITLE
No withness, no beacon sent by helium hotspot

### ISSUE THREAD

**Issue by olariupaul93** [helium/miner#1396]
Hi guys, since 5 days, no beacon was sent by my helium hotspot and in Nebra dashbord it appears 0 at withness no. Please advice.
Reward dropped 5 times from 0.2 HNT/day to 0.04 HNT/day.

**Comment by vanjulio** [comment]
You have to troubleshoot that and can't expect much sympathy when you heard the word "FLATLINE" before that means 0.0000000000 HNT/day.  I have gone more than 10 days with send a beacon.

**Comment by vanjulio** [comment]
I just have to point out we speak about so many issues getting 0.000000 HNT/day. I don't think you're going to get much help making 0.04 HNT/day .  That's a good day for me.

**Comment by serbyxp** [comment]
Heh the saga continues … make sure your up to the latest firmware, and not relayed… your not on the deny list if your still earning which is a good sign. Your going to be down for Atleast 3 hours for new firmware upgrade so leave it on and don’t mess with it for Atleast 3 hours… then check your logs to see your lovely failed to connect to challanger … your going to be pleasantly surprised with Atleast 10000 lines of those errors , and your going to feel like all of us 🤪

**Comment by meowshka** [comment]
@olariupaul93 if you're still experiencing issues with your Helium hotspot, please email support@helium.com with diagnostics information.
