### ISSUE TITLE
Miner crashing, not reviving. CRASH_REPORT in error.log

### ISSUE THREAD

**Issue by cuddlyconcretepangolin** [helium/miner#1397]
Hello,

Frequently (once per day or so), my hot spot stops hearing witnesses (as seen as a drop in "could not decrypt packet received via radio: treating as a witness" messages in console.log).  This happened today, at around 12:28.  The last "heard witness" was 12:27:

> 2022-01-27 12:27:16.510 8 [info] <0.8484.0>@miner_onion_server:decrypt:{372,13} could not decrypt packet received via radio: treating as a witness

Everything proceeds as normal. The hot spot was not able to send this witness (max_retry reached; this is normal for me). 

Then a moment or so later, I start seeing [error] logs that I don't recognize as normal:

> 2022-01-27 12:28:53.419 8 [error] <0.1074.2>@Undefined:Undefined:Undefined gen_server <0.1074.2> terminated with reason: {timeout,{gen_server,call,[<0.8374.0>,{init_proxy,<<231,16,180,142,126,60,39,55,107,126,220,59,239,105,164,12>>,<0.1074.2>,"/p2p/11mBUDGVYsZMS39vo4uaTfZ445Fc9cTVbSRu8xhYN37GAx96dsZ"}]}} in gen_server:call/2 line 239
> 2022-01-27 12:28:53.497 8 [error] <0.1082.2>@Undefined:Undefined:Undefined gen_server <0.1082.2> terminated with reason: {timeout,{gen_server,call,[<0.8374.0>,{init_proxy,<<134,161,95,98,90,19,67,209,230,157,248,126,231,214,120,209>>,<0.1082.2>,"/p2p/11mBUDGVYsZMS39vo4uaTfZ445Fc9cTVbSRu8xhYN37GAx96dsZ"}]}} in gen_server:call/2 line 239
> 2022-01-27 12:28:53.692 8 [error] <0.1077.2>@Undefined:Undefined:Undefined gen_server <0.1077.2> terminated with reason: {timeout,{gen_server,call,[<0.8374.0>,{init_proxy,<<200,162,237,45,162,48,183,218,181,126,19,242,216,234,88,60>>,<0.1077.2>,"/p2p/11mBUDGVYsZMS39vo4uaTfZ445Fc9cTVbSRu8xhYN37GAx96dsZ"}]}} in gen_server:call/2 line 239

> ...
> 2022-01-27 12:29:05.576 8 [error] <0.8457.0>@Undefined:Undefined:Undefined gen_server blockchain_state_channels_client terminated with reason: {timeout,{gen_server,call,[miner_ecc_worker,{sign,<<10,6,8,192,192,133,184,2,18,32,17,16,29,113,164,19,107,13,26,91,30,173,202,64,152,176,153,199,90,42,67,179,107,91,147,245,108,245,144,66,122,10,24,29,42,33,0,187,160,11,55,144,241,162,190,241,216,179,59,66,228,230,115,126,58,78,225,216,11,194,122,10,197,180,192,75,117,64,125>>},15000]}} in gen_server:call/3 line 247
> 2022-01-27 12:29:05.587 8 [error] <0.8457.0>@Undefined:Undefined:Undefined CRASH REPORT Process blockchain_state_channels_client with 0 neighbours exited with reason: {timeout,{gen_server,call,[miner_ecc_worker,{sign,<<10,6,8,192,192,133,184,2,18,32,17,16,29,113,164,19,107,13,26,91,30,173,202,64,152,176,153,199,90,42,67,179,107,91,147,245,108,245,144,66,122,10,24,29,42,33,0,187,160,11,55,144,241,162,190,241,216,179,59,66,228,230,115,126,58,78,225,216,11,194,122,10,197,180,192,75,117,64,125>>},15000]}} in gen_server:call/3 line 247
> 2022-01-27 12:29:05.589 8 [error] <0.8450.0>@Undefined:Undefined:Undefined Supervisor blockchain_state_channel_sup had child blockchain_state_channels_client started with blockchain_state_channels_client:start_link(#{swarm => <0.8343.0>}) at <0.8457.0> exit with reason {timeout,{gen_server,call,[miner_ecc_worker,{sign,<<10,6,8,192,192,133,184,2,18,32,17,16,29,113,164,19,107,13,26,91,30,173,202,64,152,176,153,199,90,42,67,179,107,91,147,245,108,245,144,66,122,10,24,29,42,33,0,187,160,11,55,144,241,162,190,241,216,179,59,66,228,230,115,126,58,78,225,216,11,194,122,10,197,180,192,75,117,64,125>>},15000]}} in context child_terminated

> 2022-01-27 12:30:19.259 8 [error] <0.1400.2>@blockchain_state_channels_client:maybe_send_packets:753 gen_server blockchain_state_channels_client terminated with reason: no case clause matching undefined in blockchain_state_channels_client:maybe_send_packets/3 line 753
> 2022-01-27 12:30:19.259 8 [error] <0.1400.2>@blockchain_state_channels_client:maybe_send_packets:753 CRASH REPORT Process blockchain_state_channels_client with 0 neighbours crashed with reason: no case clause matching undefined in blockchain_state_channels_client:maybe_send_packets/3 line 753
> 2022-01-27 12:30:19.265 8 [error] <0.8450.0>@blockchain_state_channels_client:maybe_send_packets:753 Supervisor blockchain_state_channel_sup had child blockchain_state_channels_client started with blockchain_state_channels_client:start_link(#{swarm => <0.8343.0>}) at <0.1400.2> exit with reason no case clause matching undefined in blockchain_state_channels_client:maybe_send_packets/3 line 753 in context child_terminated
> 2022-01-27 12:30:19.265 8 [error] <0.8450.0>@Undefined:Undefined:Undefined Supervisor blockchain_state_channel_sup had child blockchain_state_channels_client started with blockchain_state_channels_client:start_link(#{swarm => <0.8343.0>}) at <0.1400.2> exit with reason reached_max_restart_intensity in context shutdown
> 2022-01-27 12:30:19.326 8 [error] <0.8339.0>@Undefined:Undefined:Undefined Supervisor blockchain_sup had child blockchain_state_channel_sup started with blockchain_state_channel_sup:start_link(["/var/data"]) at <0.8450.0> exit with reason shutdown in context child_terminated

This triplet of `gen_server blockchain_etate_channels_client....`, `CRASH_REPORT`, `Supervisor blockchain_state_channel_sup` repeats a couple of times per minute until I do a hard power cycle on the miner.

I have saved `console.log`, `error.log`, and `crash.log` from `/var/data/log/`. I have pushed them here: https://github.com/cuddlyconcretepangolin/helium_error_logs/tree/main/2022-01-27_12-27

I will continue to monitor, but please let me know if you have any suggestions to fix this issue, or what could be causing it.  It is frustrating, to say the least. 

(RisingHF miner, v2022.01.12.1, cuddly-concrete-pangolin, not relayed)

**Comment by Vagabond** [comment]
This appears to be a problem with the crypto-chip on the i2c bus where it intermittently cannot be communicated with. I would contact the manufacturer to see if they have any suggestions.

**Comment by cuddlyconcretepangolin** [comment]
Can I ask what exactly tells you this?  I have opened a support ticket, but the manufacturer is overwhelmed with support tickets at the moment.

I'd like to continue to poke around and learn more about this system; it's been a fascinating ride so far.

**Comment by Vagabond** [comment]
`timeout,{gen_server,call,[miner_ecc_worker,{sign,` means the ecc chip did not respond to an attempt to sign a message.
