### ISSUE TITLE
validator deb package should be published for Ubuntu 20.04

### ISSUE THREAD

**Issue by kellybyrd** [helium/miner#1403]
The current deb package is uploaded to package cloud with distro id  `190` (see https://github.com/helium/miner/blob/master/.buildkite/scripts/packagecloud_upload.sh)  which appears to be Ubuntu 18.04. This LTS release is almost EOL, and most new Ubuntu LTS installs will be 20.04. The deb package should be tagged in package cloud for 20.04.

It think you need to have an API key to get the mapping of distro_version_id to Ubuntu 20.04, so probably only someone on the Helium team with access to `PACKAGECLOUD_API_KEY` can make this change.

**Comment by PaulVMo** [comment]
I have tested the deb package on 20.04 and it works great. As kelly suggested, just updating the distro id or adding a second one if support should suffice.

**Comment by meowshka** [comment]
distro id was updated, closing. https://github.com/helium/miner/commit/571ed2cf147a89a04984ca0a52c530fa4c17ea01
