### ISSUE TITLE
OG Helium Hotspot flatline after 2022.01.24.0 release

### ISSUE THREAD

**Issue by yooitsgreg** [helium/miner#1404]
OG Helium Inc hotspot has not witnessed or had a beacon witnessed since the release of the 2022.01.24.0 firmware. Diagnostics show everything is fine. Is this a known issue? Anything to further troubleshoot/fix?

Atomic Mocha Cheetah
https://explorer.helium.com/hotspots/112eWyTrhGz6qYM7YSRGvmC1aeW7QUdfVeXALDiGMwCX9sn8c1gp

**Comment by Raimis707** [comment]
The same with mine Sensecap, it looks like the transmitter power is greatly reduced

https://explorer.helium.com/hotspots/112LE8LfuciJbL6u49KLbmctF4uVdxw3ZnHd1NwutyvFuMdpdEPh

**Comment by meowshka** [comment]
@yooitsgreg can you please contact support@helium.com with diagnostics information for your hotspot? The team will help troubleshoot.
