### ISSUE TITLE
GA tagged images not being made on releases?

### ISSUE THREAD

**Issue by Jonzky** [helium/miner#1409]
Not too sure if it's intentional or a bug, but it looks like GA tagged images are not being pushed alongside the :latest tag.

It looks like that part of the _beta / _alpha addition the GA tagging was removed.
https://github.com/helium/miner/commit/2adf5e8a28c73f335f782a1227a8ef725560ec3d

Just wanted to clarify if this was intentional.

Some manufacturers (or Nebra at least) have not released 2022.01.27 as they are waiting and reliant on the GA.
https://github.com/NebraLtd/hm-miner/pull/72

**Comment by Vagabond** [comment]
Does line 77 not check for the GA tag?

**Comment by Jonzky** [comment]
@Vagabond It does, but it doesn't tag the container image - it effectively strips it and only pushed an image tagged with :latest.

This isn't an issue for me, but it seems like Nebra is holding out on the release until there is a GA image.

**Comment by Jonzky** [comment]
Big thanks for helping with this and getting it resolved so fast. Closing the issue as it should be fixed.
