### ISSUE TITLE
Snapshots are not compatible with older versions

### ISSUE THREAD

**Issue by marsxiang** [helium/miner#1414]
Using the official new snapshot, an error occurred.

![image](https://user-images.githubusercontent.com/6489149/151980711-45ef829b-903c-4937-b42d-7aab90ad4ebf.png)

We studied the source code and found that the new snapshot is incompatible with the old version of the code.

Processing logic of old version:
![image](https://user-images.githubusercontent.com/6489149/151981149-9e4fe469-a789-4ff4-8f2f-69503d1d24f3.png)

New version of processing logic:
![image](https://user-images.githubusercontent.com/6489149/151981234-9e9bddf5-178c-4f73-9e13-70628f2365d2.png)

The new version does not support map!

@evanmcc

**Comment by evanmcc** [comment]
I'm sorry, this stuff is hard to coordinate.  Newer releases support both versions, so this should resolve relatively soon.
