### ISSUE TITLE
Frequency Plan modification for Kazakhstan : add of EU868

### ISSUE THREAD

**Issue by gboisgontier** [helium/miner#1416]
Hello, 

For Kazakhstan country (KZ) ,  the ministry of Information & Communication is authorizing two frequency plans: 433-434MHz but also 863-868 MHz bandwidth (as seen in screenshot enclosed). 

Would it be possible to update Helium frequency plan to add the EU868 to Kazakhstan ? 
https://docs.helium.com/lorawan-on-helium/frequency-plans/

I understood that once a gateway is onboarded on the blockchain it is forced to communicate to frequency plan defined by the DeWi but as our equipment is 868 (and supposed to work in Kazakhstan), it may not if 433 is requested...

Let me know if it the right place to ask for this or if i should ask to DeWi LoRaWAN Committee via #dewi in the Helium Discord
Thanks a lot, 

Best Regards, 
Guillaume

<img width="497" alt="Kazakhstan" src="https://user-images.githubusercontent.com/98596691/152186482-73748b63-ea91-4813-ae60-1c7ea1339ac4.png">

**Comment by meowshka** [comment]
@gboisgontier based on the approved HIP45, there are no plans to add support for frequency selection. From HIP45: "....operators in Australia could select AU915 or AS923-1 when they assert location. We believe this to be problematic as it will lead to fragmentation of coverage and confusion on behalf of network users. Instead, we believe such mechanisms would be useful for expanding into additional subbands." You can read the full proposal here: https://github.com/helium/HIP/blob/main/0045-lorawan-frequency-plan-selection.md
