### ISSUE TITLE
NO WITNESS BUT BEACONING BOBCAT MINER HELP

### ISSUE THREAD

**Issue by derryxs** [helium/miner#1417]
Hi I  need help for my Bobcat hotspot, I have changed its location on app to a different city, it was working fine at its previous location,  it has been almost 2 days now, I have enough hotspots around, the problem is that I can send beacons to 14 hotspots with a good signal level, however I cannot see any witnesses at this new location,

can anyone help me on this issue?

here is my hotspot :

https://explorer.helium.com/hotspots/11pAPZSh2usRCXdZqhtpqUBKJs5RtGYcqvYWp69pMAibkLDX8Cz/activity

I am at high in elevation and can clearly see the whole city as LOS

I have 6 dBi omnidirectional antenna at 15 meters,

I used 10 meters of LMR400

It is aslo synced and checked from local server

Device name:

Tall Bubblegum Porpoise

Location: Gaziantep

**Comment by derryxs** [comment]
37°06'30.4"N 37°17'07.7"E check from this location if possible

**Comment by bennofle** [comment]
hello, i got the same problem with 2 bobcat minerns.
It looks exactly the same.
Jolly ash caribou 
And hot lemon scallop

**Comment by derryxs** [comment]
So what I have realized is that I have a GSM and UHF TV tower nearby, I used SAW filter at input and canceled out the bobcat miners lightning arrestor part, I directly connected the wire to the RF card input, and my antenna was 5.8 dbi, I also increased it to 8 dbi to compansate losses, 
Now I have started seeing the witnesses,

![IMG-20220205-WA0012](https://user-images.githubusercontent.com/6908792/152747835-3b5d7e13-486c-41a2-b246-6522f966cebb.jpg)
![IMG-20220205-WA0009](https://user-images.githubusercontent.com/6908792/152747839-3ac51378-5d0d-4d2e-aff1-8b198031d92e.jpg)
![IMG-20220206-WA0001](https://user-images.githubusercontent.com/6908792/152747844-9c79783e-892c-43b5-bf1d-ceb6694cecea.jpg)

**Comment by bigjuanpa** [comment]
Hi, so you disconnect the lightning arrestor ?
I have the same issue no witness,
How did you test the increase of dbi ?

**Comment by derryxs** [comment]
Actually I have changed the antenna, I was far from city, no witness can happen due to noise, I suggest filter, I had to remove arrestor part because I have used Saw filter which cause more loss than Cavity, to compansate I have changed the Bobcat miner inside pig tail cable and connected directly to rf card input bypassing the arrestor connection,

**Comment by bigjuanpa** [comment]
cool, I will test that.
thanks

**Comment by jautism12** [comment]
> hello, i got the same problem with 2 bobcat minerns. It looks exactly the same. Jolly ash caribou And hot lemon scallop

Did you end up fixing this issue? How?

**Comment by AlexHel101** [comment]
@derryxs Hi man, I have the same problem, could you show us how to do it please?

**Comment by Matrox1983** [comment]
I have exactly the same, my beacons are witnessed by other hotspots up to 20km away.
Looking at the rssi and Snr values I can tell the Bobcat is really deaf. Replaced the Bobcat with a sensecap and the problems were solved.

As long as I keep the Bobcat low with the stock antenna the results are better.

I think it's caused by the GSM antenna nearby that is pointed my direction.

What is the best solution to fix this problem?

**Comment by michuneo** [comment]
Similar issue - can't find anything wrong with set up of mine P100 

7d avg beacons are decent 44 - but total witnessed within past 5 days is one and I don't think that changed much during whole month.

The only thing I can think of now is a complex of many sensors, antennas and transmitters at the very nearby intersection.

**Comment by omara256** [comment]
got the same problem here
