### ISSUE TITLE
Miner is unable to beacon

### ISSUE THREAD

**Issue by rami202** [helium/miner#1420]
I have a heltec that is not able to beacon anymore, last beacon was 21 days ago. In mean while nothing has changed and the miner has been reseted multiple times, still won't beacon. In addition, hotspot is running latest version firmware and is connected with internet cable.

Hotspot name: Dapper Myrtle Scorpion
11egNcYxVjCV3ZrR64U9Z6rZQqBP3BbHpAB5Twk9zeyuz8mn8SL

Could you please take a look ?

**Comment by trader156** [comment]
If you find out a solution, please write to me, because I have the same issue.

**Comment by rami202** [comment]
nope

**Comment by rami202** [comment]
did you find a solution @trader156

**Comment by trader156** [comment]
So an upgrade on my miner. I had to switch it off for a few days, due to e poe adapter issue and after I think 4 days I turned it back on. Cleared the blockchain data, just to be sure, and synced the device again. Now for the past 3 days it has been working fine and is sending out beacons.

**Comment by rami202** [comment]
> 

no i didn't

**Comment by mehmetes-sudo** [comment]
I have the same issue.

**Comment by meowshka** [comment]
@rami202 activity on your hotspot looks normal now. Please contact the manufacturer directly if you experience any other issues. Here's their discord: https://discord.gg/Pt85TrZfxZ
