### ISSUE TITLE
unable to participate in any blockchain activity

### ISSUE THREAD

**Issue by rami202** [helium/miner#1421]
Hotspot is fully synced and  added succesfully to the blockchain, however it's unable to participate in any blockchain activty!
hotspot is running latest version firmware and is connected with internet cable.

Hotspot name: Long Azure Nuthatch
112KhX4bffgEFej2dirp6QHkLHGingYE8kxP8VF6iZaxCWUZkoXe

**Comment by mgvos3** [comment]
have you found a solution to this? I am having the same issue with my RAK Gold miner using a hotspot with vpn router for a Static IP

**Comment by rami202** [comment]
its kindof solved, i think. Today it went online and started to do somthing. However I think it had something to do with the internet not forwarding any packages and blocking all activity.

**Comment by rami202** [comment]
its now relayed as well so should open the poorts and see whatsapp. Question form my side... why are you using vpn?

**Comment by mgvos3** [comment]
gotcha, thanks for the quick response

**Comment by mgvos3** [comment]
using a VPN so as to create a static IP. the wireless hotspot i am using for internet only has DHCP option. using mango router to run the vpn

**Comment by rami202** [comment]
miner was not port forwading packages or data due to a router issue, so after changing the router it started working like a champion!!
