### ISSUE TITLE
Sync problem: miner_critical_sup had child blockchain_sup on bobcat miner

### ISSUE THREAD

**Issue by oljwW3po** [helium/miner#1422]
Hi everyone. I have a problem with my bobcat from the day I've received it.  It always keeps falling out of sync with similar issue. Since I've received it, I started with onboarding without updating it to the latest version (I know that's bad). Since Bobcat cannot be access over SSH users, I can't get more logs that the UI itself provides. 

Key facts: 
```
ota_version": "1.0.2.79
Image": "quay.io/team-helium/miner:miner-arm64_2022.01.29.0_GA
"ports": {
    "Private IP:22": "open",
    "Private IP:44158": "open",
    "Public IP:22": "open",
    "Public IP:44158": "open"
```
Erorrs: 

> 2022-02-07 15:54:36.931 1 [error] \u003c0.1506.0\u003e@Undefined:Undefined:Undefined Supervisor miner_critical_sup had child blockchain_sup started with blockchain_sup:start_link([{key,{{ecc_compact,{{'ECPoint',\u003c\u003c4,56,32,100,105,186,234,223,157,47,167,150,54,217,80,13,67,...\u003e\u003e},...}},...}},...]) at undefined exit with reason {shutdown,{failed_to_start_child,blockchain_worker,{badarg,[{erlang,binary_to_term,[\u003c\u003c131,104,17,100,0,10,103,97,116,101,119,97,121,95,118,50,109,0,0,0,33,1,221,207,12,253,198,126,108,237,125,151,69,32,19,100,59,9,14,148,130,185,243,214,200,162,72,13,186,225,179,244,171,188,110,8,0,255,131,170,105,237,141,194,8,70,63,240,0,0,0,0,0,0,70,63,240,0,0,0,0,0,0,97,0,98,0,18,110,21,109,0,0,0,32,184,99,30,25,172,153,237,107,178,51,83,211,109,154,134,43,9,178,124,108,25,193,35,194,55,245,65,148,149,...\u003e\u003e],...},...]}}} in context start_error'    Please try to power off then power on. If that doesn't work contact support.     :'

Symptoms: 
- Miners keeps rebooting (hourly)
- Frequently downloads the snapshot, but keeps failing with the message above

What I tried: 
- Reset miner many times
- Resync miner many times
- Fast Sync after Resync and Reset (tried without Resync as well).

Description: 
I have two miners on the same location. The idea was to set up both, one keeps at home and others replace at other location. One miner (which works good) is connected via my home router. 
The issue miner is connected via VPN IPSEC tunnel to Linode VPS and has different ip's as the one at home. Portforwarding is enabled and tested. I had both miner on the same wallet, but once i removed the problem miner to another wallet - it was shortly able to beacon and then died again (it was 3 days ago). On the map the problem miner is moved about 100m away from my "working" miner. 
As it worked it was something like that: 

1. Transfer hotspot
2. Constructed Challenge 
3. Challenged Beaconer 
4. Received Mining reward
5. Dead

The idea was not to trick the system, but only to set up everything and make sure that it works - and then remove to the location it was originally planned to. 

Does anyone have a hint what may be the problem? For me, it looks like the Sync or DB Container keeps failing and cause all the issue. But since Bobcat user cannot access the miner over SSH only thing I can do is guess. I opened a ticker at bobcat month ago, but nobody from the engineering team contacted me yet. Any input would be appreciated. Currently I'm out of ideas.

**Comment by Liixee** [comment]
Hello,

i have the same issue :(

**Comment by meowshka** [comment]
@oljwW3po this shouldn't be an issue after full transition of the system to Light Hotspots. Please contact the manufacturer of your device if you still have any problems with it. Here's their discord: https://discord.com/invite/2Barf528uj
