### ISSUE TITLE
SenseCap M1 miner haven't broadcasted any beacons for the past 10 days?

### ISSUE THREAD

**Issue by mercy719** [helium/miner#1425]
Hello everyone, my hotspot is Real Hazelnut Bee, it haven't broadcasted any beacons for the past 10 days. Before that I got one beacon per day on average. It witnesses beacons from other hotspots just fine but is having issue broadcasting beacons. The hotspot is not in relayed status so I don't think port forwarding can solve it. Please let me know what I can do to solve this problem!

**Comment by trader156** [comment]
If you find out a solution, please write to me, because I have the same issue.

**Comment by Lefthook90** [comment]
I'm having this exact issue with my sensecap. I can witness and challenge beacons, but haven't broadcasted a beacon in 14 days. Please let me know if you find a solution.

**Comment by meowshka** [comment]
@mercy719 please contact manufacturer of your hotspot directly regarding this issue. Here's their discord: https://discord.gg/HzgM7t2fBb
