### ISSUE TITLE
RAK miner offline after SD card replacement

### ISSUE THREAD

**Issue by adamjankwiatek** [helium/miner#1429]
Hi everyone, 

A while ago, 2 of my 3 RAKs have flatlined. I decided to replace SD cards after doing some research. 

I have replaced the SD cards on 2 of the miners so far - one of them was working, but I decided to replace the stock 32GB card anyway. The one that had flatlined started working within a day, but the one that was working stopped after the replacement. The procedure pretty much reversed the statuses. Both cards were brand new and flashed the same way. I even replaced the card once again, suspecting there was something wrong with that particular unit, but to no avail. 

The stuck RAK is currently offline and not syncing. I have limited access to the miner, so I check its status via the [API](https://api.helium.io/v1/hotspots/112sEKPBoEAhWMdunLaen9esP9DYnhwNDxBzAd91kKuBbckL29eH). The last_change_block does not seem to update. 

I would highly appreciate some advice. [Here is the miner in question](https://explorer.helium.com/hotspots/112sEKPBoEAhWMdunLaen9esP9DYnhwNDxBzAd91kKuBbckL29eH).

**Comment by meowshka** [comment]
@adamjankwiatek please reach out to the manufacturer of your hotspot directly. Here's their discord:  https://discord.com/invite/gae6cGa7jn
