### ISSUE TITLE
Beconing Issues with Helium miner

### ISSUE THREAD

**Issue by HarpreetGandhi** [helium/miner#1436]
Hi,

We are facing lot of Beconing Issues with Helium miners of ClodPi (Manufacturer) devices in India.
There are hardly any becons per day or sometimes no becons for few days.  The community has been chasing the manufacturer for help or updates but the manufacturer says it's Helium issue and cannot help.

Appretiate any inputs/help in this regard and if it's an helium issue how long will it take to resolve as it's almost a month or two we are facing this issue or atleast from the beginning this manufacturer started its distribution.

Many Thanks.

**Comment by serbyxp** [comment]
Ask your manufacture if they have port 31341, open some to the radio , I run my hotspot image with port 31341 which is in the sys.config file, if it’s in a container style distribution or like postman balenaOS then something I noticed is the Oficial image only has 1680 open , but the same image binds the radio TX to the second port in the the radio section of sys.config , which is fine if your running it off of the Linux Bullseye OS , but if your using containers, I would try opening that port, or binding it to port 1680 to the local OS if your packet forwarder is running in a different container or bus I have no problems beaconing with that set up.

**Comment by meowshka** [comment]
@HarpreetGandhi please contact the manufacturer of your hotspot directly. Here's their discord: https://discord.gg/unJjAtZHBZ
