### ISSUE TITLE
status (timestamp: null,  listen_addrs: null, height": null)

### ISSUE THREAD

**Issue by lind-ucdcd** [helium/miner#1444]
hello dear helium team i have this problem in my hotspots api 
can you please tell me what's the problem?

  "status": {
        "timestamp": null,
        "online": "online",
        "listen_addrs": null,
        "height": null
      },

https://explorer.helium.com/hotspots/11DVYPt8KZG9GJKF956Ucic1ypuYuzLadtTxLyXif4HEJpxEne6
https://explorer.helium.com/hotspots/11RkqgEde9iBcsBAaDD3qQ9nGivptp3chWzd7dMyc7YdNrYtwqg

**Comment by Raimis707** [comment]
Very similar problem wit mine hotspot from 2022.01.25, but i do not know api status.

Pet bronze barracuda

**Comment by lausser** [comment]
Same here, it's a MerryIOT/Browan which i setup over a week ago. Using the Helium App & Bluetooth it says "100% synced".
In the explorer however, still "syncing". And when i query the API, i get exactly  the empty status json like above.
44158 is open, the hotspot is reachable from the internet, there is also a lot of traffic sent back and forth. But it does not update its external address to the blockchain.

**Comment by swadegeiger** [comment]
Did someone eventually figure this out? Of the devices listed above, it looks like one is online, one is offline, and the other might be relayed?

**Comment by meowshka** [comment]
@lind-ucdcd please contact manufacturer of your hotspots directly regarding this issue.
