### ISSUE TITLE
Hotspot not broadcasting beacons

### ISSUE THREAD

**Issue by Lefthook90** [helium/miner#1447]
My Sensecap M1 miner has not broadcasted a beacon in 13 days.

 My hotspot is able to witness and challenge beacons, but unable to broadcast them. The sensecap dashboard shows that it is fully synced, not relayed and healthy. The dashboard also shows that there is is P2P inbound and outbound data being transfered. 

Does anyone know why my hotspot is unable to beacon?

My hotspot name is Suave Hazelnut Chicken

**Comment by Raimis707** [comment]
my sensecap from 01.24 stopped broadcasting and witnessing.  no one helps, waiting for mercy so far will fix this bug

**Comment by Lefthook90** [comment]
> my sensecap from 01.24 stopped broadcasting and witnessing. no one helps, waiting for mercy so far will fix this bug

Let me know if you get it sorted and I will do the same

**Comment by Raimis707** [comment]
> 

i tried everything, last chance, i turn off the hotspot for a few days.  then i will try tur on back maybe in the meantime something will change in the helium pool or got a new update. I will write help it or not.

**Comment by Lefthook90** [comment]
> > 
> 
> i tried everything, last chance, i turn off the hotspot for a few days. then i will try tur on back maybe in the meantime something will change in the helium pool or got a new update. I will write help it or not.

Have you recently switched from WiFi to Ethernet? I think I found out why my miner wasn't beaconing.

**Comment by Raimis707** [comment]
> from

I am using ethernet all time. Couple times i had tried with nwifi but nothing changes.

**Comment by Lefthook90** [comment]
My problem was I switched from WiFi to Ethernet and had multiple ip addresses for my miner.

 I was able to fix this by doing a diagnostic test and forgetting my WiFi network. I also set a static ip address on my router, disabled UPnP, and port forwarded port 44158 again.

**Comment by Raimis707** [comment]
> My problem was I switched from WiFi to Ethernet and had multiple ip addresses for my miner.
> 
> I was able to fix this by doing a diagnostic test and forgetting my WiFi network. I also set a static ip address on my router, disabled UPnP, and port forwarded port 44158 again.

glad you found a reason for me to be fine with ip, i hope the helium firmware released today will solve my problem.

**Comment by Lefthook90** [comment]
I may have spoken too soon. My miner has not beaconed all day

**Comment by adrianformunda** [comment]
> > my sensecap from 01.24 stopped broadcasting and witnessing. no one helps, waiting for mercy so far will fix this bug
> 
> Let me know if you get it sorted and I will do the same

The hotspot is synced? Usually that is the reason for not doing anything.

**Comment by adrianformunda** [comment]
> 

Looks like you have 3 beacons in the last 24h

**Comment by matta1336** [comment]
i have the same sent beacons every day for 6 months then 3 days ago just stopped , how to fix this please

**Comment by ViktorVVVV** [comment]
@Lefthook90 I have the same issue since I switched to ethernet. What do you mean by 'observed IP'?  I did not find such in heliumtracker.

**Comment by MacZaki** [comment]
> I got it sorted yesterday using heliumtracker.io. My issue was that my listen ip was different from my observed ip. My miner is finally beaconing consistently!

Can you explain what you have done please!

**Comment by chatawan** [comment]
> > I got it sorted yesterday using heliumtracker.io. My issue was that my listen ip was different from my observed ip. My miner is finally beaconing consistently!
> 
> Can you explain what you have done please!

Yes, could you please explain this in more detail?
