### ISSUE TITLE
Pisces P100 Sending beacons, but not witnessing, beacons not witnessed either

### ISSUE THREAD

**Issue by jautism12** [helium/miner#1453]
Hello,

My Pisces p100's beacons arent being witnessed, and its not witnessing any nearby hotspots/beacons either. There's a few other Pisces p100s nearby, and theyre functioning Flawlessly, witnessing and everything without any problems, but my miner refuses to witness at all. I doubt the nearby pisces all already have the SAW filter, as theyve been up and running for months. 

My miner is located on the 3rd floor of a tall building overlooking the city, but that being said it isnt on the very top floor or anything. Could that be why its getting zero witnesses? What else could be the reason; what else can i do? Thanks!

My miner: https://explorer.helium.com/hotspots/112MSWHffLk8T6oGbNxmAaw3fhuWJz2D7rWvPFs3kdGH5xx1uEJG

**Comment by MarcDietschi** [comment]
Same problem with my Nebra Rock Pi 4 Indoor Miner: Firmware Version | 2022.02.22.0, 8dBi antenna, 20 meters over ground

**Comment by oltionnikolla** [comment]
same here, i found this in error log:
`
2022-02-28 04:11:40.162 [error] <0.9522.1>@miner_onion_server:send_witness:{207,5} failed to send witness, max retry
2022-02-28 06:13:06.885 [error] <0.16733.1>@miner_onion_server:send_witness:{207,5} failed to send witness, max retry
2022-02-28 08:28:24.262 [error] <0.24233.1>@miner_onion_server:send_witness:{207,5} failed to send witness, max retry
2022-02-28 08:29:32.265 [error] <0.24277.1>@miner_onion_server:send_witness:{207,5} failed to send witness, max retry

`

**Comment by baturalps** [comment]
@oltionnikolla  how did you access to logs or SSH?

> same here, i have Browan/MerryIoT, i found this in error log: ` 2022-02-28 04:11:40.162 [error] <0.9522.1>@miner_onion_server:send_witness:{207,5} failed to send witness, max retry 2022-02-28 06:13:06.885 [error] <0.16733.1>@miner_onion_server:send_witness:{207,5} failed to send witness, max retry 2022-02-28 08:28:24.262 [error] <0.24233.1>@miner_onion_server:send_witness:{207,5} failed to send witness, max retry 2022-02-28 08:29:32.265 [error] <0.24277.1>@miner_onion_server:send_witness:{207,5} failed to send witness, max retry
> 
> `

**Comment by meowshka** [comment]
@jautism12 please contact the manufacturer of your hotspot directly regarding this issue. Here's their discord: https://discord.gg/cBwEUxHcn4
