### ISSUE TITLE
Docker (no_gateways)

### ISSUE THREAD

**Issue by arduino43** [helium/miner#1478]
Hello,

I have my RAK miner up and running on Rasbian. It reads the keys correctly, syncs and challenges, but it doesn't appear to be able to send to gateway.

Perhaps I am misunderstanding how these are setup, but does the docker container control the radio/packet forwarder?

Error:
2022-03-09 00:42:50.459 [error] <0.1873.0>@miner_onion_server:decrypt:{431,61} unable to send_poc, reason: no_gateways

**Comment by RepRapid** [comment]
The miner software Image does not have a built in packet_forwarder software. Their is another docker container for packet_forwarder software. Corresponding ports need to be forwarded or in docker terms "Exposed" or "Bind"ed to the Docker instance / container. If you have Packet_forwarder running on Raspbian and not in Docker, Then you would need to -bind port 1680:1680 to allow access from your radio into the Miner container AND if your Packet_Forwarder software is running in a Docker Container , connected with a HAT to the Raspberry PI you would need to expose the port and give the docker container Privilege to access the SPI bus pins, including the reset pin * In the Packet_Forwarder container*

**Comment by arduino43** [comment]
Thanks!

**Comment by no1bob** [comment]
Any solution for this, since I have exactly the same problem?!
