### ISSUE TITLE
Loading new Denylist Seemingly Failing (Logging Broken)

### ISSUE THREAD

**Issue by benengele** [helium/miner#1482]
Seems the logging happening when a new denylist is loaded is broken:
`2022-03-09 21:15:05.829 145 [info] <0.1972.0>@miner_poc_denylist:handle_info:{109,29} FORMAT ERROR: "new denylist version appeared: ~s have ~s" [2022030901,2022022201]`
`2022-03-12 07:56:59.945 135 [info] <0.2247.0>@miner_poc_denylist:handle_info:{109,29} FORMAT ERROR: "new denylist version appeared: ~s have ~s" [2022031101,2022030901]`

Users seeing this message will think the denylist is broken.

**Comment by meowshka** [comment]
@benengele thank you for reporting. The format issues has been fixed https://github.com/helium/miner/commit/fc7501fe6957dd1ea8aac939be99c68bff49d3fc
