### ISSUE TITLE
Miner crash after rocksdb:get $var_sc_version 

### ISSUE THREAD

**Issue by fredsco** [helium/miner#1495]
I'm experiencing an issue where the miner keeps restarting after 2/3 minutes, it happens after the miner is trying to install a snapshot, and restarts after this log: 

[error] <0.1803.0>@blockchain_ledger_v1:config:1397 gen_server blockchain_state_channels_client terminated with reason: bad argument in call to rocksdb:get(#Ref<0.1440384285.2621571082.200254>, #Ref<0.1440384285.2621571082.200255>, <<"$var_sc_version">>, []) in blockchain_ledger_v1:config/2 line 1397

I have tried to remove the miner container and its data, checked docker_config but nothing seems to help.

**Comment by meowshka** [comment]
@fredsco please reach out to the manufacturer of your hotspot directly regarding this issue.
