### ISSUE TITLE
Online Status: P2P/IP4 connection Failed. Most of my miners are not witnessing?

### ISSUE THREAD

**Issue by M155WDY** [helium/miner#1497]
Hi everyone, I currently have issues with over half my miners I am hosting. All hotpots are installed correctly and have external aerials on rooftops. Earnings have been going down every day for past 2 weeks and a lot of my miners are not witnessing at all which is bizarre. When I do a ping test - this is what I am getting on the heliumtracker.io dashboard always - P2P/IP4 connection Failed. Hotspots are online and sending beacons etc but not witnessing. I have 67 miners in place and my earnings are 6 hnt per day. Most are installed with the tplink wifi plugs also. Can anyone tell me what the issue is or what action they think I need to take ref witnessing issues? 

One of my hotspots is called: Hot Coconut Eagle. Any info or anything you think I can do would be gratefully received.

**Comment by meowshka** [comment]
@M155WDY please contact the manufacturer of your hotspots directly regarding this issue.
