### ISSUE TITLE
Low/No witness activities for the past 3 weeks 

### ISSUE THREAD

**Issue by KhalidKhazal** [helium/miner#1510]
I noticed that my Panther X2 miner has reduced amount of witnessing activities to almost no activities for the past 3 weeks, broadcast beacons are always successful, but no witnessed activities 

https://explorer.helium.com/hotspots/11cP2LtxKfPRcqckNf4YdesdRCYcyW6zM8SbyQ9L3YZZf3ogWNj/activity

**Comment by meowshka** [comment]
@KhalidKhazal looks like there is normal witness activity now for your hotspot. If you have any other issues, please contact the manufacturer directly.
