### ISSUE TITLE
Bobcat miner 300 fatal network states

### ISSUE THREAD

**Issue by Foggy045** [helium/miner#1512]
I got issue with bobcat miner  keeps getting fatal network states i have to reboot miner every single day
Dont know the reason for it. Its not realed or internet port issue its just says fatal

**Comment by Foggy045** [comment]
![Screenshot_20220327-102753](https://user-images.githubusercontent.com/102478509/160292687-d10bcee7-ce37-4794-abf7-63657f00e22a.jpg)
![Screenshot_20220320-174524](https://user-images.githubusercontent.com/102478509/160292697-d5992abe-8fa1-4850-8a72-cb341b74ed11.jpg)

**Comment by ThinkGet** [comment]
I just got my bobcat miner as well after many months of waiting, I just installed it and couple day later now I’m also getting Network Status Fatal, what do we do.

**Comment by Foggy045** [comment]
> I just got my bobcat miner as well after many months of waiting, I just installed it and couple day later now I’m also getting Network Status Fatal, what do we do.

No idea im also trying find the problem  so far ive contracted bobcat vis email but thay just ask me to reset the miner then wait for 24hrs but still similar symptoms gets long gap staff i think its got bug in software dont know hw to reset the software

**Comment by ThinkGet** [comment]
I figured out first open port 44158 in router then restart, your router id and info will be in the back of your router to log in via computer browser, should be something like 192.1..... several numbers.

Then you will need to log into you bobcat miner via web browser 192.168.1.138 this will land you to the page below. Try to first press reboot button, user= bobcat , password = miner wait 10 min until reboot is complete , you will need to refresh your browser. Then press resync miner, it will prompt for user and password, user= bobcat, password = miner, this will delete the blockchain and helium software and reinstall and sync from zero, make sure power is always on, this may take several hours. Once complete you will see a gap number, then you will do a Fast sync(Alpha), once complete you may see a gap of zero, then do one last reboot.

FYI do not use the Reset Miner button, more info can be found in the bobcat diagnoser user guid on the bobcat miner official page

Best of luck 
![image](https://user-images.githubusercontent.com/103283198/163700670-43828234-ba7d-4e33-971e-8e823068c714.jpeg)

**Comment by meowshka** [comment]
@Foggy045 please contact Bobcat directly regarding this issue. Here's their discord https://discord.com/invite/2Barf528uj
