### ISSUE TITLE
but he can help me with the problem I have with my miner Bobocat300, he doesn't do anything for many hours, that is 12, , 15.20 h daily https://explorer.helium.com/hotspots/latest mining name. Swif Vini Babger. Romania (Bucharest)

### ISSUE THREAD

**Issue by Crisatian** [helium/miner#1513]
but he can help me with the problem I have with my miner Bobocat300, he doesn't do anything for many hours, that is 12,
, 15.20 h daily https://explorer.helium.com/hotspots/latest mining name. Swif Vini Babger. Romania (Bucharest)

**Comment by meowshka** [comment]
It could have been a temporary syncing issue with blockchain. Looking at your miner in the Explorer, I don't see any problems right now. If you have any other questions, please feel free to post them in the Discussions board.

**Comment by Crisatian** [comment]
what a shit you did, you killed Bobocat300, I know I'm not the only one,
shit all that means hilium, dust and lumps, who can help me know if my
guest Swift Vinyl Badger from Romania is more threatening or not, dead for
24 hours, may be canceled by someone in the validatorsHilium experts, let
me know if I can mine Hilium or not, what the fuck is this, please insist
on clarifying me too.

joi, 12 mai 2022, 08:02 meowshka ***@***.***> a scris:

**Comment by Crisatian** [comment]
failed to get peer book. Post
"http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/1dd755fd378876bf689711f9f06f09af06bcd34b55d9b4d33e0af537cb735e74/exec":
context deadline exceeded
Afișează textul citat

joi, 12 mai 2022, 09:06 Cristian Petrica Jarca <
***@***.***> a scris:

**Comment by Crisatian** [comment]
hello how are you, it seems you haven't solved my old problem with any
abdeit that I have on the Bobcat 300 Swift Vinyl Badger. failed to get peer
book. post "http:
//%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/1dd755fd378876bf689711f9f06f09af06bcd34b55d9b4d33e0af537cb735e74/exec":
context deadline exceeded

joi, 12 mai 2022, 08:02 meowshka ***@***.***> a scris:
