### ISSUE TITLE
Miner's bug about IN865

### ISSUE THREAD

**Issue by xiaoye-x** [helium/miner#1514]
I found an issue while using Miner and I put it together as a pdf, 
could you check here for me?
[Miner's bug about IN865.pdf](https://github.com/helium/miner/files/8360174/Miner.s.bug.about.IN865.pdf)

**Comment by xiaoye-x** [comment]
![image](https://user-images.githubusercontent.com/77484115/160340422-2a3af5ea-f47f-4851-b524-04e2c3e9cf5d.png)

**Comment by meowshka** [comment]
@xiaoye-x I'm sorry, but the router doesn't currently support IN865.
