### ISSUE TITLE
0 Witness failed to send witness, max retry

### ISSUE THREAD

**Issue by doganayyonel** [helium/miner#1516]
Hi there
My Browan miner has been almost inactive for 21 days.
When I examine the logs, I witness, but it always fails. Failed to send witness gives max retry error. How can I solve this?

![image](https://user-images.githubusercontent.com/101640919/160630259-3b3ff448-b2e5-4533-99fa-3b42314c98ae.png)

![image](https://user-images.githubusercontent.com/101640919/160630290-6716cb15-4b7e-43d1-8b46-ace9f8318c72.png)

**Comment by meowshka** [comment]
@doganayyonel please contact manufacturer of your hotspot directly regarding this issue.
