### ISSUE TITLE
Eror

### ISSUE THREAD

**Issue by Crisatian** [helium/miner#1522]
.I had this error and was left with 200 blocks a year ago, I gave up and came back, but maybe someone can clarify what it means would be super thank you. ( failed to get peer book. Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.29/containers/fd674192cbe98c3bd673d4f4bab6021577080bef8660f12855ed171e4052df69/exec": context deadline exceede) nem Bobcat 300, Swift Vinyl Badger, Bucharest.

**Comment by jovicailievski** [comment]
I have this exact same error too with my bobcat helium 300. Tried everything Wifi, Lan, Miner reset, resync, fast resync. Ports are forwarded, tested and working. Anyone else with the issue/solution?
This is my hotspot: https://explorer.helium.com/hotspots/112dAtnukzNkBoP4jTCwEGxNWZjXfiQUvr7qfMZEATRY5aVNJs8S

**Comment by Crisatian** [comment]
Am anteles ca, poate sa fie o problema retea, transmitere captare semnal, am vazut ca dabia lai atasat la blokchein, daca este ca la mine, eu iam dat restart adica scos cablu alimentare lasat 1 minut si lam lasat sa se sincronizeze, si a functionat, bafta,

**Comment by meowshka** [comment]
Closing, this issue should no longer be happening. Please start a conversation in the Discussions board if you run into any other problems.
