### ISSUE TITLE
failed to dial proxy server + cannot confirm regulatory domain for miner

### ISSUE THREAD

**Issue by devrisk** [helium/miner#1523]
For past several days im trying to setup pisces P100-868 (868 EU currently being installed in Bulgaria).
![WhatsApp Image 2022-04-03 at 15 03 40](https://user-images.githubusercontent.com/45876191/161427652-afdf8092-bbb9-4b7b-9745-e179bb32e81c.jpeg)
Miner link:
https://explorer.helium.com/hotspots/11JGATajRXqcYLN4Bkf2RH89ZMSQJZVH8JLMgRudL72aS1TUJo5
So far changes that i've made:
- migrated to few locations in order to verify if problem is coming to local ISP. :checkered_flag:
- static ip added + port 44158  forwa
![Capture000](https://user-images.githubusercontent.com/45876191/161427572-f7ea7272-9096-45c7-bb36-b8e86fabb2ab.PNG)
rding (lan port is used) :checkered_flag:
- dashboard update to PiscesQoLDashboard :checkered_flag:
![Capture](https://user-images.githubusercontent.com/45876191/161427565-ed81d1b6-9d27-41ef-b69c-2fbd7d090ead.PNG)

- several clear blockchain data attempts. :checkered_flag:
Miner is starting with **failed to dial proxy server** :warning: ,after that is moving to **cannot confirm regulatory domain for miner** :warning: .I've also notices that logs are running 3h backwards compared to my localtime
I have no clue where is the problem??

:warning: Witness Log is empty so far :warning:
[error_logs.txt](https://github.com/helium/miner/files/8404314/error_logs.txt)
[miner_logs.txt](https://github.com/helium/miner/files/8404315/miner_logs.txt)

**Comment by leonardoagobr** [comment]
hello friend, i bought panther devices and i have exactly the same problem as you.

Did you manage to solve it?

**Comment by meowshka** [comment]
@devrisk please reach out to the manufacturer of your hotspot directly. Here's their discord: https://discord.gg/cBwEUxHcn4
