### ISSUE TITLE
CRC_OK: 0.00%, CRC_FAIL: 0.00%, NO_CRC: 0.00% help me

### ISSUE THREAD

**Issue by doganayyonel** [helium/miner#1524]
Hi there
My logs are always as follows.
What could be the problem?

Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: # PULL_DATA sent: 3 (100.00% acknowledged)

Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: ### [DOWNSTREAM] ###

Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: # PUSH_DATA acknowledged: 100.00%

Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: # PUSH_DATA datagrams sent: 1 (113 bytes)

Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: # RF packets forwarded: 0 (0 bytes)

**Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: # CRC_OK: 0.00%, CRC_FAIL: 0.00%, NO_CRC: 0.00%**

Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: # RF packets received by concentrator: 0

Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: ### [UPSTREAM] ###

Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: ##### 2022-04-04 11:26:32 GMT #####

Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: INFO: [down] PULL_ACK received in 1 ms

Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: INFO: [down] PULL_ACK received in 0 ms

Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: INFO: [down] PULL_ACK received in 0 ms

Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: INFO: [up] PUSH_ACK received in 0 ms

Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: JSON up: {"stat":{"time":"2022-04-04 11:26:02 GMT","rxnb":0,"rxok":0,"rxfw":0,"ackr":100.0,"dwnb":0,"txnb":0}}

Apr  4 14:26:32 MerryIoTHotspotV1D895 packet_forwarder.sh[381]: ##### END #####

**Comment by meowshka** [comment]
@doganayyonel please contact the manufacturer of your hotspot directly regarding this issue.
