### ISSUE TITLE
panther x2 9 days sycning

### ISSUE THREAD

**Issue by giorgiocc** [helium/miner#1580]
already tried to clear data and now I am waiting for fast sync for 8 days. still 300 blocks behind. 
Dashboard Version: 0.2.18
Miner Version: miner-arm64_2022.04.27.0_GA
Panther X Firmware Version: 1.0.4
Panther X SN: HL2EU102S22024FD
included here error logs + miner logs + witness logs +  screenshot

this miner was in morning sunlight for 1 day and goes up to 70 celsius. then I noticed it and changed place.
now it's in good working condition but stays offline after this.

it has syncing endless. sometimes goes behind 200 blocks then still decreasing to 600-700 blocks behind then increasing at 400-200 then still decreasing at 500-700.

Hotspot: old-goldenrod-moose
Hotspot Maker: PantherX
Address: 112KuuayZQzW9UEWST5X896KiK87cDL6ihGuk3VmAyxH4M4HmPYF
Connected to Blockchain: yes
Dialable: yes
Height: 1,330,717
Last Challenge: 2022-04-22 04:36 AM
Firmware: 2022.04.19.0
App Version: 4.0.1
Wi-Fi MAC: 08:E9:F6:79:CA:FC
Eth MAC: 00:16:16:32:CB:90
NAT Type: Symmetric
IP Address: 192.168.1.117
Disk status: ok
Report Generated: 2022-04-28 12:16 PM
Device Info: msmnile | android 30 
https://i.imgur.com/xBgbwlh.png
https://codeshare.io/MNoDln
https://codeshare.io/xvxMNj
https://codeshare.io/qPDMkz

**Comment by hax98** [comment]
same issue here. it also randomly turns off or loop blinking status led or wifi led turns off

**Comment by isa-kz** [comment]
hello, did you find a solution?

**Comment by giorgiocc** [comment]
yes

**Comment by giorgiocc** [comment]
i changed its location also internet provider and synced in like 30
minutes.

**Comment by giorgiocc** [comment]
i changed its location also internet provider and synced in like 30
minutes

**Comment by isa-kz** [comment]
Thanks

**Comment by cokes518** [comment]
Folks, this is not a support channel. If you have questions about your panther hotspot, please reach out to your manufacturer.
