### ISSUE TITLE
 failed to dial "/p2p/11w77YQLhgUt8HUJrMtntGGr97RyXmot1ofs5Ct2ELTmbFoYsQa": timeout dropping 2 packets2022-04-30 11:18:15.479 [error] <0.1943.0>@blockchain_state_channels_client:handle_info:{205,5} failed to dial "/p2p/11w77YQLhgUt8HUJrMtntGGr97RyXmot1ofs5Ct2ELTmbFoYsQa": timeout dropping 2 packets

### ISSUE THREAD

**Issue by Kaktusman2022** [helium/miner#1581]
Hello,

using a Controlino hotspot since 4 weeks, every minute i can see this in the error log:

packets2022-04-30 11:18:15.479 [error] <0.1943.0>@blockchain_state_channels_client:handle_info:{205,5} failed to dial "/p2p/11w77YQLhgUt8HUJrMtntGGr97RyXmot1ofs5Ct2ELTmbFoYsQa": timeout dropping 2 packets2022-04-30 11:18:15.479 [error] <0.1943.0>@blockchain_state_channels_client:handle_info:{205,5} failed to dial "/p2p/11w77YQLhgUt8HUJrMtntGGr97RyXmot1ofs5Ct2ELTmbFoYsQa": timeout dropping 2 packets

**Comment by meowshka** [comment]
@Kaktusman2022 please reach out to Controllino regarding this issue. Here's their discord: https://discord.gg/HCp6wBuhwF
