### ISSUE TITLE
Absolutely no mining activity since light hotspot firmwares started to be released!

### ISSUE THREAD

**Issue by danfu79** [helium/miner#1619]
Helium development Team you must know, and I am sure you are aware of that, you had and have a great responsibility on your shoulders, if I would be you I would work day and night to solve the mess is going on after the miners update for light Hotspot started to be released.
The status is really not acceptable at all and I cannot understand how very few hotspots are still working. Are you releasing to most of us just bugged firmwares or what?

Helium development Team you should be shame of the quality you are delivering!

**Comment by meowshka** [comment]
Closing as duplicate.
