### ISSUE TITLE
Why the denylist is not working?

### ISSUE THREAD

**Issue by danfu79** [helium/miner#1632]
I checked several hotspots in denylist and they are still working better than normal hotspots.
Is the denylist still used?

Here some examples:
Refined Gunmetal Alpaca - id: 112AJtHBbuTgy6FXCJrNKx9r3uR8LwofntNYa3A7DiWiQkE5Dyik 
in denylist but it gained only today HNT 0.318
Shiny Snowy Bull - id: 11neHhrHh97KyYwUrSbU7YXzCYumqhm4j8y1o6k5BZuSVZE4hW2
in denylist but it gained today HNT 0.054 

There are really several cases like those ones.

Great job to ricompensate our cheaters!!!

**Comment by GhostCrackerCoding** [comment]
https://github.com/helium/denylist/issues

**Comment by evanmcc** [comment]
There was initially a misconfiguration of the validators that caused them to ignore the denylist.  This has since been fixed.

**Comment by danfu79** [comment]
There are still 42 validators not up to date, could you force them not to waste our HNT spreading them on the Denylist?

**Comment by danfu79** [comment]
Anyway the issue is not closed and I have examples even today, please act and block them, up to you if to block the validators or act somehow but ro something!
