### ISSUE TITLE
How can I disable blocks syncing

### ISSUE THREAD

**Issue by zxgangandy** [helium/miner#1677]
Hi all:
Are there any config items which can disable the miner syncing blocks?  Cause it need  much network flows everyday. If currently syncing blocks is not necessary, I have to disable that. Please help.

**Comment by meowshka** [comment]
@zxgangandy blockchain sync will be turned off automatically for Light Hotspots, once the transition is complete. Please follow #announcements channel on the Official Helium Community discord for the latests updates on the progress: https://discord.gg/DXUsTAHJ

**Comment by zxgangandy** [comment]
@meowshka  Thanks for ur answer:)
