### ISSUE TITLE
Help me！

### ISSUE THREAD

**Issue by helo112233** [helium/miner#1688]
I re-mirrored my hotspot with SSH, but the animal name and B58 address corresponding to my hotspot have become a new address, and now the hotspot is not working properly, how can I fix it?
The command I used to upgrade the image is shown below.

`docker stop helium-miner && docker rm helium-miner \
docker run -d --init \
--ulimit nofile=64000:64000 \
--env REGION_OVERRIDE=US915 \
--restart always \
--publish 1680:1680/udp \
--publish 44158:44158/tcp \
--name helium-miner \
--mount type=bind,source=/opt/panther-x2/miner_data,target=/var/data \
quay.io/team-helium/miner:miner-arm64_2022.05.19.0_GA`

**Comment by madninja** [comment]
Please contact the maker. Looks like your "re-mirror" is not configured right and is not picking up its keys from the ECC chip
