### ISSUE TITLE
Not able to get my new Pisces P100 registered on Helium Blockchain

### ISSUE THREAD

**Issue by danfu79** [helium/miner#1700]
It is several hours I am trying to register a new Pisces P100 on my wallet and Helium app keep showing "Hotspot added to blockchain: pending".
Here the data about my hotspot:
{pubkey,"11ufJVZ9ap9uugB2Sc8MPAmsmj2K195uiEHUpzxWjGdfK2eFbV2"}.
{animal_name,"fun-obsidian-moth"}.

**Comment by ke6jjj** [comment]
For what it's worth, this hotspot is on the blockchain now, and it appears to have been there since 2022-05-27. Closing.
