### ISSUE TITLE
Every day that passes, worse than the day before

### ISSUE THREAD

**Issue by Mikael1993** [helium/miner#1739]
We open a page here to find out what the real problem is
How long should this new helium problem last?
Every day since May 11, the network has been down
And it gets worse every time with a new update
Friends, by writing a comment here, we can report our problems to Helium Technical Support

**Comment by omidtar** [comment]
دقیقا از 11می همچی بهم ریخت

**Comment by Mikael1993** [comment]
> دقیقا از 11می همچی بهم ریخت
Please write in English

**Comment by omidtar** [comment]
> > دقیقا از 11می همچی بهم ریخت 
> > لطفا انگلیسی بنویسید
It all fell apart on May 11th
