### ISSUE TITLE
LPWAN Frequency for Pakistan

### ISSUE THREAD

**Issue by iwebconsultants** [helium/miner#1741]
[iot_srd_regulatory_framework_01-06-2022.pdf](https://github.com/helium/miner/files/8883393/iot_srd_regulatory_framework_01-06-2022.pdf)
Hi Team, 

Pakistan Telecommunication Authority has recently announced LPWAN frequency bands for Pakistan, which are 433.05 - 434.79 MHz and  920 - 925 MHz. So the LoRaWAN frequency plans can be EU433 or AS923. Details of the regulatory framework official copy can be found at following link:

https://www.pta.gov.pk/assets/media/iot_srd_regulatory_framework_01-06-2022.pdf

Can we please update the information according above changes.

Appreciate your support. 

Regards, 

Azam

**Comment by mikev** [comment]
AS923-1 deployed
