### ISSUE TITLE
Unstake NOT WORKING

### ISSUE THREAD

**Issue by tsouza** [helium/miner#1812]
Please someone help me. My wallet address is `14NvSPHti6K32U6Lven9XMkPEusRfog8jYtUACgm3hqgaPenwyY`  I have performed unstake and transaction is `ySXXsHtZHLo15khyfkEhvVOYGxXb_fT_odQRz3XsLq0`. The stake height release is `1498909` and at this moment the block height is already `1503114` but when I access the api https://api.helium.io/v1/accounts/14NvSPHti6K32U6Lven9XMkPEusRfog8jYtUACgm3hqgaPenwyY it still says that value is staked. I checked the ledger and it also says it's 10k staked. How can it still be staked if stake release height has already passed?!?!?!?! 

I tried to withdraw the funds and it's stuck

The unstake transaction https://api.helium.io/v1/transactions/ySXXsHtZHLo15khyfkEhvVOYGxXb_fT_odQRz3XsLq0

Here says `Stake Released`, but Stake **HAS NOT BEEN RELEASED**. https://explorer.helium.com/txns/ySXXsHtZHLo15khyfkEhvVOYGxXb_fT_odQRz3XsLq0

**Comment by Vagabond** [comment]
What happens when you try to withdraw the funds? From what I can see it looks like the unstake worked.

**Comment by Vagabond** [comment]
Here's your account balance at two ledger heights, which shows you have 10k in your account you did not before:

```
(val2_miner@127.0.0.1)6> blockchain:height(blockchain_worker:blockchain()).                         {ok,1481829}
(val2_miner@127.0.0.1)7> blockchain_ledger_v1:find_entry(libp2p_crypto:b58_to_bin("14NvSPHti6K32U6Lven9XMkPEusRfog8jYtUACgm3hqgaPenwyY"), blockchain:ledger()).
{ok,#blockchain_ledger_entry_v2_pb{nonce = 22,
                                   hnt_balance = 84459594,hst_balance = 0,mobile_balance = 0,
                                   iot_balance = 0}}
```

```
(blockchain_etl@127.0.0.1)9> blockchain:height(blockchain_worker:blockchain()).
{ok,1503533}
(blockchain_etl@127.0.0.1)10> blockchain_ledger_v1:find_entry(libp2p_crypto:b58_to_bin("14NvSPHti6K32U6Lven9XMkPEusRfog8jYtUACgm3hqgaPenwyY"), blockchain:ledger()).
{ok,#blockchain_ledger_entry_v2_pb{nonce = 23,
                                   hnt_balance = 1000078599695,hst_balance = 0,
                                   mobile_balance = 0,iot_balance = 0}}
```

**Comment by tsouza** [comment]
Hi @Vagabond, thanks for replying. After some help from devs in discord channel it was told me that this is an issue that happens some times and making a payment to/from the account solves the issue. I just did it and HNT has been unstaked.

We can close this.
