### ISSUE TITLE
Pakistan - AS923-1 deployed

### ISSUE THREAD

**Issue by iwebconsultants** [helium/miner#1825]
AS923-1 deployed

_Originally posted by @mikev in https://github.com/helium/router/issues/804#issuecomment-1216910400_

Hi @mikev, 

Thank you for following it up, I can see that the Frequency has been updated on the Helium Regional Frequency Page: https://docs.helium.com/lorawan-on-helium/frequency-plans/

However, it seems that all the Miners are still auto updating frequency to IN865. 

Is there a quick fix to this?

Appreciate your support, 

Regards, 

Azam

**Comment by iwebconsultants** [comment]
Just found my answer: https://github.com/helium/miner/issues/1791

How long will it take for chainvar to update?

**Comment by mikev** [comment]
The chainvar was updated Nov 17th.  Pakistan should be AS923 now.
