### ISSUE TITLE
Why is This Hotspot Fit Aqua Swan on the Denylist?

### ISSUE THREAD

**Issue by 00crazyman00** [helium/miner#1857]
Hello,

@6CornerDefender
can you explain me, why this miner is still on the denylist?
Furthermore, the submissions 57.58 on Crowdspot.io were declined!
Why??

**Comment by 00crazyman00** [comment]
#8228

**Comment by abhay** [comment]
This is not the denylist repo. https://github.com/helium/denylist#removal-from-this-list
