### ISSUE TITLE
JSONRPC and functions outdated

### ISSUE THREAD

**Issue by fredsco** [helium/miner#1872]
Please update the miner_jsonrpc_info.erl and its functions. 

miner_summary does not work anymore. Probably there are still some functions from older miner versions. (e.g pre light hotspot and P2P disabling.

**Comment by fredsco** [comment]
@madninja Please have a look.

**Comment by madninja** [comment]
@fredsco since the erlang miner is going away in the next month or so, I don't think we'll be fixing this
