### ISSUE TITLE
[Removal]: Please remove Sour Tiger Parrot

### ISSUE THREAD

**Issue by Shade91** [helium/miner#1883]
My miner is on the Denylist and I dont know why?
Can it be removed from this list and how? Does anyone know?

Unless it flew from my roof I believe it is still there since it's showing online in my app and on the helium explorer page.

Thanks in advance for reading and replying with instructions!

Greetings

**Comment by abhay** [comment]
This is not the denylist repo. https://docs.helium.com/mine-hnt/denylist
