### ISSUE TITLE
Remove from DenyList

### ISSUE THREAD

**Issue by Lebanese77** [helium/miner#1884]
good morning,
I found 5 devices on my network on denylist, I don't know what is the issue since I installed them a year before, 
could you help in this issue?
Polished Golden Antelope, Scruffy Mocha Osprey, Muscular Blush Orca, Fit Menthol Hedgehog, Cold Brunette Mockingbird, 
thank you

**Comment by jmarcelino** [comment]
This is the wrong place for that, submit a request to https://docs.helium.com/mine-hnt/crowdspot/#submit-a-removal-request instead
