### ISSUE TITLE
RAK MNTD Helium mining issue

### ISSUE THREAD

**Issue by gcoello27** [helium/miner#1916]
I have a RAK MNTD I just purchased, but the diagnostics continue to say no outbound or inbound. I see there’s another miner with the same name as mine which is Raspy Leather Whale. How can I fix it to make sure it syncs and starts mining?

**Comment by jmarcelino** [comment]
Hi @gcoello27 this is neither the right way to ask for support not the right software.

All miners on Helium since the migration to OpenLNS use gateway-rs and this package no longer needs to sync with the blockchain so the diagnostics are correct, you hotspot should be working fine

**Comment by gcoello27** [comment]
I apologize. So does that mean I just have to wait before it starts mining?Sent from my iPhoneOn Jun 10, 2023, at 3:06 PM, Jose Marcelino ***@***.***> wrote:﻿
Hi @gcoello27 this is not the neither the right way to ask for support not the right software.
All miners on Helium since the migration to OpenLNS use gateway-rs and this package no longer needs to sync with the blockchain so the diagnostics are correct
