### ISSUE TITLE
Does miner take a long time to restart?

### ISSUE THREAD

**Issue by jdhoch** [helium/miner#442]
I installed the miner on AWS.  When I issue the command **docker exec miner miner info height** I get the following response:
_**Error response from daemon: Container XXXXXXXXXXXXXXXXXXX is restarting, wait until the container is running**_

Its been several hours already

**Comment by lthiery** [comment]
I can take 10-30 seconds to restart sometimes, but not 10-30 hours! You're most likely in some kind of crash loop.

Are you running the most recent image from quay?

Can you remove the image (`docker stop miner && docker rm miner`) and do the run command again, but this time, remove `-d` and `--restart always`. The shell will give you some output which you can share here.

**Comment by jdhoch** [comment]
Was this really built on Ubuntu 20.04? AWS is offering version 18.04, not 20.04. Do I need to upgrade Ubuntu first?

**Comment by jdhoch** [comment]
So, I was able to get it going by using AWS EC2 instead of LightSail.

Now, if I run the print_keys command I see my public key. **How do I see my private key?**

**Comment by Wheaties466** [comment]
I am trying to run the miner on a raspberry pi with docker. Using the arm64 0624 GA build and I’m getting the same thing. In the logs it mentions something from go.

Has there been any fix for this? I can try an older image to see if that works.

**Comment by fvasquez** [comment]
> I am trying to run the miner on a raspberry pi with docker. Using the arm64 0624 GA build and I’m getting the same thing. In the logs it mentions something from go.

@Wheaties466 
Are you sure you pulled the arm64 image and not the amd64 image?
Are you running the 64-bit version of Ubuntu 20.04 LTS on your Raspberry Pi 3/4?

> Has there been any fix for this? I can try an older image to see if that works.

Older Docker images have worked on the Raspberry Pi 3/4 in the past but I haven't tested any recent arm64 images recently. They could be miscompiled. I am tagging the `2020.07.02.0_GA` release now so you can try that when it's done building.

**Comment by Wheaties466** [comment]
@fvasquez looks like im getting the same error on the 07.02 build

`pi@rak-gateway:~ $ sudo docker logs --tail 50 --follow miner
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
`

**Comment by fvasquez** [comment]
> raspberry pi 3 with the stock image it comes with.

The arm64 Docker image is built for 64-bit ARM. It will not work on Raspbian which is the image that comes with your RAK  gateway.

Make a microSD with Ubuntu 20.04 LTS (Pi 3/4). Make sure to get the 64-bit server OS version for arm64 architectures. The 32-bit server version for armhf architectures will not work.

https://ubuntu.com/blog/ubuntu-20-04-lts-is-certified-for-the-raspberry-pi

Those are the first steps to getting our Docker image running on a Pi 3/4.

**Comment by Wheaties466** [comment]
Thank you sir, that was the answer to my question.

**Comment by fvasquez** [comment]
Users have been reporting success running miner in docker containers.
