### ISSUE TITLE
can this work on a raspian rasperry pi

### ISSUE THREAD

**Issue by mantoles** [helium/miner#514]
I tried to install it on rasperry pi running raspian and I get the following error.

pi@raspberrypi:~/miner $ make
./rebar3 compile
./rebar3: error while loading shared libraries: /lib/arm-linux-gnueabihf/libtinfo.so.5: invalid ELF header
make: *** [Makefile:17: compile] Error 127
pi@raspberrypi:~/miner $ sudo apt-get /lib/arm-linux-gnueabihf
E: Invalid operation /lib/arm-linux-gnueabihf

can anyone advice how to fix this?

**Comment by fvasquez** [comment]
Why? Just use the latest prebuilt Docker image if you want to run miner on a Raspberry Pi 3 or 4.

https://developer.helium.com/blockchain/run-your-own-miner
