### ISSUE TITLE
OTP 23 + rebar3 3.14

### ISSUE THREAD

**Issue by evanmcc** [helium/miner#567]
It's about time to start moving towards OTP 23, and rebar3 3.14 makes a lot of changes to how the scripts run, so we need to spend some time updating clique and our stuff to make all this work.  Some of the work has already been done.

**Comment by evanmcc** [comment]
rebar3 3.14 condenses the rpc and rpcterms path, which will change how the extension scripts will need to be written.

the current code looks like: 
```
relx_nodetool rpc miner_console command info $@
```

and will need to look like:
```
relx_nodetool rpc miner_console command '["info", "arg1", "arg2"]'
```

this doesn't seem to be super simple to do in bash, but we'll need to figure it out.

**Comment by Vagabond** [comment]
```sh
  #!/bin/sh

  j=1
  l=$#
  buf="'["
  while [ $j -le $l ]; do
      buf="$buf\"$1\","
      j=$(( j + 1 ))
      shift
  done

  buf="${buf%?}]'"
  echo $buf
```

```
$ ./fmt.sh hello world how are you 
'["hello","world","how","are","you"]'
```

like this? this is in posix sh

**Comment by Vagabond** [comment]
Example for the `peer` command from blockchain core:

```sh
  #!/bin/sh
  if [ -t 0 ] ; then
      export CLIQUE_COLUMNS=`stty size 2>/dev/null | cut -d ' ' -f 2`
  fi

  j=1
  l=$#
  buf="[[\"peer\","
  while [ $j -le $l ]; do
      buf="$buf\"$1\","
      j=$(( j + 1 ))
      shift
  done

  buf="${buf%?}]]"

  relx_nodetool rpc blockchain_console command $buf
  exit $?
```

**Comment by Vagabond** [comment]
I think we can template this file by just replacing `peer` on line 9 with a template variable and using rebar's templated file stuff.

**Comment by evanmcc** [comment]
done
