### ISSUE TITLE
Miner cli comand miner ledger gateways fails

### ISSUE THREAD

**Issue by maco2035** [helium/miner#620]
The current miner command miner ledger gateways fails to do anything. It will throw the following error: RPC to 'miner@127.0.0.1' failed: timeout.

I suspect this is due to the shear amount of active gateways on the networks. I have tried this on 4 different docker containers on AWS t2.medium, and Digital Ocean smallest droplet, Linode 2nd cheapest plan, and on my personal computer. They all throw the same error. I believe it has to do something with the docker container and the hotspots being under powered.

**Comment by maco2035** [comment]
This issue may belong into the blockchain-core. As ledger is a function of the blockchain-core, then the miner.

**Comment by evanmcc** [comment]
The code that this points to does indeed live in blockchain-core.  That said, it works fine for me, both on our AWS machines (t2.large) and my personal laptop (i7 mbp).

**Comment by maco2035** [comment]
I think smaller instances will crash the blockchain with it. With bigger and bigger instances it will be fine. Just a matter of what the system size is.

**Comment by evanmcc** [comment]
let me poke at it this afternoon, I can probably make it a bit faster/lower memory.

**Comment by lthiery** [comment]
I’ve seen this quite a bit on low end machines or “difficult” CLI commands. For example, loading a snapshot on a RPi often results in this even though, if you monitor the logs, the snapshot does successfully get applied eventually.

It could be “solved” maybe by enabling timeouts to be configurable with sys.config?

**Comment by maco2035** [comment]
@lthiery I think this might be the case, the miners do slow down with such heavy loads in on the blockchain-core, however I think the timeouts could be tweaked is what I am going to go try, if it works. Then there will be only need to change longer timeout periods in all the sys.config.

**Comment by evanmcc** [comment]
The timeout is a shell variable currently. `NODETOOL_TIMEOUT=120000 miner ledger gateways` should give you two minutes, for example.  this will likely change in a few months.

**Comment by evanmcc** [comment]
https://github.com/helium/blockchain-core/pull/732
before:
```~/src/miner3$ time _build/dev/rel/miner/bin/miner ledger gateways > /dev/null 

real	0m11.278s
user	0m1.424s
sys	0m0.391s
```
after:
```
:~/src/miner3$ time _build/dev/rel/miner/bin/miner ledger gateways  > /dev/null 

real	0m6.350s
user	0m1.576s
sys	0m0.477s
```

**Comment by maco2035** [comment]
@evanmcc Well that did speed it up a ton. The slow computers will do way better with those changes as this list is only going to get bigger in the future.

**Comment by maco2035** [comment]
@evanmcc @lthiery I am going to mark this as done! Thanks for the help. Speed everything up.
