### ISSUE TITLE
Update Staking Keys for Nebra

### ISSUE THREAD

**Issue by cokes518** [helium/miner#621]
Remove the old Helium staking key `14fzfjFcHpDR1rTH8BNPvSi5dKBbgxaDnmsVPbCjuq9ENjpZbxh`
Add NEW staking key (Nebra Ltd) `13Zni1he7KY9pUmkXMhEhTwfUpL9AcEV1m2UbbvFsrU9QPTMgE3`

**Comment by abhay** [comment]
@cokes518  Have we set any expectations on when Nebra would like to start testing real onboarding? 

FYI: @vihu @evanmcc @Vagabond  on a needed chain var change

**Comment by ryanteck** [comment]
> @cokes518 Have we set any expectations on when Nebra would like to start testing real onboarding?

As soon as possible :)

I have one unit that I'd ideally like to get setup this week. While I keep my other unit with test onboarding for now.

**Comment by ryanteck** [comment]
@abhay Is there anything we need to do to help out with this?

**Comment by vihu** [comment]
https://github.com/helium/miner/pull/623
