### ISSUE TITLE
Macedonia Frequency

### ISSUE THREAD

**Issue by timtamothee** [helium/miner#633]
From the LoRaWAN Regional Parameters guidelines, it looks like Macedonia uses the EU863-870 frequency. Can this be checked to add it to the supported frequencies? https://lora-alliance.org/wp-content/uploads/2020/11/rp_2-1.0.1.pdf. Thanks.

**Comment by waveform06** [comment]
Its officially called North Macedonia now
https://en.wikipedia.org/wiki/North_Macedonia

**Comment by babalonqe** [comment]
Hope  it will be possible in north macedonie to place hotspots and earn hnt

**Comment by babalonqe** [comment]
So will it be possible to place hotspots in north macedonia and earn hnt

**Comment by waveform06** [comment]
We confirmed this as a yes 2 days ago

**Comment by babalonqe** [comment]
Ok great thanks you

Op za 13 feb. 2021 23:56 schreef waveform06 <notifications@github.com>:

**Comment by evanmcc** [comment]
fixed in https://github.com/helium/miner/pull/640
