### ISSUE TITLE
Broken Link: https://docs.helium.com/blockchain/run-your-own-miner returns a 404

### ISSUE THREAD

**Issue by NetScr1be** [helium/miner#634]
Don't know if this is the right channel for this. If not, my apologies and please direct me accordingly.

The [github readme.md for building a miner](https://github.com/helium/miner#installing-miner-from-source), in the paragraph 'miner step-by-step' has a line:

> This is for development purposes only and if you are interested in running a miner, please follow our guide [here](https://docs.helium.com/blockchain/run-your-own-miner).

With 'here' linking to https://docs.helium.com/blockchain/run-your-own-miner which returns a 404

**Comment by kent-williams** [comment]
Thanks @NetScr1be, PR fix up #635
