### ISSUE TITLE
Update staking keys for Syncrobit

### ISSUE THREAD

**Issue by cokes518** [helium/miner#645]
ADD new maker (Syncrob.it):
`14rb2UcfS9U89QmKswpZpjRCUVCVu1haSyqyGY486EvsYtvdJmR`

**Comment by chineselegend** [comment]
I approve this change with my non existing power

**Comment by abhay** [comment]
addressed in https://github.com/helium/miner/commit/5a8f34d481768f343877900ab50e8697fc7103af
