### ISSUE TITLE
Bump deps

### ISSUE THREAD

**Issue by JayKickliter** [helium/miner#650]
The following deps have build-system improvements for macOS builds and OTP23 support

- [ ] https://github.com/helium/erlang-pbc
- [ ] https://github.com/helium/erlang-erasure
- [ ] https://github.com/helium/ebus

These deps have outstanding issues:

- [ ] https://gitlab.com/barrel-db/erlang-rocksdb/-/issues/118

**Comment by evanmcc** [comment]
This is done other than horror related to erocks that will take some time to resolve.
