### ISSUE TITLE
make release fails with Error 1

### ISSUE THREAD

**Issue by joshhamon** [helium/miner#668]
_Early in make release I see:_

===> Compiling erlang_pbc
CMake Error at cmake/FindPBC.cmake:39 (target_include_directories):
  Cannot specify include directories for imported target "PBC::PBC".
Call Stack (most recent call first):
  CMakeLists.txt:104 (find_package)

CMake Error at cmake/FindPBC.cmake:47 (target_link_libraries):
  Cannot specify link libraries for target "PBC::PBC" which is not built by
  this project.
Call Stack (most recent call first):
  CMakeLists.txt:104 (find_package)

-- Configuring incomplete, errors occurred!
See also "/root/miner/_build/default/lib/erlang_pbc/_build/c_src/CMakeFiles/CMakeOutput.log".
===> Hook for compile failed!

Makefile:32: recipe for target 'release' failed
make: *** [release] Error 1

_What is Error 1?_

**Comment by Vagabond** [comment]
My guess is there's an earlier error that's more helpful. Do you have libgmp and its development headers installed?

**Comment by joshhamon** [comment]
apt-get install libgmp-dev is up to date.  I added in libgmp3-dev but no dice. I am not seeing an earlier error from my initial make release

**Comment by evanmcc** [comment]
what version of CMake do you have?  you'll need to update past 3.10.x if you're on ubuntu 18.04.

**Comment by joshhamon** [comment]
3.10.2-1ubuntu2.18.04.1 is what I'm running but it's not updating/upgrading

**Comment by joshhamon** [comment]
For those encountering this: 
wget https://github.com/Kitware/CMake/releases/download/v3.19.6/cmake-3.19.6.tar.gz
tar the file 
cd cmake*
per the README ./bootstrap && make && sudo make install
