### ISSUE TITLE
testnet: helium-wallet info, balance 10005, right after staking

### ISSUE THREAD

**Issue by fydela** [helium/miner#671]
Like others, I noticed that the initial balance in the wallet is 10005 (after staking) and should be zero? Potential for someone to unstake at that point and get 10005 TNT for doing nothing? concern?

**Comment by evanmcc** [comment]
I haven't been able to reproduce this, sorry.  let me know if it happens again.

**Comment by fydela** [comment]
Balance (still) shows 10005 even though processing blocks 840 and continuing, running v0.1.12. I probably toke a wrong turn somewhere when creating the latest validator build. Thanks.

helium-wallet info
+--------------------+-----------------------------------------------------+
| Key                | Value                                               |
+--------------------+-----------------------------------------------------+
| Address            | 1aKRTAsiA5gDMC4P32JYXUe7RrvRdAKYTFW49RkUVuFBHUL5ycB |
+--------------------+-----------------------------------------------------+
| Network            | testnet                                             |
+--------------------+-----------------------------------------------------+
| Type               | ed25519                                             |
+--------------------+-----------------------------------------------------+
| Sharded            | false                                               |
+--------------------+-----------------------------------------------------+
| PwHash             | Argon2id13                                          |
+--------------------+-----------------------------------------------------+
| Balance            | 10005.00000000                                      |
+--------------------+-----------------------------------------------------+
| DC Balance         | 0                                                   |
+--------------------+-----------------------------------------------------+
| Securities Balance | 0.00000000                                          |
+--------------------+-----------------------------------------------------+
