### ISSUE TITLE
Missing LoraWAN support code frequency for my country, Uganda.

### ISSUE THREAD

**Issue by ignited2021** [helium/miner#677]
According to the information provided by Lora alliance org on the list of countries with supported frequencies for LoraWan My country (Uganda) is among and lies within this range of frequency; 923 - 925 MHz plus 863 - 865 MHz,
865-867.6 MHz, 869.25 - 869.7 MHz; with these support codes (EU433 and AS923). I would like to start mining Helium (HNT) in Uganda However I'm not sure whether the frequencies in Uganda will be compatible with the LoRaWAN devices. The Github list does not show whether Uganda frequency ranges support the Helium network in Uganda in case I buy/order/ship my the devices to Uganda and connect them will they work? Plus I see that my country shares the same codes on the Lora alliance org with many other countries like Hong Kong, UK, Thailand, that are currently mining Helium but on your list Uganda's information is not matching that on Lora alliance org. Could you please crosscheck for me the frequency to confirm if I can mine Helium in Uganda using the current mining LoRaWAN devices within those radio frequency ranges in Uganda as per Lora alliance organization list of supported countries.

**Comment by timtamothee** [comment]
Hi @ignited2021, can you please provide the documentation that you found from the LoRa Alliance site for Uganda's supported LoRaWAN frequency for reference? This can help others cross-reference before approving a supported frequency. Thanks.

**Comment by shawaj** [comment]
I believe based on the document linked in https://github.com/helium/miner/pull/663 the correct frequency for Uganda is EU868

**Comment by jmarcelino** [comment]
According to RP002-1.0.1 the LoRa Alliance is recommending IN865 for Uganda and this is supported by the Uganda Communications Commission https://www.ucc.co.ug/wp-content/uploads/2017/09/Technical-Requirements-for-operation-of-868.docx.pdf

From that document you can also see that in Uganda there is a condition that "Any gateways or base stations deployed shall have to be registered with UCC."

**Comment by shawaj** [comment]
@jmarcelino ah yes, the LoRa doc does suggest in865. I must have made an error whilst translating that to the CSV.

However, the UCC document you linked doesn't seem to support the frequency ranges mentioned in the lora doc and seems to allow eu868 as well.

And since Kenya, Rwanda, Burundi, Zambia all use eu868 it seems to make more sense to use eu868 than in865 in this case, IMO.

**Comment by jmarcelino** [comment]
From the UCC document I linked you can see that you must stay within 865-868Mhz to operate with a 1% duty cycle with bandwidths > 100 kHz. Outside of range the device must maintain 0.1% duty cycle.

This is not compatible with EU868 hence the LoRa Alliance quite wisely assigned Uganda to IN865.

**Comment by shawaj** [comment]
@jmarcelino it also says you can use 868-868.6 MHz ≤ 1% duty cycle with no restriction on bandwidth. So eu868 is also allowed it seems.

**Comment by jmarcelino** [comment]
No, 868-868.6 MHz is not enough to meet the EU868 requirements sorry.

**Comment by shawaj** [comment]
I guess you missed the last row of the table

**Comment by jmarcelino** [comment]
I believe you missed the "869.4-869.65MHz ≤ 25kHz" bandwidth requirement when reading that last row.
Default RX2 frequency for EU868 is 869.525 MHz at 125kHz

**Comment by shawaj** [comment]
That's a default, not a strict requirement for eu868. The strict requirements are indicated by "SHALL" in the lora doc AFAIK (i.e. the three main channels 868.1, 868.3 and 868.5)

**Comment by ignited2021** [comment]
Thanks for your response/help. So can I now confidently take IN865 as the
supported frequency for Uganda instead of EU868 or both can be supported?

**Comment by jmarcelino** [comment]
Yes you can change it, there is no argument to override the LoRa Alliance here and maintaining country specific default RX2 frequencies would be madness. Thanks.

**Comment by shawaj** [comment]
@jmarcelino sure, but EU868 is still a valid frequency plan for Uganda based on the LoRa alliance specification doc, albeit not if you are using the default RX2 value. That was my point.

In any case, #705 updates the frequency to IN865. I'll go through the doc again to ensure no other errors were introduced while copying the data. If you spot any others, give me a shout.

cc @ignited2021

**Comment by Ndikabona** [comment]
I want to start mining helium in Kampala can someone help me
