### ISSUE TITLE
Validators - unstake transactions should include amount

### ISSUE THREAD

**Issue by PaulVMo** [helium/miner#688]
I believe that the unstake transaction should include the amount that is being unstaked. 

First, with the potential for overstake at some point in the future, this may be required if partial unstake is also enabled. Adding the amount now would allow this transaction to be compatible with the potential future functionality and void an unstake v2 transaction.

Second and more important, this is needed from an accounting perspective for wallet owners. Currently, there is no account activity record that corresponds to a stake being returned to a wallet. The 'stake' transaction includes an amount and the amount leads to a direct reduction in the available account balance decreasing. However, when unstaking, there is no corresponding transaction/activity (with an amount) that indicates the stake being returned to the account balance. 

Put another way, it is not possible to derive the account balance by looking solely by looking at transactions for that account.
Technically, this can be derived from looking back at the original transaction for the amount as well as the cooldown period in the chain vars. However, this adds a lot of complexity when it comes to accounting or tax report in order to be able to track account balance at any given time.

Furthermore on the accounting point, it might even require adding another transaction type that is generated at the time that the cooldown period ends and the stake is put back in the account's available balance. There are technically three transition that occur but only two transaction types:
1. Not staked to Staked (the current stake transaction)
2. Staked to Cooldown (the current unstake transaction, although it doesn't include amount)
3. Cooldown to not staked (no corresponding transaction)

**Comment by evanmcc** [comment]
added
