### ISSUE TITLE
Validators - allow transfer to new owner with same validator address

### ISSUE THREAD

**Issue by PaulVMo** [helium/miner#689]
The transfer stake transaction should support transferring the stake to a new owner while maintaining the existing validator address. A stake owner may want to transfer their stake to a different owner without needing to change the validator. There is a straightforward workaround of regenerating the swarm_key and restarting the validator so this is a convenience rather than a must have.

Currently, a transfer stake transaction is considered invalid anytime the old address equals the new address. I believe the logic should be changed to also considered whether the new owner does not equal the old owner.

**Comment by evanmcc** [comment]
Sorry, I don't agree.  Generating a new key is too easy, and there will never be a guarantee that the old owner didn't keep a copy of the old key.
