### ISSUE TITLE
Validators - transfer stake transaction should include stake amount transferred

### ISSUE THREAD

**Issue by PaulVMo** [helium/miner#690]
I believe that the transfer stake transaction should include the amount of stake being transferred.

First, with the potential for overstake at some point in the future, this may be required if partial transfer is also enabled. Adding the amount now would allow this transaction to be compatible with the potential future functionality and void a transfer v2 transaction.

Second and more important, this is needed from an accounting perspective for wallet owners. Without the stake amount included in the transfer transaction, the transaction history does not correspond to the change in stake balance for the account.

Put another way, it is not possible to derive the staked balance at a point in time by looking solely by looking at transactions for that account. Technically, this can be inferred from looking back at the original transaction for the amount. However, this adds a lot of complexity when it comes to accounting or tax reporting in order to be able to track account balance at any given time.

**Comment by evanmcc** [comment]
added
