### ISSUE TITLE
Validators - allow transfer stake during cooldown

### ISSUE THREAD

**Issue by PaulVMo** [helium/miner#691]
Given the long cooldown period proposed for stakes, there may be demand for the option to transfer a stake while it is in the cooldown period. Currently, as soon as a validator is unstaked, the owner is locked into waiting for the stake to complete the cooldown period. Owners may desire to have the flexibility to sell the cooling stake.

This may also require a new transaction type or new attribute of a transfer stake transaction to ensure that the new owner has certainty as to whether they are accepting an active versus cooling stake. If not, it may be used for malicious purposes. For example, if someone agrees to sell and transfer an active stake; they could initiate the transfer, send the partially signed transaction to the new owner for signing and submitting, but in the mean time unstake. The transfer would still go through although the new owner may be expecting it to be an active stake.

**Comment by evanmcc** [comment]
My initial response here is: "just try harder to sell it first".  I'm almost certain that it's not worth the added complexity, especially as the cooldown period is likely to be reduced as the validator network grows in size.

**Comment by jdgemm** [comment]
I agree, there's a lot of added complexity and it's not something we should try to address for our mvp.
