### ISSUE TITLE
Validator - miner peer book -s showing listen address that is not on device

### ISSUE THREAD

**Issue by ericjohncarlson** [helium/miner#694]
Version: 0.1.20.

When checking status of  with `miner peer book -s`, a second IP address that is not related to the validator is listed as a peer address.

```+----------------------------------------------+---------------+----------+---------+---+----------+
|                   address                    |     name      |listen_add|connectio|nat|last_updat|
+----------------------------------------------+---------------+----------+---------+---+----------+
|/p2p/1Za3L1R32qPJJ546kteo7WP9t2DzWtTMw5u9jKfpJ|magic-caramel-s|    2     |    8    |non| 120.272s |
+----------------------------------------------+---------------+----------+---------+---+----------+

+----------------------------+
| listen_addrs (prioritized) |
+----------------------------+
|/ip4/158.69.118.209/tcp/2154|
|/ip4/75.119.137.119/tcp/2154|
+----------------------------+
```

In this example, the top IP address is of the validator where this command is being run.  The lower IP address is a public IP address of a different validator completely.

**Comment by Vagabond** [comment]
Thanks for the report! Are you aware of any relationship you have to that second IP?

**Comment by ericjohncarlson** [comment]
> Thanks for the report! Are you aware of any relationship you have to that second IP?

I have no known relationship with that IP.  I can see that it's in Germany, a different ISP/provider with no relationship with my colo (OVH/so-you-start) in Canada.  When I perform a `netstat -an` to view any connections, that IP does not show up in the list of peer connections (or any other connection)

I also restarted the validator, and it at first didn't appear as a listen address, and now the same 2 listen addresses are being shown again.

**Comment by lthiery** [comment]
FWIW, when I connect to that IP, I get the following:

```
/ip4/172.17.0.2/t|/ip4/75.119.137.119/|/p2p/1Z48rp3Dh7cNysevEAR5f3DfYti5BHEqt21r|slow-opaque-shark
```

Is this a relay being displayed weird?

**Comment by ericjohncarlson** [comment]
It's definitely a validator. You can telnet to port 2154 and see output.  So it has a direct connection as well.

**Comment by fydela** [comment]
I am seeing this same issue. My validator is running in Linode (Fremont CA) yet listen_addrs shows that exact second address /ip4/75.119.137.119/tcp/2154. Validator seems okay, chucking along, joining CG and etc.

**Comment by Vagabond** [comment]
Yeah, I have some ideas what's going on and will be looking into it.

**Comment by fydela** [comment]
Thank you. Let me know if you need more details to this intermittent (?) problem.

**Comment by sgerov** [comment]
hey, the owner of that second node (75.119.137.119) here. I'm trying out different networking configurations and lose access from the outside to the node in the meantime hence it becomes a relay. Let me know if I can help with anything

**Comment by jackoat** [comment]
I also have 2 IP addresses with the exception that the the "other" ip is prioritized.
---------------------------------------------+----------------+----------+---------+---+----------+
|                   address                   |      name      |listen_add|connectio|nat|last_updat|
+---------------------------------------------+----------------+----------+---------+---+----------+
|/p2p/1YwmtSs9588SSLcqA2J2k7tB7XHE8NGhYHaie9SG|daring-bronze-co|    2     |    3    |non| 184.414s |
+---------------------------------------------+----------------+----------+---------+---+----------+

+----------------------------+
| listen_addrs (prioritized) |
+----------------------------+
|/ip4/75.119.137.119/tcp/2154|
|/ip4/99.250.95.204/tcp/2154 |
+----------------------------+

**Comment by kylemanna** [comment]
I'm observed this as well on my validator running `0.1.35` where the second IP (not mine) is `158.69.118.209`

It also appears in the API when querying @  https://testnet-api.helium.wtf/v1/validators/

**Comment by kylemanna** [comment]
Seem unusual that 13 validators have `158.69.118.209` listed as a `listen_addrs`.  My validator has no relationship with that IP address.

```
$ jq <validators-with-158.69.118.209-listener.json '. | length'
13
```

JSON dumps @ https://gist.github.com/ead0827a6ff190f3eb5fb400a9417ba0

**Comment by snip** [comment]
I'm also experiencing this with validator 0.1.39 with a second IP which has nothing to do with me.
Explorer is showing country switched ... (crossed the ocean faster than the light).
This is occurring during time i was in the consensus group.

**Comment by derjohn** [comment]
Hello,
is there a way to disable the validator's own-ip-autodiscovery, like setting it with an ENV var? Or in the config file? In my particular case I'm running the validator as a pod in kubernetes and the usual way to make external access is the ingress controller.
The only way I found to make it work, was to set an external IP to the pod/container .... which is what you usually don't want. So: Setting an "inbound ip address" would help. (I can also think that miners behind vpn gateway would need such a feature).

rgds,
j

**Comment by derjohn** [comment]
Self-Reply: It's the env var NAT_EXTERNAL_IP
