### ISSUE TITLE
Validator - add --json output for all miner commands

### ISSUE THREAD

**Issue by ericjohncarlson** [helium/miner#699]
There's great incentive for both helium and the validator "owner" to have performant validators.  The commands coming out of the miner app are valuable, but all the output is formatted for the screen, not system consumption.  

Being able to force a `--json` output on locally run commands would allow data collection at the validator for concensus status, hbbft group performance, miner versioning verifications as well as other metrics.  

I recognize that some/most of this is available via the helium apis for validators, but my polling frequency may be above what you want on the APIs and this may help reduce load on the APIs.  Not to mention being able to gather and compare data from both the validator and the API.

**Comment by evanmcc** [comment]
csv works right now, I'll see what json needs to work
` ./_build/validator/rel/miner/bin/miner hbbft perf --format=csv`

**Comment by evanmcc** [comment]
also, in the future, we plan to add some gRPC interfaces to stream some of this stuff, so let us know what you'd like to see there.  I already have a request for a stream of txns as they're applied.

**Comment by evanmcc** [comment]
This should be resolved by the JSONRPC API.  Please file other issues for specific deficits.
