### ISSUE TITLE
Local and Remote validator monitoring

### ISSUE THREAD

**Issue by evanmcc** [helium/miner#710]
This issue is for tracking community requests around local and remote monitoring for validators.  Please leave comments here letting us know what you'd be interesting in monitoring or asking questions about what you need to understand better in order to do proper monitoring.

**Comment by OrmEmbaar** [comment]
Thanks for opening this issue. The first thing I would like to understand is how a validator can fail or, perhaps more importantly, underperform. 

A very basic monitoring system might look at validator height and compare that to one or more other nodes. That seems like a good and essential first step, but it only gives us insight into whether the validator is actually keeping up. Once the codebase is stable and we hit mainnet, I would expect most validators to only rarely fall behind the tip of the blockchain. 

Other types of instability/underperformance are less obvious and may pose a greater risk to longterm validator returns and, ultimately, network stability. For the purpose of this discussion, an underperforming node is one that cannot get elected to the consensus group or spends a below average amount of time in the consensus group. With that in mind, my questions are as follows:

1. How should validator performance be measured? 
2. What would constitute good validator performance? 
3. What factors might lead to a validator underperforming? 

Thanks!

**Comment by ericjohncarlson** [comment]
For my situation, I'm simply looking for a structured output (e.g. json) for specific validator metrics.  This doesn't need to be a gRPC stream or an open socket, and can be returned data based on executing a command line request.  The validator could expose an internal API for monitoring as well, but I don't know if that's necessary or adds additional port management, security controls.

For the testing done so far, here's the list of items that have been valuable for me thus far as well as some other items that may be good to report on/monitor:

- validator name
- validator version
- validator listen address(es), prioritized
- current height & sync height
- in_consensus true/false
- connected true/false
- dialable true/false
- hbbft perf penalty metric

Other nice to haves:
- nat_type
- hbbft perf bba_completions (as a decimal percentage, not 4/6)
- hbbft perf seen_votes (as a decimal percentage, not 24/26)
- hbbft perf recent_failures

**Comment by KunaniGaming** [comment]
I'd like to compile a real-time stats page at some point. So all of Eric's requests are fine. I prefer the bba/votes request to give current / max values though. I can do decimal conversions for progress displays on my end.

Any type of timing data would be great. Response times when communicating with other validators, timeouts, hbbft events timestamped, etc.

**Comment by OrmEmbaar** [comment]
> I'm simply looking for a structured output (e.g. json)

The ability to pass a --json flag would be a huge help.

**Comment by evanmcc** [comment]
I haven't had time to look at why the `--format=json` stuff is failing, but `--format=csv` works now and is much easier to parse, at least.

**Comment by kellybyrd** [comment]
Re format, I don't care much about JSON vs csv, but CSV is sometimes tricky in different languages (there's no CSV standard and some parsers are not very permissive. As far as the actual things I would want to know. It would all boil down to being able to answer the question "Is my validator earning as much as it can?" I guess this translates to: "Is my validator a great citizen relative to other validators?" Specifically, I think this ends up being stats that tell me things the algorithms that choose CG participants would consider to be bad:
- Basic p2p connectivity: dialable, connected, listen_addr, nat type (if relevant). 
- Validator version
- in_consensus or not.
- block height vs current top of the chain
- hbbft stats, with penalties, ideally with enough info for me to figure out: "ok, I got a +0.30 penalty for failing the DKG at time xx:yy:zz 

I think all of these have to be a timestamped events. Or, if we're just polling an interface, the timestamp is the time we poll. But if there are actual events vs just current state (like moving from CG to not happens at a specific time) it would be useful to be able to capture all the individual event times so we don't have to poll as often.

**Comment by evanmcc** [comment]
There is now a JSONRPC API for the miner.  Please see the docs for more details.  I believe that everything in here has been covered, so please open a new, specific issue if we've missed something.

**Comment by kellybyrd** [comment]
Sorry if this is covered somewhere but:
> Please see the docs for more details.
Link to docs?
