### ISSUE TITLE
Shuffle Witnesses

### ISSUE THREAD

**Issue by maartenvanderhoef** [helium/miner#711]
The current concept of first-come-first-served with the 25 witness receipts has a few limitations.

In cities with Cable and DSL and LTE/5G, DSL tend to have the lowest latencies by a few milliseconds. This causes some to wonder why their witnesses hardly change and vice versa who they witness. Cable in some cases adds another 10ms delay, this causing them to never be in the first 25 witnesses received by the challenger.
This generally pushes hotspot owners in the direction of DSL. HIP-15 reads [we want redundant RF coverage since hotspots are “unreliable” as compared to enterprise gateways like cell towers](https://github.com/helium/HIP/blob/master/0015-beaconing-rewards.md), this should also apply to the internet access used by the hotspots, redundancy should be more important than latency by a few milliseconds.

Secondly, with having the challenger functioning by first-come-first-served, it is not possible to add a random delay to the submitting code of the witness. Adding a random delay to the witness could relieve the network as in some cases beacons with 100+ witnesses can push the limits of the challenger and its relay.

@jerms on Discord suggested to create a PR which addresses this by using   [a streaming random selection](https://rosettacode.org/wiki/Knuth%27s_algorithm_S) to not take up memory, together with a bloom filter to mitigate bad actors submitting their receipt over and over again, increasing the chances it will make it into the final results.

A PR is in the making with [@sokhouw](https://github.com/sokhouw) and should follow soon.

**Comment by ke6jjj** [comment]
This ultimately was adopted into the code base (but not from @sokhouw's work, sadly). Closing!
