### ISSUE TITLE
Validators - transfer stake transaction doesn't move penalties to new validator

### ISSUE THREAD

**Issue by PaulVMo** [helium/miner#729]
Based on my interpretation of the transfer validator stake transaction (specifically the absorb function), it appears that penalties are not copied from the old validator to the new validator. This creates an opportunity to game elections. Penalties can essentially be reset just by transferring stake. Transfer stake can be as easy as generating new keys and submitting the wallet transaction for $0.35.

The transfer validator stake transaction should be updates such that penalties moved to the new validator along with the stake.

**Comment by evanmcc** [comment]
that's a good idea.  I think that it might actually just work that way?  but we should definitely do it on purpose.

**Comment by PaulVMo** [comment]
This is not actually an issue. The penalties are transferred.
