### ISSUE TITLE
Explicit Cool Down Release Height in Validator Unstake Transaction

### ISSUE THREAD

**Issue by lthiery** [helium/miner#736]
Currently, a chain_var defines cooldown and, upon unstaking, the user implicitly agrees to it.

Since the cooldown period is non-trivial (currently proposed at ~~2.5 months~~ 5 months), it would be advisable to have the signatory explicitly approve the cooldown period during which they will both not earn nor have access to their stake. This would be expressed in the block height at which they will recover their stake as it is released from the cool down period.

A new field shall be added to the `unstake_validator_v1` transaction (`stake_release_height`?). This height will be validated by confirming that is it greater than `current_block_height + chain_var::cool_down` and less than `current_block_height + chain_var::max_cool_down`. (`chain_var::max_cool_down` is currently proposed as 1k blocks). Therefore, this feature also requires this additional chain_var.

**Comment by jdgemm** [comment]
@lthiery the cooldown period is ~5 months (250,000 blocks).

**Comment by lthiery** [comment]
> @lthiery the cooldown period is ~5 months (250,000 blocks).

Thanks, edited above

**Comment by evanmcc** [comment]
This was implemented.
