### ISSUE TITLE
Israel frequency

### ISSUE THREAD

**Issue by shawaj** [helium/miner#739]
Looks like Israel may soon have a freq plan (possibly a variation of as923?)...
https://www.thethingsnetwork.org/community/telaviv/post/new-draft-of-frquency-allocations-by-the-israeli-moc
https://www.gov.il/he/departments/news/03012021

![0c8a0bd97dbd4da591baa2f4cc19f7a1 large](https://user-images.githubusercontent.com/3359418/115802139-373cea80-a3d6-11eb-8311-a477020ba297.png)

**Comment by jmarcelino** [comment]
Yes it's AS932-4, 917-920MHz

**Comment by papitosss** [comment]
So I was thinking of buying the bobcat 300 helium miner right now.
should I forget about it?

**Comment by VadimGut** [comment]
> So I was thinking of buying the bobcat 300 helium miner right now.
> should I forget about it?

what did you end up doing, i was thinking to buy the RAK Hotspot Miner v2 with the 915 mhZ
but i am not sure it is right

**Comment by ko3ak81** [comment]
Same doubts here... probably it won't be approved...

**Comment by shawaj** [comment]
@jmarcelino is this in an official published document somewhere?

**Comment by shawaj** [comment]
@jmarcelino looks like it's Asia 923 MHz with frequency shift of -5.9MHz. But did you have an official document on this?

**Comment by shawaj** [comment]
@jmarcelino ignore me. Found it https://lora-alliance.org/resource_hub/rp2-1-0-3-lorawan-regional-parameters/

[RP-2-1.0.3.pdf](https://github.com/helium/miner/files/6494221/RP-2-1.0.3.pdf)

**Comment by shawaj** [comment]
Added this in #772

**Comment by shawaj** [comment]
This is now merged in #772 so closing
