### ISSUE TITLE
Lack of frequency

### ISSUE THREAD

**Issue by mhmd231** [helium/miner#740]
There are many areas whose frequency is not mentioned on the list. 
I'm from Syria. can I be told of my country's hesitation ?

**Comment by shawaj** [comment]
According to the official document, Syria can do EU868

https://lora-alliance.org/resource_hub/rp2-1-0-3-lorawan-regional-parameters/

**Comment by shawaj** [comment]
I have added it in #772

**Comment by shawaj** [comment]
This is now merged in #772 so you can close this issue
