### ISSUE TITLE
validator: write out p2p address and angry purple tiger to files

### ISSUE THREAD

**Issue by tedder** [helium/miner#743]
It'd be nice if the validator wrote out the identity of itself to a file. That would remove reliance on the validator/miner being running and happy to get these basic introspection bits, and would make other types of automation easier.

Perhaps these could be placed next to the `swarm_key`.

**Comment by Vagabond** [comment]
`miner print_keys` will work without the node running and it prints the b58 key and the animal name

**Comment by tedder** [comment]
Aha. That may be sufficient.
