### ISSUE TITLE
Trinidad and Tobago frequency plan

### ISSUE THREAD

**Issue by Nathaniel0202** [helium/miner#746]
Good afternoon, does anyone know if Trinidad and Tobago uses US915 or AU915?

thanks!

**Comment by kristt2001** [comment]
i believe AU915. but i dont see any network range here.

**Comment by shawaj** [comment]
AU915 is correct as per the lora alliance specification https://lora-alliance.org/resource_hub/rp2-1-0-3-lorawan-regional-parameters/

**Comment by Deakarn** [comment]
Did you manage to get any miners yet? Also in TNT

**Comment by Nathaniel0202** [comment]
Not as yet

**Comment by Deakarn** [comment]
I see 4 units in the country now.

**Comment by glennjagdeosingh** [comment]
I'm seeing 5 units in Trinidad now. Anyone can confirm whether they use US915 or Au915. I don't understand why we would use the Australian network

**Comment by shawaj** [comment]
@glennjagdeosingh because AU915 is the correct frequency for the regulations. Check the document I linked above

**Comment by cdkeensd** [comment]
> 
> 
> I'm seeing 5 units in Trinidad now. Anyone can confirm whether they use US915 or Au915. I don't understand why we would use the Australian network

The ones in Trinidad are US915 . However Lora Alliance has us mapped to Region ITU- Region 3 which is Oceana/Australia.  We will have to lobby Lora Alliance to have them correct this mistake 

The Telecommunications Authority of Trinidad and Tobago (TATT- tatt.org.tt) has outlined that the frequency that we operate are compliant to ITU-R Region 2 (page 4 ) .
https://tatt.org.tt/Portals/0/Documents/Frequency%20Allocation%20Table%20(9kHz%20to%201000%20GHz).pdf

Trinidad and Tobago is located 60N and 20E which places us in ITU-Region 2
(See page 152 Appendix 1)
https://tatt.org.tt/Portals/0/Documents/Frequency%20Allocation%20Table%20(9kHz%20to%201000%20GHz).pdf

https://www.itu.int/en/ITU-R/terrestrial/broadcast/PublishingImages/bcd%20images/ITU%20regions.jpg

**Comment by shawaj** [comment]
It says 902-928MHz, I don't see any reason why AU915 would not be suitable

![Screenshot_20211116-014933_Acrobat for Samsung](https://user-images.githubusercontent.com/3359418/141881089-39d76820-a688-4f7c-b36f-0d0d2273bc41.jpg)
![Screenshot_20211116-020014_Acrobat for Samsung](https://user-images.githubusercontent.com/3359418/141882046-bbc95d4e-bfd8-42b6-9e36-b64cfe27b202.jpg)

There is likely a technical or operational reason why LoRa Alliance chose this frequency plan... For example sometimes it's due to maintaining interoperability with a neighbouring country with more restrictive rules for example.

To be honest, you are probably just wasting your time to fight it.

**Comment by cdkeensd** [comment]
> 
> 
> It says 902-928MHz, I don't see any reason why AU915 would not be suitable
> 
> ![Screenshot_20211116-014933_Acrobat for Samsung](https://user-images.githubusercontent.com/3359418/141881089-39d76820-a688-4f7c-b36f-0d0d2273bc41.jpg) ![Screenshot_20211116-020014_Acrobat for Samsung](https://user-images.githubusercontent.com/3359418/141882046-bbc95d4e-bfd8-42b6-9e36-b64cfe27b202.jpg)
> 
> There is likely a technical or operational reason why LoRa Alliance chose this frequency plan... For example sometimes it's due to maintaining interoperability with a neighbouring country with more restrictive rules for example.
> 
> To be honest, you are probably just wasting your time to fight it.

Lol I know it may be a losing battle with Lora Alliance , but I still wrote them .  AU915 and US915 are pretty much almost the same , but the issue will be that miners that do not have the same region settings according to Lora Alliance will not be able to witness each other. I have seen that happen with the US915 Bobcats here

**Comment by shawaj** [comment]
Yes that's mainly because bobcat aren't correctly configuring their hotspots based on the location asserted on the blockchain which they should, unfortunately.

Actually AU915 uses following frequencies:

And US915 uses:

**Comment by shawaj** [comment]
Full list is here:
```
US915' => [903.9, 904.1, 904.3, 904.5, 904.7, 904.9, 905.1, 905.3],
                      'EU868' => [867.1, 867.3, 867.5, 867.7, 867.9, 868.1, 868.3, 868.5],
                      'EU433' => [433.175, 433.375, 433.575],
                      'CN470' => [486.3, 486.5, 486.7, 486.9, 487.1, 487.3, 487.5, 487.7 ],
                      'CN779' => [779.5, 779.7, 779.9],
                      'AU915' => [916.8, 917.0, 917.2, 917.4, 917.6, 917.8, 918.0, 918.2],
                      'AS923_1' => [923.2, 923.4, 923.6, 923.8, 924.0, 924.2, 924.4, 924.6],
                      'AS923_2' => [921.4, 921.6, 921.8, 922.0, 922.2, 922.4, 922.6, 922.8],
                      'AS923_3' => [916.6, 916.8, 917.0, 917.2, 917.4, 917.6, 917.8, 918.0],
                      'AS923_4' => [917.3, 917.5, 917.7, 917.9, 918.1, 918.3, 918.5, 918.7],
                      'KR920' => [922.1, 922.3, 922.5, 922.7, 922.9, 923.1, 923.3],
                      'IN865' => [865.0625, 865.4025, 865.985],
                      'RU864' => [864.1, 864.3, 864.5, 864.7, 864.9, 868.9, 869.1]
```

**Comment by cdkeensd** [comment]
Ok so you are saying basically both AU915 and US915 miners should work based on Trinidad and Tobago's frequency spectrum. however Bobcat miners specifically will have issues due to their configuration issue ?

**Comment by shawaj** [comment]
Maybe, yes. Don't know enough about the bobcat ones other than that they have had issues in au915 with beacons and witnessing. There is an issue on here somewhere

For the frequency yes it looks from that document you linked that either would be legal but as lora Alliance say au915 it's best to stick to that

**Comment by RAGNAR868** [comment]
Greetings who has a helium miner? if so which one do you got? An are you making any profit I would like to get inno this
