### ISSUE TITLE
Version 2021.04.26 - problem when executing miner commands

### ISSUE THREAD

**Issue by disk91** [helium/miner#747]
following commands usually working:
```
docker exec miner miner info summary
docker exec miner miner info height
docker exec miner miner peer book -s
``` 

now return an error message
```
RPC to 'miner@127.0.0.1' failed: {'EXIT',
                                  {{case_clause,
                                    {error,
                                     {no_matching_spec,
                                      ["[["info","summary"]]"]}}},
                                   [{blockchain_console,command,1,
                                     [{file,"blockchain_console.erl"},
                                      {line,16}]},
                                    {rpc,'-handle_call_call/6-fun-0-',5,
                                     [{file,"rpc.erl"},{line,197}]}]}}
```

Problem confirmed on ARM and AMD64 version

**Comment by vihu** [comment]
This will be fixed in the next release. [Fix](https://github.com/helium/miner/pull/748).

**Comment by disk91** [comment]
not fixed 
RPC to 'miner@127.0.0.1' failed: {'EXIT',
                                  {{case_clause,
                                    {error,
                                     {no_matching_spec,["info","summary"]}}},
                                   [{blockchain_console,command,1,
                                     [{file,"blockchain_console.erl"},
                                      {line,16}]},
                                    {rpc,'-handle_call_call/6-fun-0-',5,
                                     [{file,"rpc.erl"},{line,197}]}]}}
Error: Usage information not found for the given command

**Comment by disk91** [comment]
Sorry it's now good, but we need to wait a long time before being able to execute the command

**Comment by Vagabond** [comment]
This has unfortunately been the case for a while, you'd just have gotten a better error about the command not being registered before.
