### ISSUE TITLE
Validator transactions allow validator keys with different network type

### ISSUE THREAD

**Issue by PaulVMo** [helium/miner#752]
The validator transactions allow validator keys to be used that have a different network type that the network they are on. For example, mainnet validator swarm keys can be used on testnet.

Stake transaction using a testnet owner key but mainnet swarm_key for the validator:
https://explorer.helium.wtf/txns/Km5nC2IHuebqu84pp1khTYBgmjjpUOEwQD8id3rxarw 

Transfer stake transactions using a testnet address for old key but mainnet key for new address:
https://explorer.helium.wtf/txns/xJQ9h19LOaBaiu5AwFQhk2NbgnVar6Jd5mKOZj9mKZk

**Comment by ke6jjj** [comment]
Possible fix in PR https://github.com/helium/blockchain-core/pull/878

**Comment by vihu** [comment]
Thank you @PaulVMo and @ke6jjj for finding and proposing a fix for this issue. This is fixed in https://github.com/helium/blockchain-core/pull/879 and we'll update miners soon.

**Comment by evanmcc** [comment]
This is resolved.
