### ISSUE TITLE
Supported helium freequency for INDIA 

### ISSUE THREAD

**Issue by IN865RIO** [helium/miner#759]
India supports a wide range of Frequency ranging from 865 to 867 my query is what about 868Mhz? 

Now the confusion arises in India because the 865 MHz to 867 MHz license free band in India ends at 867 MHz, as per the Ministry of Communications and Information Technology directions as mentioned here. Bit of a conundrum because in the ITU Region 1 (Mostly Europe) 863-870 MHz is license free 

can I use 868 mhz in India and does Helium suppports 868 Mhz in India? as it it not license free band

**Comment by shawaj** [comment]
IN865 is for India

**Comment by vihu** [comment]
We are in the middle of adding support to all (most) LoRaWAN region parameters. Refer: https://github.com/helium/blockchain-core/blob/781c05e2948cb35fab7016377d781c7daab4f445/include/blockchain_region.hrl#L367

WIP PR: https://github.com/helium/blockchain-core/pull/776
