### ISSUE TITLE
Vietnam frequency plan

### ISSUE THREAD

**Issue by qhiee167** [helium/miner#762]
What miner should i use for AS923-2 frequency in Vietnam, thank you

**Comment by vihu** [comment]
AS923-2 frequency support is in the works. Refer: https://github.com/helium/blockchain-core/blob/781c05e2948cb35fab7016377d781c7daab4f445/include/blockchain_region.hrl#L234

WIP PR: https://github.com/helium/blockchain-core/pull/776
