### ISSUE TITLE
Didn't Helium discontinue acceptance of third-party builds into its blockchain?

### ISSUE THREAD

**Issue by MichaelBrenden** [helium/miner#763]
I heard fraud ('fake miners having no radios but somehow earning $HNT') caused Helium company to discontinue accepting third-party builds into the Helium blockchain.  Can anyone clarify, please?  Thank you.

**Comment by shawaj** [comment]
Do you mean "DIY gateways"?

If so, yes. But look at HIP22 https://github.com/helium/HIP/issues/94
