### ISSUE TITLE
Missing LoraWAN support code frequency for my country, Libya

### ISSUE THREAD

**Issue by abdodeikna** [helium/miner#773]
I would like to start helium mining (HNT) in Libya but I don’t know if it’s gonna work

**Comment by vihu** [comment]
![image](https://user-images.githubusercontent.com/3199183/118710814-aa6a2e80-b7d3-11eb-9aff-50cb221187c3.png)

From: https://lora-alliance.org/wp-content/uploads/2020/11/RP_2-1.0.2.pdf

Libya appears to be an unsupported region according to Lora alliance. There's not much we can do until lora alliance supports a particular region. Sorry about that.
