### ISSUE TITLE
Cannot make build on SolusOS

### ISSUE THREAD

**Issue by filippossemere** [helium/miner#785]
sudo git clone https://github.com/helium/miner.git
cd miner/
sudo make release

`
./rebar3 as prod release -n miner
/usr/bin/env: ‘escript’: No such file or directory
make: *** [Makefile:32: release] Error 127
`
Stuck here and I'm unsure if all of the dependencies even are available on SolusOS.

**Comment by Vagabond** [comment]
You'd need to install Erlang at a minimum here, but we don't support Solus or have any experience with it.

**Comment by filippossemere** [comment]
> You'd need to install Erlang at a minimum here, but we don't support Solus or have any experience with it.

just installed erlang and sudo make release seems to work now, but I also needed to install cargo/rust apparently

![image](https://user-images.githubusercontent.com/22945098/119402255-fdb11500-bcdc-11eb-9820-217b59b27764.png)

**Comment by filippossemere** [comment]
The last sodium.h issue persists even after removing the build and re-cloning and building.

**Comment by vihu** [comment]
> The last sodium.h issue persists even after removing the build and re-cloning and building.

Don't know much about SolusOS, but you may also need to install libsodium + libsodium-devel. Solus does seem to have [these](https://pkgs.org/download/libsodium) packages.

**Comment by filippossemere** [comment]
> > The last sodium.h issue persists even after removing the build and re-cloning and building.
> 
> Don't know much about SolusOS, but you may also need to install libsodium + libsodium-devel. Solus does seem to have [these](https://pkgs.org/download/libsodium) packages.

Yes, it was libsodium-devel which I was missing. Do you have a good link for how to setup wallet and so on with this miner?

![image](https://user-images.githubusercontent.com/22945098/119406411-099fd580-bce3-11eb-9d20-a9c1fa86240f.png)

**Comment by vihu** [comment]
> > > The last sodium.h issue persists even after removing the build and re-cloning and building.
> > 
> > 
> > Don't know much about SolusOS, but you may also need to install libsodium + libsodium-devel. Solus does seem to have [these](https://pkgs.org/download/libsodium) packages.
> 
> Yes, it was libsodium-devel which I was missing. Do you have a good link for how to setup wallet and so on with this miner?
> 
> ![image](https://user-images.githubusercontent.com/22945098/119406411-099fd580-bce3-11eb-9d20-a9c1fa86240f.png)

Nice, glad you were able to compile it, running miner is pretty typical to running any erlang application. We have general documentation available [here](https://docs.helium.com), you can find wallet building and usage there.
