### ISSUE TITLE
Please use latest releases for github

### ISSUE THREAD

**Issue by vaddec-everstake** [helium/miner#787]
Hi.
I use scripts for search latest releases API github. 
And if I check https://git.github.com/repos/helium/miner/releases/latest/ I see 404 ERROR. 
This can be resolved if you use the latest release. If you have another solution, tell me how to automate the notification of new releases using API.

In documentation API github https://api.github.com/repos/[path to repos]/releases/latest

**Comment by shawaj** [comment]
Have you seen this https://quay.io/repository/team-helium/miner?tab=tags

**Comment by evanmcc** [comment]
We'll consider this, but for now, the quay interface will have to suffice.
