### ISSUE TITLE
Update frequency in the Philippines

### ISSUE THREAD

**Issue by Edwin102576** [helium/miner#788]
Hello, I just want to follow up the plotted frequency here in the Philippines.

**Comment by shawaj** [comment]
It's been merged in #772

**Comment by shawaj** [comment]
AS923-3

**Comment by Edwin102576** [comment]
Hello Sir Aaron,

Good day. May I know what is the most compatible Helium Miner Brand that
fits AS923-3 frequencies here in the Philippines?

Your reply will be highly appreciated.

God bless you Sir for your reply.

EDWIN C. FRANCISCO

**Comment by shawaj** [comment]
@Edwin102576 I'm biased because I'm from Nebra, so I can't really answer that question without mentioning our own and this isn't really the place for it.

Your best bet is to go to discord.gg/helium and join the #ph-philippines channel and you can discuss with people there :-)

**Comment by Edwin102576** [comment]
No, that's ok, if you're biased, if this one will help us here in the
Philippines the compatible with AS923-3 freq. Did Nebra provide AS923-3
frequencies?
