### ISSUE TITLE
Is there any suitable device for mining helium in Hong Kong?

### ISSUE THREAD

**Issue by CHUNGKINGHO** [helium/miner#796]
Many people said that the frequency in HK is AS923
Bobcat / Nebra US915 can be used in Hong Kong?

**Comment by shawaj** [comment]
Not sure about bobcat one but Nebra definitely can.

See below...
![Screenshot_20210529-181118_Chrome](https://user-images.githubusercontent.com/3359418/120078854-4f74e900-c0a9-11eb-907d-bde2b90cf002.jpg)
