### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by seCoin3363se** [helium/miner#801]
Hi, I would appreciate Helium to support IPv6. There may be many people in the future with problematic IPv4 but public IPv6 like me (I have public IPv6 but I'm behind 2x NAT at IPv4). Many thanks. (reffering to https://github.com/NebraLtd/helium-miner-software/issues/60 )

**Comment by ganey** [comment]
Just to add to this, some UK ISP's only use IPv6 (Sky broadband has been for years). 

It's 2021, IPv6 should have been the default with backwards compatibility for IPv4

**Comment by evanmcc** [comment]
unlikely that this will be fixed any time soon, closing for now.

**Comment by adamcharnock** [comment]
I find this response very surprising. I operate a small ISP and it is simply not feasible to acquire sufficient IPv4 addresses to provide one to each customer, so we have to use CGNAT (aka double NAT).

We are interested in deploying miners at our towers, and our customers may be interested in deploying at home. We hand out public IPv6 blocks to all customers because, well, it’s 2021.

Surely IPv6 would be amazing for something like Helium?

**Comment by abhay** [comment]
It will likely be something we can support in Light Hotspots but not a priority in the short term for the erlang miner codebase.

**Comment by qwick745** [comment]
+1 on this. I'm on T-mobile for my miners and TMO only issues IPv6 addresses now for their standard plans.

**Comment by flyoffacliff** [comment]
I agree, shocked this is unsupported in 2021. Hope to see it in the coming months...

**Comment by lowerpower** [comment]
Helium requires inbound connections to port 44518, this is the problem.   The network already tracks IP, why not store IP:PORT or have it settable.    At least then we could make a viable relay system that could support thousands of miners on one IP.

**Comment by petrkr** [comment]
Problem would be in thing that all miners use docker, and most of users do not know how to pass IPv6 to docker, so it's easier to do docker run -p 44158:44158 than think how to do IPv6 pass through or do NAT on IPv6... Because there is no other reason why NOT support IPv6. Linux kernel support it since kernel 2.6 and Windows since XP. (both more than 20 years old).

But maybe it's business model, because you have to pay for everything on helium network (change location, antenna, ...) so maybe if you want cover whole city by 100+ HNT miners, you have to but almost /24 range of IPv4 (which is also like another $5000)

**Comment by snip** [comment]
@petrkr as of today libp2p used is not compatible with ipv6. (how would you ask a ipv4 only miner to connect to a ipv6 only miner?)
Target is to run light miners. For which miner to miner communicaiton will not be anymore required. Only miner to validator will be. So at target it will be easier to implement ipv6. But at target there will be no more incoming TCP session (so no more need of forwarding ports).
I prefer the team keep working hard on light miner path than trying to implement ipv6 for a temporary setup.

**Comment by petrkr** [comment]
I do not consider IPv6 as temporary.

IPv6 only will connect to IPv6 only of course.
IPv4 only will connect to IPv4 only

But dual stack can connect to both (if  not firewalled and if pub ipv4)

Ipv6 can connect to ipv4 world by using nat64.

But it already works at other crypto for many years, so it's really not bottlenck

IPv4 was exhausted around 2012 already.


But if they work on solution which will NOT require public ip at all then it's ok..

Actually even now they can use for example TOR to connect each other. There are many possibilities...

**Comment by snip** [comment]
> I do not consider IPv6 as temporary.

IPv6 is not temporary. full miner are.

> IPv6 only will connect to IPv6 only of course. IPv4 only will connect to IPv4 only

So 50% of communications will fail?

> Ipv6 can connect to ipv4 world by using nat64.

So this must be implemented ISP side + helium side ... for a temporary solution (before switching to light miner).

> But it already works at other crypto for many years, so it's really not bottlenck

A crypto with communication between all nodes? Example?

> But if they work on solution which will NOT require public ip at all then it's ok..

They are: https://www.helium.com/roadmap#lighthotspots

> Actually even now they can use for example TOR to connect each other. There are many possibilities...

TOR can works between an IPv4 only to an IPv6 only?

**Comment by petrkr** [comment]
> IPv6 is not temporary. full miner are.
I see, missunderstand

> So 50% of communications will fail?
why ? It does not connect each to each, it connects to some random nodes, that is how most of P2P works.
for example my bobcat now has only 9 connections to P2P network and not 400 000
![image](https://user-images.githubusercontent.com/6428351/148419610-d1f15b85-73ae-455c-888e-48c27ca610d1.png)


> So this must be implemented ISP side + helium side ... for a temporary solution (before switching to light miner).
Yes

> A crypto with communication between all nodes? Example?
They does not, they connect for example random 15 nodes based for example, you do not need to connect to all as you can check blokchain consistency by itself.

> TOR can works between an IPv4 only to an IPv6 only?

No, TOR could be used to achive P2P over NAT, so nodes will not be relayed to each other.

**Comment by petrkr** [comment]
But you are right, there is not reason implement something to temporary solution. But it could be taken in mind for new / lights hotspots.

But mainly manufactures of base image must support it, then this mining sw can use it. So it's wrong thread anyway I guess...

Regards.

**Comment by PCDbeeip** [comment]
I think any modern system like should support IPv6.
I think any modern system should use IPv6 by default
IPv4 is legacy ( see https://www.ripe.net/manage-ips-and-asns/ipv4/ipv4-run-out) and should now ony be used as a workaround for pepole that cannot have ipv6 for any reason.

**Comment by telmich** [comment]
Hey @evanmcc,

is there any chance we can reopen this ticket? IPv6 makes miners directly reachable as opposed to the port forward that is required for IPv4.

**Comment by petrkr** [comment]
New HIP will not need direct access at all, so it's kinda out-of-date.

Much worst is by that HIP also users/nodes will be missing blockchain, so they can not check if developers (or validators) does not cheat. If you want have copy of blockchain, you need to become validator node, but for that you will need deposite 10  000HNT (aprox 230 000 USD in time of writting)
