### ISSUE TITLE
HELP NEEDED Can any one clarify which frequency is suitable for Mongolia ? 

### ISSUE THREAD

**Issue by gatuk19** [helium/miner#810]
Even ©2021 LoRa Alliance  database doesn't indicate any suitable frequency in Mongolia. There are more than 10 bobcat hotspots are working here in Ulaanbaatar, Mongolia. 
Is that mean bobcat euro model is suitable in Mongolia ? 
if not, after purchasing euro model, is it possible to adjust the frequency by changing antenna only ? 

Thank you

**Comment by shawaj** [comment]
You'd need to contact your local government to ask about the correct frequency.

**Comment by shawaj** [comment]
Just changing the antenna won't change the frequency either. You will need to also change the software configuration and possibly also the concentrator. You'd need to contact Bobcat to see if it's possible to change the hardware/software to a different frequency.
