### ISSUE TITLE
Can't build miner

### ISSUE THREAD

**Issue by benarent** [helium/miner#827]
I was working to recreate my testnet miner from source, but was unable to due to it being unable to find blockchain-core. 

```
➜  miner git:(pevm/validators) ./rebar3 as validator release

===> Verifying dependencies...
===> Fetching blockchain (from {git,"https://github.com/helium/blockchain-core.git",
                      {ref,"5968b371e7084354a271f265c1ebbdecbb58efaa"}})
===> Failed to fetch and copy dep: {git,
                                  "https://github.com/helium/blockchain-core.git",
                                  {ref,
                                      "5968b371e7084354a271f265c1ebbdecbb58efaa"}}
```

**Comment by benarent** [comment]
It looks like `pevm/testnet-integration1` i no longer around. Any suggestions @evanmcc ? 

https://github.com/helium/miner/commit/8acd7f8001b70cdb0ee542344e3a6b0565875b95#diff-427d8ddce21ccc4fae24fb547c7a82c2a793ed57208d8343e519e0aec8119ff7R13

**Comment by vihu** [comment]
> It looks like `pevm/testnet-integration1` i no longer around. Any suggestions @evanmcc ?
> 
> [8acd7f8#diff-427d8ddce21ccc4fae24fb547c7a82c2a793ed57208d8343e519e0aec8119ff7R13](https://github.com/helium/miner/commit/8acd7f8001b70cdb0ee542344e3a6b0565875b95#diff-427d8ddce21ccc4fae24fb547c7a82c2a793ed57208d8343e519e0aec8119ff7R13)

Maybe try with the latest [validator tag](https://github.com/helium/miner/releases/tag/val0.1.73) ?

**Comment by benarent** [comment]
@vihu This did the trick. ty
