### ISSUE TITLE
connect no about 5% of the time (testnet)

### ISSUE THREAD

**Issue by Jackiehelium** [helium/miner#862]
I am running this command every minute:
docker exec validator miner info p2p_status
and logging f I am connected or not). I am seeing about 5% of the time connected = no
Here is what I am using to start each machine
arm64
#!/bin/bash
docker run -d --init \
--restart always \
--publish 2154:2154/tcp \
--name validator \
-v $HOME/validator_data:/var/data \
 -e "NAT_INTERNAL_IP=172.17.0.3" \
-e "NAT_EXTERNAL_IP=$( curl -s ipv4.icanhazip.com )" \
quay.io/team-helium/validator:latest-val-arm64 

 miner info p2p_status
+---------+-------+
|  name   |result |
+---------+-------+
|connected|  yes  |
|dialable |  yes  |
|nat_type |unknown|
| height  | 6969  |
+---------+-------+

amd:
#!/bin/bash
docker run -d --init \
--restart always \
--publish 2154:2154/tcp \
--name validator \
-v $HOME/validator_data:/var/data \
 -e "NAT_INTERNAL_IP=172.17.0.3" \
-e "NAT_EXTERNAL_IP=$( curl -s ipv4.icanhazip.com )" \
quay.io/team-helium/validator:latest-val-amd64 

 miner info p2p_status
+---------+-------+
|  name   |result |
+---------+-------+
|connected|  yes  |
|dialable |  yes  |
|nat_type |unknown|
| height  | 6970  |
+---------+-------+

is this number to be expected?
What other information can I provide!? 
Thank you for all your hard work!

**Comment by evanmcc** [comment]
```    CheckSessions = fun() ->
                            case (catch length(libp2p_swarm:sessions(SwarmTID)) > 5) of
                                true -> "yes";
                                _  -> "no"
                            end
                    end,
```
This is the code that it's checking.  I think that this would ideally be a number?  so 0 would be bad.  I'm not sure that 4 connections is actually bad, though.   I'm not sure how actionable this information is.

**Comment by Jackiehelium** [comment]
when I build the branch:
pevm/clarify-connected

I am getting the following error:
===> Compiling miner
===> Bad semver version in ["0.1.0",
                                       "2021.06.28.1+build.2.ref5c5fd0f"]
escript: exception error: no function clause matching relx:format_error(unparsable_release) (/Users/evan/src/rebar3/_build/default/lib/relx/src/relx.erl, line 141)
  in function  rebar3:handle_error/2 (/Users/evan/src/rebar3/src/rebar3.erl, line 347)
  in call from escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 

Any idea when this will be merged for testnet or mainnet?
Thank you!!!
