### ISSUE TITLE
JSONRPC - hbbft_perf

### ISSUE THREAD

**Issue by deasydoesit** [helium/miner#873]
### Issue
- The `hbbft_perf` command on the JSONRPC endpoint returns `Method not found.`

### Expected behavior
- The `hbbft_perf` command on the JSONRPC should return consensus group penalty information in JSON format

### Further info
- Command: 
> ` curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1,"method":"hbbft_perf"}' http://localhost:4467`
- Return value:
> `{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found."},"id":1}`

**Comment by evanmcc** [comment]
This is not implemented and will need to be implemented.

**Comment by ke6jjj** [comment]
I'll do it.

**Comment by ke6jjj** [comment]
This got merged. Can be closed now.

**Comment by vihu** [comment]
https://github.com/helium/miner/pull/930
