### ISSUE TITLE
Discovery mode does nothing on my Bobcat miner.

### ISSUE THREAD

**Issue by psavva** [helium/miner#878]
Please help me with the Discovery mode on my Bobcat miner.

helium://hotspot/112KcnsXfn7G3BNL6eeGiJmZvLZyUoKnsesnDKH8TJ1kLwmt6zR

I'm not sure it's working at all ..

**Comment by hexalys** [comment]
I have had similar issues early on. Suggestions are to restart the hotspot, reinstall the app and/or log-out of your wallet (making sure you have your keys saved first, and the latest firmware). The latter especially worked for me with a Bobcat using the iPhone app.

**Comment by meowshka** [comment]
@psavva looks like your question was answered, I'm closing the issue. If you have any other questions, please bring them up in the Discussions board.
