### ISSUE TITLE
`Bad semver version in ["0.1.0","2021.07.02.0_GA"]`  when building validator from tag `validator1.0.5`

### ISSUE THREAD

**Issue by kellybyrd** [helium/miner#892]
From a fresh git clone, I did this:
```
~/src/helium$ git clone https://github.com/helium/miner.git
~/src/helium$ cd miner
~/src/helium/miner$ git checkout validator1.0.5 -b validator1.0.5
Switched to a new branch 'validator1.0.5'
~/src/helium/miner$ git show
commit 2023f2ff4f3515a912c153cab3c4a6b818e60de2 (HEAD -> validator1.0.5, tag: validator1.0.5, tag: 2021.07.02.0_GA, tag: 2021.07.02.0, origin/master, origin/HEAD, master)
Merge: 85a81ea b0a7974
Author: Rahul Garg <3199183+vihu@users.noreply.github.com>
Date:   Fri Jul 2 16:55:46 2021 -0700

    Merge pull request #890 from helium/rg/snap-904710

    Snapshot to 904710

~/src/helium/miner$ ./rebar3 as validator release
<... snip ...>
===> Analyzing applications...
===> Compiling miner
===> Bad semver version in ["0.1.0","2021.07.02.0_GA"]
escript: exception error: no function clause matching relx:format_error(unparsable_release) (/Users/evan/src/rebar3/_build/default/lib/relx/src/relx.erl, line 141)
  in function  rebar3:handle_error/2 (/Users/evan/src/rebar3/src/rebar3.erl, line 347)
  in call from escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3
 ```

This is on Ubuntu 20.04, in an environment that has built all of the mainnet validator releases before this one, and several testnet releases. Erlang package is locked at version 23.3.1-1 

A wild guess is that the some version stamping code is trying to parse the multiple tags that are on this same commit and are falling over. From Discord, I know others have built this tag, but at least one of those who successfully built it earlier now reports he sees the same error I do if he uses a fresh clone.

**Comment by andrewboudreau** [comment]
also seeing issue when running 
`docker build -t helium:andrews-miner -f .buildkite/scripts/Dockerfile-val-amd64 .` on `master`

with the console output of ...
```
#14 559.3 ===> Bad semver version in ["0.1.0","2021.07.02.0_GA"]
#14 559.3 escript: exception error: no function clause matching relx:format_error(unparsable_release) (/Users/evan/src/rebar3/_build/default/lib/relx/src/relx.erl, line 141)
#14 559.3   in function  rebar3:handle_error/2 (/Users/evan/src/rebar3/src/rebar3.erl, line 347)
#14 559.3   in call from escript:run/2 (escript.erl, line 758)
#14 559.3   in call from escript:start/1 (escript.erl, line 277)
#14 559.3   in call from init:start_em/1
#14 559.3   in call from init:do_boot/3
------
```

**Comment by kellybyrd** [comment]
Someone on Discord pointed me to the [tar.gz release of validator1.0.5](https://github.com/helium/miner/releases/tag/validator1.0.5). My build completes, but I think the wrong version is stamped into the build:
I built that tar and I don't think it builds the right thing:
```
~/src/helium/miner_tar_gz/miner-validator1.0.5$ ./rebar3 as validator tar
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling miner
===> Assembling release miner-0.1.0...
===> rendering builtin_hook_wait_for_process hook to _build/validator/rel/miner/bin/hooks/builtin/wait_for_process
===> Release successfully assembled: _build/validator/rel/miner
===> Building release tarball miner-0.1.0.tar.gz...
===> Tarball successfully created: _build/validator/rel/miner/miner-0.1.0.tar.gz
```
That `miner-0.1.0.tar.gz` makes me think the wrong version got built, but it may be the write source code. The typical output tar is `_build/validator/rel/miner/miner-1.0.4.tar.gz`

**Comment by ke6jjj** [comment]
Thanks to `@andrewb` on Discord, for the suggestion to revert commit #8be0c7. Doing so is effectively this patch to `rebar.config`:

```
diff --git a/rebar.config b/rebar.config
index 24b597a..3de34e9 100644
--- a/rebar.config
+++ b/rebar.config
@@ -59,7 +59,7 @@
 ]}.
 
 {relx, [
-        {release, {'miner', "0.1.0"},
+        {release, {'miner', "git"},
          [miner, runtime_tools, tools, recon]},
         {overlay,
          [
```

Doing so and rebuilding worked for me.

**Comment by ke6jjj** [comment]
I'm no longer having this issue with source built from `validator1.0.7`.

**Comment by ke6jjj** [comment]
I **am** having the issue with `validator1.0.7`.

**Comment by kellybyrd** [comment]
I built with 1.0.7 last night and it worked for me. It built: `miner-1.0.7+build.1070.refa6deccd.tar.gz` 

@ke6jjj: maybe start from a fresh clone of the repo without any of your local changes? Or at least go back to `master` branch force pulled from origin?

**Comment by ke6jjj** [comment]
@kellybyrd I'm building with `./rebar3 as validator release` It looks like you're using the `tar` target. Perhaps the difference could lie there? I have been ensuring that I have no local changes/modifications and have been right on the master branch (with tag) when attempting the build.

**Comment by kellybyrd** [comment]
> @kellybyrd I'm building with `./rebar3 as validator release` It looks like you're using the `tar` target. Perhaps the difference could lie there? I have been ensuring that I have no local changes/modifications and have been right on the master branch (with tag) when attempting the build.

Previously, both failed. Now, both succeed.

**Comment by ke6jjj** [comment]
Perhaps we can close now?
