### ISSUE TITLE
Miner info height higher than blockchain height from API

### ISSUE THREAD

**Issue by shawaj** [helium/miner#938]
Have noticed on occasion that the miner height from `miner info height` is higher than the blockchain height [from the API](https://api.helium.io/v1/blocks/height) - is there some lag in the API perhaps?

![Screenshot_20210716-065534_Chrome](https://user-images.githubusercontent.com/3359418/126053866-6916d261-6b09-42e2-8e8e-a25e6bba4002.jpg)

**Comment by densone** [comment]
@shawaj this is ok. The API has to consume data that goes through a transformation process so it's not as up to date as running the command directly against the blockchain.

**Comment by madninja** [comment]
That's correct.. the `status` field in the api is based on _gossip_ and not on-chain data. It is laggy and can be delayed for quite a while. We're trying to find ways to represent how in sync your hotspot is without having accurate data at all times.

**Comment by shawaj** [comment]
That's no problem, we will put some error handling in the local diagnostics so this higher than 100 percentage doesn't confuse things 👍

Thanks very much
