### ISSUE TITLE
peer_book(ADDR) RPC not working

### ISSUE THREAD

**Issue by LilaQ** [helium/miner#953]
I'm running the latest `miner` image, but can't use the `peer_book` RPC with a provided address. `self` and `all` work fine, but specific address errors out with an internal error.

`peer_ping`, which uses the same args, works just fine.

**peer_ping**
`(miner@127.0.0.1)6> miner_jsonrpc_peer:handle_rpc(<<"peer_ping">>, #{<<"addr">> => <<"/p2p/11213y8nLoeD3wtK5quUbLiNqP7bLTukADXy52Y9hJrKsPVmpNS">>}).`
`#{<<"/p2p/11213y8nLoeD3wtK5quUbLiNqP7bLTukADXy52Y9hJrKsPVmpNS">> =>
      101}`

**peer_book**
`(miner@127.0.0.1)7> miner_jsonrpc_peer:handle_rpc(<<"peer_book">>, #{<<"addr">> => <<"/p2p/11213y8nLoeD3wtK5quUbLiNqP7bLTukADXy52Y9hJrKsPVmpNS">>}).`
`** exception error: no match of right hand side value {error,not_found}
     in function  miner_jsonrpc_peer:peer_book_response/1 (miner_jsonrpc_peer.erl, line 119)
(miner@127.0.0.1)8>`

It seems that the difference is that `peer_ping` does `binary_to_list` on the Addr in the argument but `peer_book` does not.

The same problem exists for the `validator` as well.

**Comment by Bogardo** [comment]
I'm having the same issue with `peer_book`.

**Comment by robputt** [comment]
Also seeing this problem too, currently a blocker for my project, any ETA for fix?

**Comment by LilaQ** [comment]
#974 
Created a PR for this

**Comment by ke6jjj** [comment]
I believe the fix has been applied (#974). This should be closed if so.
