### ISSUE TITLE
Compile miner failed on MAC

### ISSUE THREAD

**Issue by zxgangandy** [helium/miner#973]
![image](https://user-images.githubusercontent.com/544426/128856737-34a778d5-70b2-4936-ba72-0509ee85c09e.png)

Does anyone meet this issue? Hope u can help me:)

**Comment by madninja** [comment]
This error usually happens when your installed erlang is too new. Please install erlang 22

**Comment by Vagabond** [comment]
Erlang 23 also works, we just haven't finished the OTP 24 support yet.
