### ISSUE TITLE
RPC method `info_p2p_status` returns internal error in version 1.1.5

### ISSUE THREAD

**Issue by OrmEmbaar** [helium/miner#982]
Version 1.1.5 breaks RPC method `info_p2p_status`. 

```bash
curl --location --request POST 'localhost:4467' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "info_p2p_status"
}'
```
```
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error."},"id":1}
```

**Comment by ke6jjj** [comment]
I'm not able to reproduce this on a 1.1.5 validator built from source. Can you:

1. Try again while watching your `console.log`
2. Find the more descriptive error line in that log
3. Tell us more about your deployment. (Built from source? Docker?)

**Comment by OrmEmbaar** [comment]
Errors logs:
```
2021-08-19 18:46:50.023 [info] <0.1570.0>@miner_jsonrpc_handler:handle_rpc:36 Dispatching method <<"info_p2p_status">> with params: []
2021-08-19 18:46:50.031 [error] <0.1570.0> Error in JSON-RPC handler for method info_p2p_status with params [] (id: 1): error:{badmatch,#{"dialable" => "yes","height" => "962473","nat_type" => "symmetric","sessions" => "11","well-connected" => "no"}} from [
```

Deployed with docker using the tag `miner-amd64_validator1.1.5`. It is behaviour I have seen across several production validators and in my local dev environment. I have not seen that RPC method succeed once on 1.1.5.

**Comment by ke6jjj** [comment]
oo, almost had enough to help there. Can you get the next few lines? You cut off the crucial ones, which might show us where that `badmatch` is being thrown.

**Comment by OrmEmbaar** [comment]
There was nothing else. The next lines are unrelated in both time and type. 

Is the issue here not to do with mismatched types? The type I see in the error output differs from the type in previous versions, as it contains the keys `sessions` and `well-connected`, and is missing `connected`. Are you sure you're running 1.1.5?

**Comment by OrmEmbaar** [comment]
I don't know much about Erlang, but this RPC method does not appear to expect anything with those keys.

https://github.com/helium/miner/blob/84d2fec83b778e64d7881a876c776c199a984385/src/jsonrpc/miner_jsonrpc_info.erl#L33-L45

**Comment by OrmEmbaar** [comment]
> You cut off the crucial ones

I've just realised that I did cut a bit off that error log, but it was only a single character `]`. Apologies.

**Comment by ke6jjj** [comment]
I like your thinking, but that expression _shouldn't_ be bothered by extra keys appearing in the map. It should only extract the values that it explicitly lists. However, It could be that one of the keys it is _expecting_ is missing! And that is in fact the case.

In the output you've pasted, there's no`"connected"` key anymore. It appears to have been renamed `"well-connected"`.

**Comment by ke6jjj** [comment]
And to further confuse the issue, it appears that Evan has just pulled a fix into the code base, which makes it especially hard to see what was going on.

https://github.com/helium/miner/commit/5eb837b5e479cadd091460ac63e70a99a24c126d

With this latest pull, it should be working again, at cursory glance.

**Comment by OrmEmbaar** [comment]
Okay, i'll wait on 1.1.6 and see what happens. Thanks for your help!
