### ISSUE TITLE
Auto purge all blocks prior to blessed block

### ISSUE THREAD

**Issue by shawaj** [helium/miner#984]
When a new blessed block is released, the miner should automatically purge any blocks before this in /var/data/blockchain.db as they are no longer needed.

At the moment we are doing this as a workaround directly on Nebra units but it should probably be part of the core miner functionality to do this.

Putting this in here even though I guess it also relates to https://github.com/helium/blockchain-etl

**Comment by evanmcc** [comment]
There's a PR out there for space-sensitive purging of older blocks that we need to land at some point.  I'm going to close this as a dupe of that one, which is: https://github.com/helium/blockchain-core/pull/808

**Comment by shawaj** [comment]
Thanks for the heads up @evanmcc  👍
