### ISSUE TITLE
New firmware update has knocked my miner out

### ISSUE THREAD

**Issue by Kayz86** [helium/miner#988]
I notice there is a new diagnostic page and with that a new firmware update version of 2021.08.16.1

I have noticed since this afternoon my miner has stopped mining,

These are the listed issues:

- Not connected to the blockchain: False
- Height Status: 0 / 968601
- Modem Detected: False

Your help would be much appreciated.

**Comment by abhay** [comment]
Please contact your manufacturer. Support email is available on helium.com/mine.
