### ISSUE TITLE
How to run miner on MAC OS

### ISSUE THREAD

**Issue by wushengyidong** [helium/miner#989]
Can u guys help me to how to run the miner on the MAC OS? 
Cause I wanner do some debug for the program. But there's no any doc for this. Please help me:)

**Comment by shawaj** [comment]
You can either build it from source or just run using docker. Instructions are here https://github.com/helium/miner#miner-quickstart

You can also run a Linux VM from inside macOS if you find that easier

**Comment by wushengyidong** [comment]
> You can either build it from source or just run using docker. Instructions are here https://github.com/helium/miner#miner-quickstart
> 
> You can also run a Linux VM from inside macOS if you find that easier

I mean if wanna do some debug. And I cannot do this in the docker.

**Comment by Vagabond** [comment]
It does work on MacOS but we don't support it. I believe the dependencies you need are all in homebrew. If someone wants to document the build requirements we could add that to the documentation.
