### ISSUE TITLE
Hotspot unreachable due to changing IP

### ISSUE THREAD

**Issue by karlbnapf** [helium/miner#998]
The problem is already described here: https://github.com/helium/miner/issues/916. As I cannot reopen the issue, I'm creating a new one. Quick recap: Nightly router reconnects forced by many ISPs lead to situations where hotspots are de facto unreachable for most of the time (even if port forwarding is enabled). This is due to the fact that listen_addrs lags up to one day. Note that many people on Discord seem to have similar problems. The only known workaround is to reboot the hotspot when a new IP gets assigned to the router. Solution proposals (feasibility of implementation needs to be checked):

1. Communicate IP address more frequently so that listen_addrs is up to date most of the time
2. Allow users to specify a DynDNS name to the hotspot, which remains the same even if IP address changes

**Comment by shawaj** [comment]
Cross posting from libp2p repo @karlbnapf https://github.com/helium/erlang-libp2p/issues/373

**Comment by El-livo** [comment]
this is still happening needs a work around creating and a firmware update distributing to hotspots asap!

**Comment by abhay** [comment]
This report is somewhat old so I'm going to close it for now. Hopefully you've seen some improvement since the more recent releases. Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.

**Comment by MMM1970** [comment]
> This report is somewhat old so I'm going to close it for now. Hopefully you've seen some improvement since the more recent releases. Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.

@abhay I know you closed this thread off but I am stuck in trying to fix this problem with my Milesight UG65.  It was working Ok but then not beaconing, then my public IP changed and I have trouble ever since.  Heliumstatus.io says its unreachable

Can you help?
